- anagram/anagram_test.rs
- anagram/example.rs
- beer-song/beer-song_test.rs
- beer-song/example.rs
- bob/example.rs
- custom-set/custom-set_test.rs
- custom-set/example.rs
- dominoes/dominoes_test.rs
- dominoes/example.rs
- grade-school/example.rs
- grade-school/grade-school_test.rs
- leap/example.rs
- nucleotide-count/example.rs
- nucleotide-count/nucleotide-count_test.rs
- parallel-letter-frequency/example.rs
- parallel-letter-frequency/parallel-letter-frequency_test.rs
- phone-number/example.rs
- phone-number/phone-number_test.rs
- point-mutations/point-mutations_test.rs
- rna-transcription/example.rs
- rna-transcription/rna-transcription_test.rs
- robot-name/example.rs
- robot-name/robot-name_test.rs
- tournament/example.rs
- tournament/tournament_test.rs
- word-count/example.rs
- word-count/word-count_test.rs
I updated the examples and tests to at very least build with the latest Rust nightly (build 2015-03-31). Hopefully this will let get the tests passing.
Obviously there's a lot more work to do, but I think just getting it to compile is a good start.
> Update Examples to the lastest Rust nightly

- SETUP.md
Depends on this getting merged: https://github.com/exercism/xrust/pull/29
> Add information to the SETUP.md file

- allergies/Cargo.lock
- allergies/Cargo.toml
- allergies/example.rs
- allergies/tests/allergies.rs
- config.json
Hi folks,
Here is a Rust implementation of the Python [allergies](https://github.com/exercism/xpython/tree/master/allergies) exercise.
Would appreciate any feedback. :smile:
> Add implementation of "allergies" exercise.

- config.json
- difference-of-squares/Cargo.lock
- difference-of-squares/Cargo.toml
- difference-of-squares/example.rs
- difference-of-squares/tests/difference-of-square.rs
- raindrops/Cargo.lock
- raindrops/Cargo.toml
- raindrops/example.rs
- raindrops/tests/raindrops.rs
Implementation of two new exercises: raindrops and difference-of-squares.
Any problem, let me know.
> New exercises: raindrops and difference-of-squares

- SETUP.md
Wrapped lines to match the instructions in exercises, and use the other link syntax to increase readability.
> Format SETUP.md nicely

- config.json
- etl/Cargo.lock
- etl/Cargo.toml
- etl/example.rs
- etl/tests/etl.rs
Let me know if there are any problems. :)
> Added etl exercise.

- config.json
- hexadecimal/Cargo.lock
- hexadecimal/Cargo.toml
- hexadecimal/example.rs
- hexadecimal/tests/hexadecimal.rs
> Added hexadecimal exercise.

- _test/check-exercises.sh
- config.json
- forth/Cargo.lock
- forth/Cargo.toml
- forth/example.rs
- forth/src/lib.rs
- forth/tests/forth.rs
Can't say it wasn't fun!
I went ahead and added an exercise skeleton, to guide the student.
Let me know if it's ok or not. :)
> Added forth.

- config.json
- nucleotide-codons/Cargo.lock
- nucleotide-codons/Cargo.toml
- nucleotide-codons/example.rs
- nucleotide-codons/tests/codons.rs
> Add nucleotide-codons exercise

- point-mutations/example.rs
- point-mutations/tests/point-mutations.rs
- robot-name/example.rs
- robot-name/tests/robot-name.rs
This is related to issue #45. hamming_distance() now returns a Result. I added 2 test cases to test for this error.
> point-mutations: handle error case for different lengths ; robot-name: fix name format

- config.json
- minesweeper/Cargo.lock
- minesweeper/Cargo.toml
- minesweeper/example.rs
- minesweeper/tests/minesweeper.rs
Here's the minesweeper exercise from the xhaskell stream.
My first attempt at contributing an exercise, and I'm a Rust beginner, so pull with care :).
> Add minesweeper exercise

- grade-school/tests/grade-school.rs
Make names more explicit (to show that values are returned sorted from
grades and grade).
Add more tests for the empty cases.
> Improve tests in grade school.

- circular-buffer/example.rs
I did a couple changes to the example code of circular-buffer based on suggestions by user petertseng. I think this version is much more readable.
> refactored example.rs for exercise circular-buffer

- config.json
- docs/INSTALLATION.md
- docs/RESOURCES.md
- docs/TESTS.md
> Added docs folder with documentation for api v3

- docs/INSTALLATION.md
The previous installing chapter has been subsumed into this chapter:
https://github.com/rust-lang/rust/commit/2f4fbb2bf5bceb2816925789c7d9534debbcd2b0
> INSTALLATION: Link to getting-started

- config.json
- exercises/roman-numerals/Cargo.lock
- exercises/roman-numerals/Cargo.toml
- exercises/roman-numerals/example.rs
- exercises/roman-numerals/tests/roman-numerals.rs
I've implemented the standard tests and provided an example solution
that I think isn't terrible. I pretty much stole it from the Ruby
example!
> Implement Roman Numerals exercise

- docs/LEARNING.md
Closes #87
Links to 5 useful resources for students learning Rust from scratch.
> Added LEARNING.md

- docs/ABOUT.md
Fixes #88
The Awesome Rust is a well-maintained and wide-ranging list of Rust
projects. Instead of calling out specific projects in the About.md, it
made sense to link to this list.
I didn't mention the "complier has your back" sentiment from #58, but I
did try to get to the same place by saying that all Rust code will be
memory safe & fast.
> Explain some of Rust's projects, appeal

- exercises/hello-world/GETTING_STARTED.md
help.exercism.io was deprecated in December 2015
> hello-world: link to exercism Rust page not help.exercism.io

- exercises/sieve/example.rs
- exercises/sieve/tests/sieve.rs
> Remove Sieve struct from API

- exercises/roman-numerals/example.rs
- exercises/roman-numerals/tests/roman-numerals.rs
Fixes #99 
As per our discussion, @JIghtuse and @petertseng
> Update Roman API to use From and ToString traits

- config.json
Based on conversation in https://github.com/exercism/xrust/issues/112,
and by looking at the solutions that students have provided, the
Gigasecond exercise is very straightforward. Other than introducing
Crates it doesn't teach much about Rust.
Also, having it come between Hamming and Nucleotide is odd, since those exercises share domain knowledge.
> Move Gigasecond to the second exercise

- SETUP.md
> broken link to crates and modules

- exercises/custom-set/tests/custom-set.rs
I accidentally left out the 'ignore test' flag. Fixing.
> Set Ignore flag on 2nd-last test

- exercises/custom-set/tests/custom-set.rs
> Update custom-set test order

- config.json
- exercises/wordy/Cargo.lock
- exercises/wordy/Cargo.toml
- exercises/wordy/example.rs
- exercises/wordy/tests/wordy.rs
This implements the Wordy exercise and follows the canonical test suite.
I'm placing this problem before custom-set. Fairly late in the current problem track, but before some of the most complex exercises. This is a hard problem to place, because I think the implementations will vary. My initial solution is not that complex, but it is extremely brittle. Some students might go farther and implement a real-ish lexer/parser
But, by the time students get to this part of the track there's no question that they'll know enough Rust to be able to complete this problem
I would like to discuss the API I'm using. Specifically...
In the most Rust-like languages, [Go](https://github.com/exercism/xgo/blob/master/exercises/wordy/wordy_test.go) does not implement a `WordProblem` concept, but …
> Implement wordy

- exercises/anagram/example.rs
- exercises/beer-song/example.rs
- exercises/nucleotide-codons/example.rs
- exercises/tournament/example.rs
In general, this is taking advantage of Rust's iterator methods (map, filter, collect) where possible, which I believe to be more idiomatic.
Another potential place not covered here:
* `etl` could use `flat_map`. I wanted to evaluate whether that would make things too complicated. Will investigate and send a PR.
> Iterator methods

- exercises/anagram/example.rs
Instead of creating a String manually, pushing into it in a loop, and
then returning it, we can just `collect` on an iterator to turn the
vector into a String.
> anagram: Use collect

- exercises/pangram/tests/pangram.rs
> Add test to capture invalid range-based solutions

- config.json
- exercises/acronym/Cargo.lock
- exercises/acronym/Cargo.toml
- exercises/acronym/example.rs
- exercises/acronym/tests/acronym.rs
- problems.md
I implemented the tests based on the canonical suite and wrote an example solution. I haven't added it to config.json or problems.md yet since I wasn't sure where you would want it.
> Implement Acronym

- exercises/pascals-triangle/src/lib.rs
Bringing this in as a separate commit. Based on #200, do we want this stub? 
My thought is yes, since it doesn't introduce anything that the tests don't already require.
> Stub file for pascals-triangle

- config.json
- exercises/atbash-cipher/Cargo.lock
- exercises/atbash-cipher/Cargo.toml
- exercises/atbash-cipher/example.rs
- exercises/atbash-cipher/tests/atbash-cipher.rs
- problems.md
cc @IanWhitney @petertseng 
I have lumped the whole thing into a single commit, but if you want smaller commits for each step, I can do that too.
> Implemented atbash cipher

- exercises/bowling/tests/bowling.rs
Added in https://github.com/exercism/x-common/pull/444
> bowling: Add test cases involving 11 after final strike

- exercises/queen-attack/tests/queen-attack.rs
Closes #259
As discussed in #259 this test can be removed.
> queen attack: Remove unnecessary test

- exercises/rectangles/Cargo.lock
- exercises/rectangles/Cargo.toml
- exercises/rectangles/tests/rectangles.rs
https://github.com/exercism/x-common/pull/497
> rectangle 1.0.0: test widths and heights of 1

- exercises/bracket-push/Cargo.lock
- exercises/bracket-push/Cargo.toml
- exercises/bracket-push/tests/bracket-push.rs
https://github.com/exercism/x-common/pull/747
> bracket-push 1.1.0: Test wrong closing bracket

- exercises/bob/Cargo.lock
- exercises/bob/Cargo.toml
- exercises/bob/example.rs
- exercises/bob/tests/bob.rs
* Make unit tests comply with the [problem specification](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json) v1.0.0.
* Update Cargo.toml version correspondingly.
* Update example.rs.
* Delete Cargo.lock.
> bob: Update tests to conform with the problem spec

- docs/EXERCISE_README_INSERT.md
We moved the contributing documentation out of the problem specifications repository.
> Link to new contributing documentation

- _test/check-exercises.sh
As done in https://github.com/exercism/rust/pull/270
> check-exercises: Require presence of src/lib.rs

- config.json
- exercises/prime-factors/Cargo.lock
- exercises/prime-factors/Cargo.toml
- exercises/prime-factors/README.md
- exercises/prime-factors/example.rs
- exercises/prime-factors/tests/prime-factors.rs
Changed my `vec!()` -> `vec![]` before submitting pull.  
This is a pretty simple one as well.  Not new rust topics learning, just algorithm implementation.
> prime-factors: Add exercise

- config/maintainers.json
By request:
https://github.com/exercism/haskell/pull/581#issuecomment-317640892
https://github.com/exercism/erlang/pull/173#issuecomment-317750784
It does not seem too presumptious to assume that the same comment
applies here!
> maintainers: etrepum is an alumnus

- config.json
- exercises/accumulate/.meta/hints.md
- exercises/accumulate/Cargo.lock
- exercises/accumulate/Cargo.toml
- exercises/accumulate/README.md
- exercises/accumulate/example.rs
- exercises/accumulate/tests/accumulate.rs
I learned something new from this one.  However, I'm not sure that function pointers is the best way for people to solve this or if it is generally the correct thing to do in Rust.   
I'm looking for some feedback from more experienced on this.  I have not seen function pointers much in Rust docs.  But this may just be because map takes care of them for most cases.
Do you think .meta\hints.md is required?  I only found function pointers by searching with that text and hitting on a Stack Overflow answer.  I worry if the user doesn't understand that phrase, they could get stuck.
> accumulate: Add exercise

- config.json
- docs/ABOUT.md
A website redesign requires some additional copy in a new "blurb" field. 
References https://github.com/exercism/discussions/issues/173
> Add nextercism blurb and edit ABOUT.md

- config.json
See exercism/problem-specifications#884
> config: replaced "math" topic with "mathematics"

- exercises/etl/README.md
- exercises/ocr-numbers/README.md
- exercises/pascals-triangle/README.md
- exercises/rna-transcription/README.md
https://github.com/exercism/problem-specifications/pull/901
https://github.com/exercism/configlet/pull/85 (as-yet unreleased)
> Titles: capitalise initialisms, add punctuation

- exercises/gigasecond/tests/gigasecond.rs
> Change link in gigasecond exercise to second edition of rust book

- exercises/book-store/Cargo.toml
- exercises/book-store/tests/book-store.rs
Update to keep in sync with exercism/problem-specifications#1021
> book-store: Update to match canonical-data 1.1.0

- exercises/parallel-letter-frequency/HINTS.md
- exercises/parallel-letter-frequency/README.md
fixes two broken links in README.md
> parallel-letter-frequency: fix broken links in README.md

- README.md
> remove broken link to exercism documentation

- exercises/isbn-verifier/README.md
Fixes https://github.com/exercism/problem-specifications/issues/1011.
A simple definition of what the system should do before getting in to
exactly what the digits of an ISBN mean would be good, in my opinion.
https://github.com/exercism/problem-specifications/pull/1019
> isbn-verifier: Include more succinct description of ISBN-10

- exercises/reverse-string/.meta/hints.md
- exercises/reverse-string/README.md
- exercises/reverse-string/tests/reverse-string.rs
Closes #428 
"運動" changed to "子猫" as per request.
> reverse-string: Add test case for wide characters

- exercises/two-bucket/README.md
https://github.com/exercism/problem-specifications/pull/1093
https://github.com/exercism/problem-specifications/pull/1192
> two-bucket: remove broken link

- exercises/book-store/Cargo-example.toml
- exercises/book-store/Cargo.toml
- exercises/book-store/example.rs
- exercises/book-store/src/lib.rs
- exercises/book-store/tests/book-store.rs
> book-store: use integer number of cents, not floating-point numbers

- exercises/bowling/example.rs
- exercises/bowling/src/lib.rs
- exercises/bowling/tests/bowling.rs
see individual commit messages
> bowling: Use Option for score and specific errors for roll; add stub

- exercises/prime-factors/src/lib.rs
> prime-factors: replace u32 with u64 in stub

- config.json
Closes #460 by exclusion.
Performed with the following command line:
```shell
jq '.exercises |= map(
if .difficulty == 3 then
.difficulty=4
elif .difficulty == 6 then
.difficulty=7
else
.
end
)' config.json > config.json.new && \
diff config.json config.json.new ; \
mv config.json.new config.json
```
> Adjust config.json to return exercise difficulties to one of 1, 4, 7, 10

- exercises/atbash-cipher/src/lib.rs
- exercises/hamming/src/lib.rs
- exercises/isogram/src/lib.rs
- exercises/luhn/src/lib.rs
- exercises/pangram/src/lib.rs
- exercises/run-length-encoding/src/lib.rs
- exercises/say/src/lib.rs
- exercises/scrabble-score/src/lib.rs
- exercises/word-count/src/lib.rs
Hello, i saw all the opened issues and added the templates to the specified files. I hope everything is fine :)
Edited by @coriolinus to auto-close relevant issues:
Closes #515 (atbash-cypher).
Closes #509 (hamming).
Closes #505 (isogram).
Closes #513 (luhn).
Closes #511 (pangram).
Closes #507 (run-length-encoding).
Closes #506 (say).
Closes #510 (scrabble-score).
Closes #514 (word-count).
> added templates to 9 exercises

- bin/format_exercises
Should be useful when new exercises are added or when rustfmt is updated
> Added script for rustfmt-ing existing exercises

- docs/ABOUT.md
This contributes to https://github.com/exercism/rust/issues/543.
> Rewrite about section to conform to formatting guidelines

- exercises/clock/.meta/ALLOWED_TO_NOT_COMPILE
- exercises/clock/src/lib.rs
Contributes to #551.
It adds quite a lot, but all additions were necessary for tests to compile.
Don't know if it counts as "taking something away from exercise", but worth a try.
> clock: Added template to stub file

- .travis.yml
- _test/check-exercises-for-authors.sh
- exercises/accumulate/Cargo.toml
- exercises/binary-search/Cargo.toml
- exercises/book-store/Cargo-example.toml
- exercises/book-store/Cargo.toml
- exercises/clock/Cargo.toml
- exercises/crypto-square/Cargo-example.toml
- exercises/crypto-square/Cargo.toml
- exercises/decimal/Cargo-example.toml
- exercises/decimal/Cargo.toml
- exercises/diamond/Cargo.toml
- exercises/macros/Cargo.toml
- exercises/nth-prime/Cargo.toml
- exercises/nucleotide-codons/Cargo.toml
- exercises/palindrome-products/Cargo.toml
- exercises/pig-latin/Cargo-example.toml
- exercises/pig-latin/Cargo.toml
- exercises/poker/Cargo-example.toml
- exercises/poker/Cargo.toml
- exercises/prime-factors/Cargo.toml
- exercises/protein-translation/Cargo.toml
- exercises/proverb/Cargo.toml
- exercises/pythagorean-triplet/Cargo.toml
- exercises/reverse-string/Cargo.toml
- exercises/rotational-cipher/Cargo.toml
- exercises/run-length-encoding/Cargo.toml
- exercises/say/Cargo.toml
> Removed authors from Cargo.toml

- exercises/rotational-cipher/src/lib.rs
> rotational-cipher: Added template to stub file

- exercises/acronym/src/lib.rs
> acronym: Added template to stub file

- exercises/sieve/src/lib.rs
> sieve: Added template to stub file

- exercises/triangle/example.rs
- exercises/triangle/src/lib.rs
- exercises/triangle/tests/triangle.rs
> triangle: Added template to stub file

- exercises/roman-numerals/src/lib.rs
> roman-numerals: Added template to the stub file

- exercises/anagram/example.rs
- exercises/anagram/src/lib.rs
- exercises/anagram/tests/anagram.rs
Closes #455.
Also contributes to #551.
>  anagram: Made test cases insensitive to the returned result order

- exercises/binary-search/src/lib.rs
> binary-search: Added template to the stub file

- exercises/luhn-from/.meta/description.md
- exercises/luhn-from/README.md
- exercises/luhn-trait/.meta/description.md
- exercises/luhn-trait/README.md
Updates commands in README for the new version of CLI
> Updated commands to download luhn exercise

- exercises/bracket-push/src/lib.rs
> bracket-push: Added template to the stub file

- exercises/queen-attack/example.rs
- exercises/queen-attack/src/lib.rs
- exercises/queen-attack/tests/queen-attack.rs
Should I update the test suite to ensure that the invalid file/rank is returned from the `ChessPosition::new()` method?
> queen-attack: Added template to the stub file

- exercises/bob/README.md
https://github.com/exercism/problem-specifications/issues/1257
https://github.com/exercism/problem-specifications/pull/1267
> bob: limit scope of incoming messages

- _test/check-configlet-fmt.sh
> check-configlet-fmt.sh is now run only when config.json is modified

- exercises/phone-number/src/lib.rs
> phone-number: Added template to the stub file

- exercises/robot-name/src/lib.rs
- exercises/robot-name/tests/robot-name.rs
Also removed the comments in the test suite, since they are redundant with the added template.
> robot-name: Added template to the stub file

- exercises/protein-translation/example.rs
- exercises/protein-translation/src/lib.rs
- exercises/protein-translation/tests/proteins.rs
The returned type seems like it could be changed from `Result<&str, &str>` to `Option<&str>`, but
I would wait for an approval, before changing anything.
> protein-translation: Added template to the stub file

- exercises/pig-latin/src/lib.rs
> pig-latin: Added template to the stub file

- exercises/tournament/src/lib.rs
> tournament: Added template to the stub file

- exercises/rectangles/src/lib.rs
> rectangles: Added template to the stub file

- exercises/dominoes/src/lib.rs
> dominoes: Added template to the stub file

- exercises/minesweeper/src/lib.rs
> minesweeper: Added template to the stub file

- exercises/dot-dsl/.meta/hints.md
- exercises/dot-dsl/README.md
As per this comment: https://github.com/exercism/rust/pull/588#discussion_r211516228
> dot-dsl: Fixed small typo in hints

- config.json
This PR cleans `config.json` after the #620 
Closes #632
> bracket-push: Removed the outdated "from_trait" tag

- exercises/luhn-from/.meta/ALLOWED_TO_NOT_COMPILE
- exercises/luhn-from/src/lib.rs
> luhn-from: Added template to the stub file

- exercises/parallel-letter-frequency/.meta/hints.md
- exercises/parallel-letter-frequency/README.md
> parallel-letter-frequency: Updated the links to the Nightly Rust section of the Book in the README hints

- config/maintainers.json
Will merge as soon as Travis passes.
> publish coriolinus maintainer status on website

- exercises/book-store/example.rs
- exercises/book-store/src/lib.rs
- exercises/book-store/tests/book-store.rs
- exercises/difference-of-squares/example.rs
- exercises/difference-of-squares/src/lib.rs
- exercises/dominoes/example.rs
- exercises/dominoes/src/lib.rs
- exercises/dominoes/tests/dominoes.rs
- exercises/macros/tests/macros.rs
- exercises/raindrops/example.rs
- exercises/raindrops/src/lib.rs
- exercises/react/tests/react.rs
- exercises/robot-simulator/src/lib.rs
- exercises/spiral-matrix/example.rs
- exercises/spiral-matrix/src/lib.rs
- exercises/spiral-matrix/tests/spiral-matrix.rs
Closes #601.
My intent is to create one commit per exercise. False positives (such as all-your-base, binary-search, etc.) are simply checked off in that issue once they have been inspected. True positives are checked off once a commit exists in this PR.
> inappropriate usize

- exercises/rna-transcription/tests/rna-transcription.rs
> rna-transcription: Added checks for the value of Err to the test_invalid_dna_input test

- exercises/acronym/src/lib.rs
- exercises/grep/tests/grep.rs
Noticed this while doing the exercises.
> acronym, grep: fix misspellings

- bin/init_exercise.py
> fix incorrect link to canonical data

- _test/check-exercises.sh
> check-exercises: Rewritten script to compile only modified exercises

- config/maintainers.json
I didn't want to give too many people the wrong idea given my level of
(in)activity, but I have decided to solve the problem by giving that
indication in the bio.
> maintainers: Show myself and my bio on the website

- README.md
See https://github.com/exercism/exercism/issues/4441.
> Update URL for Code of Conduct link on README.

- exercises/wordy/example.rs
It seems that some elements of the example solution can be removed, so I propose some.
Includes the commit from #703 because that is a part of some changes made.
I intend that I will be the one to merge this after review, but if I should be unavailable for that, I recommend not squashing on merge.
> wordy: simplify example solution

- _test/check-exercises.sh
- _test/ensure-stubs-compile.sh
> check-exercises;ensure-stubs-compile: Fixed the scripts to not repeatedly detect the same modified exercise

- exercises/leap/.meta/hints.md
- exercises/leap/README.md
This struck me as a good hint to add. I've used C but couldn't remember
how to test for divisibity because I've never done much with math
functions.
> leap:add a hint

- exercises/saddle-points/tests/saddle-points.rs
It would be nice to cover case, when all points are actually saddle points.
> saddle-points: Add test for all saddle points

- util/exercise/Cargo.toml
- util/exercise/src/cmd/generate.rs
- util/exercise/src/cmd/update.rs
> exercise crate: Made the crate subcommands to traverse an arbitrary-depth cases list

- exercises/bracket-push/Cargo.toml
- exercises/bracket-push/tests/bracket-push.rs
Note that I decided to keep original authors, because all of the value being added in the upstream commits was in saying what the test case was, so the fact that I happened to be the person performing the translation to a given track doesn't mean that I have added any value here
> bracket-push 1.5.0

- exercises/forth/Cargo.toml
- exercises/forth/tests/forth.rs
Note that 1.6.0 and 1.7.0 are out, but require some changes to the example solution that I've not made yet. I might make them at some point, but no guarantees.
> forth 1.5.0

- _test/check-exercises.sh
- bin/test-exercise
A possible way to see which ones are taking longer
> test-exercise: time each cargo command

- exercises/grep/Cargo.toml
- exercises/grep/tests/grep.rs
Adds 4 new test cases plus clippy suggestions.
Relevant PR: https://github.com/exercism/problem-specifications/pull/1356
>  grep: Updated the exercise to 1.2.0 version

- exercises/phone-number/Cargo.toml
- exercises/phone-number/example.rs
- exercises/phone-number/tests/phone-number.rs
Relevant PRs:
- https://github.com/exercism/problem-specifications/pull/772
- https://github.com/exercism/problem-specifications/pull/1090
- https://github.com/exercism/problem-specifications/pull/1120
- https://github.com/exercism/problem-specifications/pull/1327
- https://github.com/exercism/problem-specifications/pull/1337
- https://github.com/exercism/problem-specifications/pull/1361
The old example solution did not pass some new tests, so I replaced it with my own old solution, which may be not too optimal, but it passes all the tests
> phone-number: Updated the exercise to the 1.6.1 version

- exercises/forth/Cargo.toml
- exercises/forth/example.rs
- exercises/forth/tests/forth.rs
Note that I'm not altogether pleased with how much additional code had to be added to the example. It's certainly true that *some* code has to be added, but I'd be glad to hear if there is a clearer way to achieve the objectives of 1.6.0. I request particular scrutiny be given to that portion.
> forth 1.7.0

- _test/check-configlet-fmt.sh
- _test/check-exercise-crate.sh
- _test/check-exercises.sh
- _test/ensure-stubs-compile.sh
> check-exercises, ensure-stubs-compile, check-configlet-fmt.sh, check-exercise-crate.sh: Fixed the scripts to work on weekly builds

- exercises/rotational-cipher/example.rs
- exercises/rotational-cipher/tests/rotational-cipher.rs
>  rotational-cipher: Added negative shift test cases

- config/maintainers.json
> Added thedarkula to the maintainers list.

- util/exercise/Cargo.lock
- util/exercise/Cargo.toml
- util/exercise/src/fetch_configlet.rs
- util/exercise/src/lib.rs
> exercise crate: Dropped the dependency on the 'git2' crate

- exercises/grains/README.md
- exercises/grains/tests/grains.rs
This PR updates the `grains` README to the latest version and renames the test functions according to the "test_{case_description}" style. It also introduces the separate property function.
> grains: Updated the exercise README and test functions

- util/exercise/Cargo.lock
- util/exercise/Cargo.toml
- util/exercise/src/cmd/configure.rs
- util/exercise/src/cmd/generate.rs
- util/exercise/src/cmd/update.rs
- util/exercise/src/errors.rs
- util/exercise/src/fetch_configlet.rs
- util/exercise/src/lib.rs
- util/exercise/src/main.rs
Via `cargo fix --all --edition-idioms --allow-dirty`
> exercise crate: Migrated the crate to the Rust 2018 edition

- config.json
This pull pequest is part of the [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project). For more on the background there, please see [issue #809](https://github.com/exercism/rust/issues/809) opened by @kytrinyx.
This is part of "Round 2", where we're looking at the start of the track and adding exercises that bridge the gap to the harder exercises and that are easy to mentor (ideally, mentoring on the earliest exercises will largely consist of copying, pasting, and tweaking snippets of text that address common concerns).
In this case, the gap between the second ("Gigasecond") and third exercise ("Bracket Push") is significant. The choice for "Bob" here is entirely pragmatic: it's already implemented as a side exercise, so we have it available, and it's easier than …
> Promoted "Bob" to be a core exercise.

- util/exercise/Cargo.lock
- util/exercise/Cargo.toml
- util/exercise/src/cmd/configure.rs
- util/exercise/src/cmd/generate.rs
- util/exercise/src/fetch_configlet.rs
- util/exercise/src/main.rs
This PR fixes the `or_fun_call` clippy warnings, reducing the noise in the clippy output, so that more relevant warning would be visible.
>  exercise crate: Fixed the 'or_fun_call' warnings

- config.json
> hamming: change exercise topic to 'option'

- exercises/reverse-string/example.rs
Since Reverse String is now our first real core exercise, this updates the corresponding `example.rs`.
> Updated example.rs notes for 'Reverse String'.

- exercises/dot-dsl/README.md
tracks https://github.com/exercism/problem-specifications/pull/1538
attn: @aburd
> dot-dsl: update README

- exercises/anagram/.meta/hints.md
- exercises/anagram/README.md
This PR's adds some hints for the problem that to my opinion are needed. There are no indications other than the tests failing that the solution is case insensitive. Another thing that I found out by trial and error is that the word itself cannot be part of the solution. 
Those 2 should be better explained. So added hints for both of them
> anagram: Added 2 hints

- exercises/leap/.meta/hints.md
- exercises/leap/README.md
Use a link to the current version of the rust book.
> leap: Update link in hints.md

- exercises/decimal/example.rs
- exercises/isbn-verifier/example.rs
- exercises/react/example.rs
- exercises/rectangles/example.rs
individual commit messages
Preference: Prefer not squashed, but can live with squashed if individual messages are preserved in the resulting commit message
> decimal, isbn-verifier, react, rectangles: Heed Rust 1.37.0 warnings

- exercises/etl/README.md
- exercises/scrabble-score/README.md
- exercises/space-age/README.md
- exercises/word-count/README.md
the word-count one is hopefully clearer to the students; the others are not so important but came along for the ride
do not squash
> etl, scrabble-score, space-age, word-count: READMEs from problem-specifications

- config.json
Demotes bob to a side exercise.
See https://github.com/exercism/rust/pull/876 for rationale.
> Demotes bob to a side exercise

- config.json
Using topics from https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt
* `conditionals` - flow control depending on wether numbers have a factor or not
* `strings` - this is all about composing a string
* `type_conversion` - need to handle `&str` and `String` strings
* `variables` - building up the string is easiest when usign a variable.
> raindrops: pick topics from problem-specifications

- exercises/simple-linked-list/example.rs
- exercises/simple-linked-list/src/lib.rs
- exercises/simple-linked-list/tests/simple-linked-list.rs
Closes #826.
Applies the first two suggestions from that issue. The third suggestion is demo'd in https://github.com/exercism/rust/commit/3101695e79d9163c68ee4216b943871521f17b48, but I reverted it because IMO students at this point in the track will have trouble coming up with an appropriate implementation.
> simple-linked-list: idiomaticity

- config/maintainers.json
In an email, ijanos indicated  no longer having time to be a maintainer.
> maintainers: make ijanos an alumnus

- config/maintainers.json
Related to #913
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/exercism/rust/918)
> Add filalex77 to maintainers.json

- exercises/bowling/tests/bowling.rs
While solving this exercise I passed all the tests but I realized that 1 result was wrong. Here I added the test.
> bowling: Add a new test

- exercises/dot-dsl/README.md
- exercises/dot-dsl/tests/dot-dsl.rs
The `new` method on the Node expects a `&str` not a `&String` everywhere else in the tests.
> Fix dot-dsl test

- docs/RESOURCES.md
The rust programming language on discord is a great place to discuss about the language and for quick queries. Added the following links in the resources.
> Added Rust official discord in RESOURCES.md

- exercises/bob/tests/bob.rs
> Fixes #922

- config/maintainers.json
I took the liberty of grabbing your name as the exercism website displayed it as Meade. 
/cc @filalex77
> fix @filalex77's display name

- config/maintainers.json
After discussing with @efx and @coriolinus I realized I was being very silly by not formally adding myself as a maintainer. Here's to version control.
> &self -> RustMaintainer

- exercises/simple-linked-list/README.md
It looks like this site is no longer maintained. If you visit it in your
browser you get what appears to be a spammy site.
> Simple linked list: Remove spammy link

- exercises/all-your-base/example.rs
- exercises/all-your-base/src/lib.rs
- exercises/all-your-base/tests/all-your-base.rs
This is the continuation of #855.
> all-your-base: Fixing test: Empty slice corresponds to zero II

- docs/TESTS.md
Fixed link based on this issue: https://github.com/exercism/website-copy/issues/1175
> Updated Rust Doc Link

- exercises/clock/tests/clock.rs
Edge case: Negative minutes that make the hours negative
> clock: Add a test case for some edge case

- exercises/protein-translation/example.rs
> synchronize example with src/lib.rs

- exercises/poker/Cargo-example.toml
- exercises/poker/example.rs
Some little updates so the example works with the current versions of Rust and the Counter crate.
> poker: example update

- exercises/poker/example.rs
Implementing `std::convert::TryFrom` as this has become the norm.
> poker: using 'TryFrom' in example

- exercises/affine-cipher/README.md
- exercises/grade-school/README.md
- exercises/isbn-verifier/README.md
- exercises/luhn/README.md
- exercises/minesweeper/README.md
- exercises/palindrome-products/README.md
- exercises/robot-name/README.md
- exercises/scale-generator/README.md
- exercises/simple-cipher/README.md
- exercises/simple-linked-list/README.md
- exercises/two-bucket/README.md
- exercises/two-fer/README.md
individual commit messages (properly attributed to original authors) explain
these commits should not be squashed when merging
> README updates from problem-specifications

- exercises/rna-transcription/example.rs
- exercises/rna-transcription/src/lib.rs
- exercises/rna-transcription/tests/rna-transcription.rs
> Correct naming conventions in rna-transcription exercise

- exercises/nucleotide-count/README.md
Points out that understanding DNA is not necessary to complete the
exercise, as well as making the input format more clear.
https://github.com/exercism/problem-specifications/issues/1716
Thanks to SleeplessByte, rpottsoh, kotp, ErikSchierboom, etc :)
https://github.com/exercism/problem-specifications/pull/1719
> README update from problem-specifications: Update nucleotide-count description

- exercises/parallel-letter-frequency/tests/parallel-letter-frequency.rs
> [parallel-letter-frequency]: Test non-integer multiple of threads

- exercises/book-store/example.rs
- exercises/grep/example.rs
> remove redundant clones in exercise examples

- exercises/dot-dsl/example.rs
- exercises/phone-number/example.rs
> use next() instead of nth(0) in exercise examples

- exercises/dot-dsl/example.rs
clippy::filter_next
https://rust-lang.github.io/rust-clippy/master/index.html#filter_next
Helps address https://github.com/exercism/rust/pull/1012
> dot-dsl: Replace filter(p).next() with find(p)

- exercises/crypto-square/example.rs
clippy::same_item_push
https://rust-lang.github.io/rust-clippy/master/index.html#same_item_push
Helps address https://github.com/exercism/rust/pull/1012
> crypto-square: replace repeated push with resize

- exercises/decimal/Cargo-example.toml
- exercises/decimal/example.rs
https://rust-lang.github.io/rust-clippy/master/index.html#manual_unwrap_or
> decimal: Use unwrap_or; use ? instead of try_opt

- exercises/space-age/.meta/hints.md
- exercises/space-age/README.md
Suggest the use of macro to reduce boilerplate and increase readability.
> space-age: Update README.md

- .github/workflows/tests.yml
> update other references to main

- concepts/floating-point-numbers/introduction.md
> debullet floating point numbers introduction

- concepts/integers/introduction.md
> debullet and add example of `1_000_000`

- config.json
> update current status

- reference/README.md
Restores https://github.com/exercism/v3/pull/222/files to this
repository.
I wanted a copy of this enumeration handly while polishing our initial
set of exercises.
> restore our initial concept enumeration

- concepts/destructuring/introduction.md
> write an introduction to destructuring

- config.json
- exercises/concept/vec-macro/.docs/hints.md
- exercises/concept/vec-macro/.docs/instructions.md
- exercises/concept/vec-macro/.docs/introduction.md
- exercises/concept/vec-macro/.meta/design.md
- exercises/concept/vec-macro/.meta/exemplar.rs
- exercises/concept/vec-macro/src/lib.rs
Starting work to close #1063.
I intend to create follow up issues for the `vec-collect` and the others mentioned [here](https://github.com/exercism/v3/pull/2918).
> finish vec-macro

- _test/WINDOWS_README.md
I noticed this the other day looking through documentation.
I'm not on Windows but if anyone tries it this helps.
> fix inaccurate path name

- .editorconfig
I adapted this from [nushell's
editorconfig](https://github.com/nushell/nushell/blob/main/.editorconfig)
Baby steps for #1110.
> start an editorconfig

- bin/format_exercises
- exercises/concept/entry-api/tests/entry_api.rs
- exercises/concept/enums/src/lib.rs
- exercises/concept/numbers/.meta/exemplar.rs
- exercises/concept/options/tests/options.rs
- exercises/concept/string-vs-str/.meta/exemplar.rs
- exercises/concept/string-vs-str/src/lib.rs
- exercises/concept/structs/.meta/exemplar.rs
- exercises/practice/accumulate/src/lib.rs
Start addressing #1129.
I added error handling flag `-e` and shellcheck lints.
I'll push up fixes for the associated failures.
> add error handling to CI formatting check

- _test/verify-exercise-difficulties.sh
- config.json
Close #1131.
I verified it manually for a practice exercise.
This script does not operate on concept exercises at the moment. I'm
unsure of how to combine two top-level properties in jq and treat them
as one list. So improvements welcome!
> fix CI difficulty check for practice exercises

- .gitignore
- exercises/practice/spiral-matrix/tests/spiral-matrix.rs
> address clippy +beta failures

- exercises/practice/poker/tests/poker.rs
> Clean up extra commas in Poker tests

- docs/maintaining.md
Capture some of our discussion in #1141 for a broader audience.
I see this as freer form: we can adjust it as we make decisions.
I'm not wed to the name or location.
I liked the bash track's approach with `POLICIES.md`.
But I feel formal policies are inappropriate at this time.
> start notes on maintaining process

- concepts/newtype-pattern/links.json
- config.json
I was not planning on any further work on this concept now, but I did research the topic a bit today and found this description helpful.
Instead of trusting my inconsistent note-taking, `concepts/` it is!
> link to TRPL example

- _test/count-ignores.sh
- exercises/concept/enums/tests/enums.rs
- exercises/concept/vec-macro/tests/vec_macro.rs
> fix count-ignores.sh

- _test/check-exercises.sh
Based on discussion, a simple rewording suffices.
Close #1164.
> reword comment

- util/exercise/src/main.rs
Keeping it simple!
Based on our conversation here: https://github.com/exercism/rust/pull/1174#discussion_r582314920
> fix a small typo in the exercise utility help

- concepts/structs/links.json
- exercises/concept/entry-api/.docs/hints.md
- exercises/concept/structs/.docs/hints.md
- exercises/concept/vec-macro/.docs/hints.md
Close #1173.
I did not fix string-vs-str since #1165 should address that.
> correctly format hints.md files

- concepts/macros-procedural/links.json
I learned about procedural macros the other day and found these links
helpful.
Is it accurate to say procedural macros are a kind of meta-programming?
> include helpful links on procedural macros

- concepts/numbers/introduction.md
👋 Hey there, first time contributing to OS. Tried to do my homework and read up on contributing guides but if I've missed anything, just let me know! 
- I took a crack at writing an intro to numbers for #1124. I saw there was an emphasis on staying concise so I tried to keep that in mind, however it feels like there's a lot going on with numbers! I broke the content down into two sections and based the information off of the Rust book. 
- Not sure if this is what we'd be looking for, but it's a starting point at least and I can edit from here if needed. Feedback welcome, thanks :]
> write numbers intro

- .markdownlint.yaml
- concepts/destructuring/introduction.md
- concepts/numbers/introduction.md
- concepts/numeric-traits/about.md
- concepts/option/about.md
- concepts/string-vs-str/about.md
- concepts/structs/about.md
- docs/CONTRIBUTING.md
- docs/maintaining.md
> enable markdown lint rules 12 and 31

- config.json
Close #1162
https://github.com/exercism/docs/pull/64
> restore wasm categorization

- concepts/string-vs-str/links.json
@efx adding in the builder pattern here
> add a reference to the builder pattern

- exercises/practice/forth/src/lib.rs
We should demonstrate good style to students.
> use more idiomatic style for Forth default

- concepts/booleans/introduction.md
> [booleans] update Introduction.md

- concepts/&str/about.md
It's a start. Tried to cover the likeliest gotchas without going into the weeds.
> [&str] update about.md

- concepts/char/about.md
I realize this will be tricky to get right.
> [char] about.md

- concepts/box/about.md
first draft. Tried not to bring other concepts into it, but to justify Box, I kinda had to, I think.
> [box] update about.md

- concepts/collect/about.md
> [collect] update about.md

- concepts/fold/about.md
First draft. Hopefully this is more on track than the first draft of `collect`.
> [fold] update about.md

- concepts/functions/about.md
> [functions] update about.md

- concepts/lifetimes/links.json
From [discussion](https://github.com/exercism/rust/pull/1236/files#r613621861)
> capture NLL link

- concepts/references/about.md
First draft. Kind of pointless to explain references without a bit of ownership and borrowing. Hopefully I didn't make a hash of it.
> [references] update about.md

- config.json
- exercises/concept/rpn-calculator/.docs/hints.md
- exercises/concept/rpn-calculator/.docs/instructions.md
- exercises/concept/rpn-calculator/.docs/introduction.md
- exercises/concept/rpn-calculator/.meta/config.json
- exercises/concept/rpn-calculator/.meta/design.md
- exercises/concept/rpn-calculator/.meta/exemplar.rs
- exercises/concept/rpn-calculator/Cargo.toml
- exercises/concept/rpn-calculator/src/lib.rs
- exercises/concept/rpn-calculator/tests/rpn-calculator.rs
I am a lot happier with this exercise for `vec-stack` than Final Electric Bill (#1248). However, it may be less guided than Concept exercises should be, as well as having a bunch of prerequisites.
Supersedes #1248, closes #1104.
> Add RPN Calculator exercise

- config/maintainers.json
I need to divert my free cycles to personal life.
> step down as a maintainer

- exercises/practice/word-count/.docs/instructions.md
Closes https://github.com/exercism/rust/issues/1265
> Update instructions for the word count exercise.

- exercises/shared/.docs/tests.md
Move them from v2 location to v3 location.
Closes #1288.
> Extract track-specific test instructions

- exercises/shared/.docs/help.md
Move them from v2 location to v3 location.
Closes #1287.
> Extract track-specific help instructions

- exercises/practice/proverb/.docs/instructions.md
This is based on feedback from a colleague trying to learn Rust via exercism. He noted that it wasn't at all clear what was expected following "arbitrary" arrays. There's no singlar obvious right answer, but the test suite is clear about what it expects.
> Clarify the instructions for length zero arrays in the Rust proverbs exercise.

- exercises/practice/luhn-from/.meta/config.json
They are already in the author list.
Fixes: https://github.com/exercism/rust/issues/1294
> Remove IanWhitney from Contributors

- config.json
Hotfix for this issue: https://github.com/exercism/rust/issues/1303
> Set CSV Builder to be WIP

- exercises/concept/role-playing-game/.docs/instructions.md
Found that while doing the exercise, hope it helps !
> Fix incorrect variable name in instructions

- exercises/concept/role-playing-game/.docs/instructions.md
s/If they Players's/If the Player's/
Signed-off-by: Sebastian Fricke <sebastian.fricke@posteo.net>
> Fix typo in concept exercise role-playing-game

- exercises/practice/clock/.docs/instructions.md
- I was a bit confused by the limited amount of instructions on this one, but when i checked it out locally, was super happy to have found some extra docs.
- Just added some things that i thought would help others to the main instructions page
> Added more instructions for the exercise

- concepts/vec-macro/.meta/config.json
- config.json
Fix blurb for vec-macro concept. Builds on top of #1345 and must be rebased against main after that PR is merged.
> Re-add vec macro concept

- config.json
I'm disabling the analyzer as it doesn't work property at the moment. See https://github.com/exercism/rust-analyzer/issues/38#issuecomment-970268809
> Disable analyzer

- exercises/concept/rpn-calculator/.docs/instructions.md
> docs(rpn-calculator): fix typo

- exercises/concept/assembly-line/.docs/hints.md
Removing extra blank line in hints file.
> docs: remove extra blank line

- exercises/practice/minesweeper/.docs/instructions.md
It's not obvious to the average student that ascii is an option in this exercise. Some people will know this trick, but a lot of people just wouldn't think of it and it makes the exercise more pleasurable. It also makes collecting the results a little nicer at the end too.
Please feel free to suggest changes in the wording!
> It's not obvious that ascii is an option in this exercise

- exercises/concept/role-playing-game/.docs/introduction.md
I believe I've hit on all the points that the design.md file mentioned.  Hope this is what you're looking for.
> role-playing-game: Filled introduction.md with content

- exercises/practice/diffie-hellman/.meta/config.json
Hopefully, this will allow the user to add dependencies (e.g. rand, num_bigint, etc.).  Not sure how to test this for breakage other than simply committing it and testing it on Exercism.
> diffie-hellman: Added Cargo.toml to config.json

- exercises/concept/role-playing-game/.meta/config.json
I figured I should put my name down as a contributor, assuming that my Introduction contribution is accepted.  I hope I'm not being too presumptuous.
> role-playing-game: Added name to config.json

- exercises/concept/role-playing-game/.docs/introduction.md
Edited line 77 - I think it's a little easier to read now.
> role-playing-game: Edit to introduction.md

- exercises/practice/diffie-hellman/.meta/config.json
One more among many it seems. 😉
> diffie-hellman: Added name to config.json

- exercises/practice/simple-cipher/.meta/example.rs
- exercises/practice/simple-cipher/Cargo.toml
Update to use a more recent version of `rand`
> simple-cipher: Update Cargo.toml to use rand 0.8

- exercises/concept/lucians-luscious-lasagna/.docs/introduction.md
I added a semicolon to the let statement in the lucians-luscious-lasagna exercise introduction.
> Add the missing semicolon to the end of the let statement

- concepts/methods/.meta/config.json
- concepts/methods/about.md
- concepts/methods/introduction.md
- concepts/methods/links.json
- config.json
Fixes #1066. This PR introduces `methods` concept and can be linked to [`health-statistics`](https://github.com/exercism/rust/blob/main/exercises/concept/health-statistics/src/lib.rs) until we find an appropriate way to structure exercises for `struct` and `methods` separately.
@coriolinus @petertseng @bobahop Happy to get your feedback :)
> #1066: Methods Concept

- exercises/concept/resistor-color/.meta/config.json
As suggested [here](https://github.com/exercism/exercism/issues/6353#issuecomment-1125995207).
Should be sufficient to close https://github.com/exercism/exercism/issues/6353.
> resistor-color: set `test_runner: false`

- concepts/iterators/.meta/config.json
- concepts/iterators/about.md
- concepts/iterators/introduction.md
- concepts/iterators/links.json
- config.json
This PR partially addresses #1065. The next step is to either write up a concept exercise for iterators or find an appropriate existing exercise for iterators concept.
> #1065: Write iterators concept

- exercises/concept/resistor-color/.meta/exemplar.rs
- exercises/concept/resistor-color/Cargo.toml
Update crate enum-iterator version from the issue #1495
> Update enum-iterator crate version and exemplar in resistor color exercise

- exercises/concept/assembly-line/.docs/introduction.md
Reorganized the text to make it a little easier to follow.
> Update introduction.md in `assembly-line`

- exercises/concept/semi-structured-logs/src/lib.rs
Added missing _unimplemented_ message to exercise.
> concept/semi-structured-logs: add unimplemented message

- concepts/functions/introduction.md
brackets are for example [], braces are {}
> small typo corrected. updated brackets to braces

- exercises/practice/allergies/tests/allergies.rs
> Update test allergies.rs

- exercises/practice/alphametics/.meta/Cargo-example.toml
- exercises/practice/book-store/.meta/Cargo-example.toml
- exercises/practice/crypto-square/.meta/Cargo-example.toml
- exercises/practice/decimal/.meta/Cargo-example.toml
- exercises/practice/diffie-hellman/.meta/Cargo-example.toml
- exercises/practice/grep/.meta/Cargo-example.toml
- exercises/practice/pig-latin/.meta/Cargo-example.toml
- exercises/practice/poker/.meta/Cargo-example.toml
- exercises/practice/robot-name/.meta/Cargo-example.toml
- exercises/practice/scale-generator/.meta/Cargo-example.toml
This PR will update all cargo example edition based on #1532 issue
> Update cargo example edition

- exercises/practice/acronym/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/bowling/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/dot-dsl/.meta/config.json
- exercises/practice/forth/.meta/config.json
- exercises/practice/grade-school/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/high-scores/.meta/config.json
- exercises/practice/minesweeper/.meta/config.json
- exercises/practice/paasio/.meta/config.json
- exercises/practice/pig-latin/.meta/config.json
- exercises/practice/poker/.meta/config.json
- exercises/practice/reverse-string/.meta/config.json
- exercises/practice/scale-generator/.meta/config.json
- exercises/practice/simple-cipher/.meta/config.json
- exercises/practice/simple-linked-list/.meta/config.json
- exercises/practice/two-fer/.meta/config.json
There have been a bunch of little tweaks to metadata, mostly adding punctuation, but also tweaking some wording for readability.
This updates all the changed metadata in one fell swoop.
> Sync metadata with problem specifications

- exercises/practice/poker/tests/poker.rs
Additional tests for straights with the same tests also for straight flushes
> Additional tests for straights

- exercises/concept/magazine-cutout/tests/magazine-cutout.rs
test_magzine_has_more_than_words_available_than_needed() -> test_magazine_has_more_than_words_available_than_needed()
> Fix typo in magazine test

- exercises/practice/wordy/src/lib.rs
> wordy: Remove unnecessary struct

- exercises/practice/pangram/.approaches/all-contains/content.md
- exercises/practice/pangram/.approaches/all-contains/snippet.txt
- exercises/practice/pangram/.approaches/bitfield/content.md
- exercises/practice/pangram/.approaches/bitfield/snippet.txt
- exercises/practice/pangram/.approaches/config.json
- exercises/practice/pangram/.approaches/hashset-is-subset/content.md
- exercises/practice/pangram/.approaches/hashset-is-subset/snippet.txt
- exercises/practice/pangram/.approaches/hashset-len/content.md
- exercises/practice/pangram/.approaches/hashset-len/snippet.txt
- exercises/practice/pangram/.approaches/introduction.md
- exercises/practice/pangram/.articles/config.json
- exercises/practice/pangram/.articles/performance/code/main.rs
- exercises/practice/pangram/.articles/performance/content.md
- exercises/practice/pangram/.articles/performance/snippet.md
Initial commit for file structure and code. Explanatory details to follow...
> Pangram approaches

- exercises/concept/resistor-color/.docs/instructions.md
Thanks for maintaining!
I wasn't sure what task number one and task number three are exactly. I think numbering them in the list explicitly will increase clarity.
> Update instructions for resistor-color

- config.json
Clean up topics and move to practices.
I renamed topic `chars` to practices `char`
> Clean up topics vs practices in config.json #1407

- exercises/practice/ocr-numbers/.meta/config.json
> ocr-numbers: Fix broken source url

- exercises/practice/leap/.approaches/match-on-a-tuple/content.md
Fixed a couple typos in the table on the match on a tuple page.
> Leap approaches typo fixes

- exercises/practice/simple-linked-list/.approaches/config.json
- exercises/practice/simple-linked-list/.approaches/do-not-keep-track-of-length/content.md
- exercises/practice/simple-linked-list/.approaches/do-not-keep-track-of-length/snippet.txt
- exercises/practice/simple-linked-list/.approaches/introduction.md
- exercises/practice/simple-linked-list/.approaches/keep-track-of-length/content.md
- exercises/practice/simple-linked-list/.approaches/keep-track-of-length/snippet.txt
Approaches for Simple Linked List.
> Simple Linked List approaches

- exercises/practice/allergies/.approaches/config.json
- exercises/practice/allergies/.approaches/introduction.md
- exercises/practice/allergies/.approaches/vec-on-new/content.md
- exercises/practice/allergies/.approaches/vec-on-new/snippet.txt
- exercises/practice/allergies/.approaches/vec-when-requested/content.md
- exercises/practice/allergies/.approaches/vec-when-requested/snippet.txt
> Allergies approaches

- exercises/practice/binary-search/.approaches/config.json
- exercises/practice/binary-search/.approaches/introduction.md
- exercises/practice/binary-search/.approaches/looping/content.md
- exercises/practice/binary-search/.approaches/looping/snippet.txt
- exercises/practice/binary-search/.approaches/recursion/content.md
- exercises/practice/binary-search/.approaches/recursion/snippet.txt
> Binary Search approaches

- exercises/practice/binary-search/tests/binary-search.rs
> Clarify reason for disabled lint

- exercises/practice/forth/.docs/instructions.append.md
- exercises/practice/forth/.docs/instructions.md
motivation:
https://github.com/exercism/rust-test-runner/issues/30#issuecomment-1640048470
> Improve instructions of 'forth'

- exercises/practice/decimal/tests/decimal.rs
source:
https://github.com/exercism/rust/pull/1572
> Decimal: Compare different numbers of digits

- exercises/practice/anagram/src/lib.rs
> Fix lifetime annotation in anagram stub

- rust-tooling/src/exercise_generation.rs
This improves the workflow of generating tests for exercises and synchronizing them with problem-specifications.
After generating the tests, they would have to be formatted manually. This is now done automatically when generating the tests.
> Pipe generated tests through rustfmt

- exercises/practice/space-age/.docs/instructions.md
- exercises/practice/space-age/.meta/config.json
- exercises/practice/space-age/.meta/test_template.tera
- exercises/practice/space-age/.meta/tests.toml
- exercises/practice/space-age/tests/space-age.rs
Note the exclusion of the test case "invalid planet causes error".
> Sync space-age with problem-specifications

- exercises/practice/raindrops/.docs/instructions.md
- exercises/practice/raindrops/.meta/test_template.tera
- exercises/practice/raindrops/.meta/tests.toml
- exercises/practice/raindrops/tests/raindrops.rs
> Sync raindrops with problem-specifications

- exercises/practice/knapsack/.meta/test_template.tera
- exercises/practice/knapsack/.meta/tests.toml
- exercises/practice/knapsack/tests/knapsack.rs
> Sync knapsack with problem-specifications

- exercises/practice/phone-number/.meta/test_template.tera
- exercises/practice/phone-number/.meta/tests.toml
- exercises/practice/phone-number/tests/phone-number.rs
> Sync phone-number with problem-specifications

- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/tests/roman-numerals.rs
> roman-numerals: sync

- exercises/practice/pangram/.meta/test_template.tera
- exercises/practice/pangram/.meta/tests.toml
- exercises/practice/pangram/tests/pangram.rs
- rust-tooling/generate/src/cli.rs
- rust-tooling/generate/src/main.rs
> pangram: sync

- exercises/practice/nth-prime/.meta/test_template.tera
- exercises/practice/nth-prime/.meta/tests.toml
- exercises/practice/nth-prime/tests/nth-prime.rs
> nth-prime: sync

- config.json
I believe some work went into the exercise order by the previous maintainers, so I didn't completely redo it. I only fixed the obviously bad aspects of the order:
- difficulty 10 exercises being way too early in the track
- new, easy exercises being at the end of the exercise list
forum discussion:
https://forum.exercism.org/t/rust-track-exercise-order/10855
> improve exercise order

- exercises/practice/series/.docs/instructions.append.md
Fix typo of instructions for problem "Series"
> Fix typo of instructions for problem "Series"

- exercises/practice/triangle/.docs/instructions.append.md
[forum discussion](http://forum.exercism.org/t/pr-to-update-instructions-append-md-for-triangle/11752/6)
> triangle: update instructions append

- config.json
This is similar to various tracks needing `Pascals Triangle` => `Pascal's Triangle`,  which was discussed in the [forum](http://forum.exercism.org/t/48in24-exercise-08-27-pascals-triangle/12056/9).
> Eliuds Eggs => Eliud's Eggs

- exercises/practice/alphametics/.meta/test_template.tera
- exercises/practice/alphametics/.meta/tests.toml
- exercises/practice/alphametics/tests/alphametics.rs
> alphametics: sync

- exercises/practice/fizzy/tests/fizzy.rs
> fizzy: remove macro from tests

- exercises/practice/allergies/.meta/test_template.tera
- exercises/practice/allergies/tests/allergies.rs
> allergies: remove test util function

- exercises/practice/crypto-square/.meta/Cargo-example.toml
- exercises/practice/crypto-square/.meta/example.rs
- exercises/practice/crypto-square/.meta/test_template.tera
- exercises/practice/crypto-square/.meta/tests.toml
- exercises/practice/crypto-square/tests/crypto-square.rs
> crypto-square: sync

- exercises/practice/hamming/.meta/test_template.tera
- exercises/practice/hamming/.meta/tests.toml
- exercises/practice/hamming/tests/hamming.rs
> hamming: sync

- exercises/practice/nucleotide-count/.meta/additional-tests.json
- exercises/practice/nucleotide-count/.meta/test_template.tera
- exercises/practice/nucleotide-count/.meta/tests.toml
- exercises/practice/nucleotide-count/tests/nucleotide-count.rs
> nucleotide-count: sync

- exercises/practice/saddle-points/.meta/test_template.tera
- exercises/practice/saddle-points/tests/saddle-points.rs
> saddle-points: remove util function in tests

- exercises/practice/clock/.meta/test_template.tera
- exercises/practice/clock/.meta/tests.toml
- exercises/practice/clock/tests/clock.rs
> clock: sync

- exercises/practice/dot-dsl/Cargo.toml
- exercises/practice/dot-dsl/tests/dot-dsl.rs
> dot-dsl: Remove dependency in test code

- exercises/practice/allergies/.meta/test_template.tera
- exercises/practice/allergies/tests/allergies.rs
Clippy started warning against this.
> allergies: remove unconventional whitespace

- exercises/practice/dot-dsl/tests/dot-dsl.rs
forum discussion:
https://forum.exercism.org/t/unnecessary-to-string-calls-in-the-test-file-of-dot-dsl/15525
> dot-dsl: allow owned and borrowed strings

- exercises/practice/palindrome-products/src/lib.rs
Just corrected a minor inaccurate description that may cause confusion.
> Inaccurate description in comments

- exercises/practice/doubly-linked-list/.meta/config.json
> doubly-linked-list: Add blurb

- exercises/practice/high-scores/.meta/test_template.tera
- exercises/practice/high-scores/.meta/tests.toml
- exercises/practice/high-scores/tests/high_scores.rs
The diff is a little bit strange since I had to move 3 tests to the bottom. Everything _should_ be fine though.
> high-scores: Sync tests & generate with template

- exercises/practice/largest-series-product/.meta/test_template.tera
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/tests/largest_series_product.rs
It should be easy to review each commit individually.
> largest-series-product: Sync tests & add template

- bin/checkout_pinned_problem_specifications_commit.sh
- exercises/practice/affine-cipher/.docs/instructions.md
- exercises/practice/saddle-points/.docs/instructions.md
- exercises/practice/sieve/.docs/instructions.md
No changes in tests, the updates in the instructions do not require any rust-specific appends as far as I can see.
> Sync exercise files with problem-specifications

- config.json
forum discussion: https://forum.exercism.org/t/rust-etl-exercise-is-a-bit-odd/16921
> etl: downgrade to easy difficulty
