anagram/tests/anagram.rs
Seems reasonable to ignore case when checking for anagrams.
=> add test in anagram, that bAnana is not an anagram of banana

anagram/tests/anagram.rs
Ignore the final test on anagram (initially, only the first test should run)
=> Ignore the final test on anagram (initially, only the first test should run)

phone-number/example.rs, phone-number/tests/phone-number.rs
Using 00000000 as an invalid number is rather odd - I think Option is much better style in Rust and properly uses the type system.
What do you think?
=> Use rust style error handling in phone number

anagram/tests/anagram.rs
If the order returned by anagrams_for is different from the test
case's expected output, the test would fail while being correct.
```
---- test_multiple_anagrams stdout ----
thread 'test_multiple_anagrams' panicked at 'assertion failed: `(left == right)` (left: `["largely", "regally", "gallery"]`, right: `["gallery", "regally", "largely"]`)', tests/anagram.rs:42
```
Ordering both arrays before comparison fixes the false positive.
=> Fixed false positive with test_multiple_anagrams

robot-name/tests/robot-name.rs
According to exercism/exercism.io#2441 , a valid name should be:
* exactly five letters long
* start with two upper case letters
* end with three numeric digits
The previous code had a bug allowing shorter names to pass, as long
as the first two characters where uppercase letters:
e.g. 'AB' and 'ABC', 'AB1', 'AB*'
=> robot-name : improve test for name validity

dominoes/example.rs, dominoes/tests/dominoes.rs
I mostly explained these tests in the individual commit messages, so take a look there. I had to fix example.rs to give correct results for the new tests (it was incorrect on a few).
I believe Rust is the only language that is using the dominoes exercise, hopefully I'm not wrong on that point (otherwise, it would probably be prudent to port these tests to the other languages as well, right?)
=> Dominoes tests

circular-buffer/Cargo.lock, circular-buffer/Cargo.toml, circular-buffer/example.rs, circular-buffer/tests/circular-buffer.rs, config.json
The tests were ported from the Ruby version, the example implementation is similar to the Go example.
=> add exercise circular-buffer

leap/tests/leap.rs
It is possible to have green tests and not exactly correct solution. See, for example: http://exercism.io/submissions/a5147caadb714d428816389ec6fa62f0
=> leap: Check another exceptional century

config.json, hello-world/Cargo.lock, hello-world/Cargo.toml, hello-world/GETTING_STARTED.md, hello-world/example.rs, hello-world/tests/hello-world.rs
This commit fixes https://github.com/exercism/todo/issues/47.
Disclaimer, I do _not_ have a "working" knowledge of rust, like it
requires in the reference issue. All feedback is definitely welcome.
=> Add hello-world exercise

exercises/bob/tests/bob.rs
test_shout_without_question_mark() -> test_non_question_with_question_mark()
=> Correct name of a test.

exercises/rna-transcription/example.rs, exercises/rna-transcription/tests/rna-transcription.rs
This was introduced in 7877d6389ed47d8c3e6631274c1c66a0b4c4ec54 back
when the exercises was ported to xrust, but there's no clear reason why
we would want the RNA to be convertible to a string.
* It's not relevant to the problem statement.
* There's no clear use case for why this is something that should be
required.
* Other languages don't do this.
* Other exercises in xrust don't do this.
Given these reasons, it makes more sense to remove it.
Closes #76
=> rna-transcription: Remove as_ref test

config.json, exercises/gigasecond/Cargo.lock, exercises/gigasecond/Cargo.toml, exercises/gigasecond/example.rs, exercises/gigasecond/tests/gigasecond.rs
Adding the [Gigasecond exercise](http://x.exercism.io/problems/gigasecond) for the Rust track.
This exercise is a little odd in Rust as the core language has no library for dealing with time. There was the Time crate, but that was pulled from the standard library. Based on [this RFC](https://github.com/rust-lang/rfcs/issues/619) from last year, the Chrono crate appears to be the best current library for dealing with time. I've used Chrono here.
Either because I'm still new to Rust, or because of an actual limitation in Chrono, the best way I could write the tests was to have everything be a UTC DateTime. This means that the tests that only use dates still require the slightly weird `.and_hms(0,0,0)` function at the end to make them DateTime-y. I did this because Chrono only seems to …
=> Implement Gigasecond exercise

.travis.yml
A suggestion from https://docs.travis-ci.com/user/languages/rust
The motivation here is simply that we get alerted ahead of time if an
upcoming release of Rust would break our tests for whatever reason. In
such a case we'd like to be alerted of it ahead of time.
=> travis: test beta and nightly

exercises/allergies/example.rs, exercises/allergies/tests/allergies.rs
As mentioned in #64, using Allergies(3) or similar constrains the
implementation to using tuple structs, whereas there could be a range of
possible implementations. By using `new` as the test interface,
implementations can choose what internal representation they'd like. For
instance, the example solution still uses a tuple struct, but you could
imagine solutions using regular structs.
Closes #64 (and I believe this is the only exercise that constrains the
implementation in such a way)
=> allergies: use Allergies::new for test interface

config.json, exercises/queen-attack/Cargo.lock, exercises/queen-attack/Cargo.toml, exercises/queen-attack/example.rs, exercises/queen-attack/tests/queen-attack.rs
There is no common set of tests for this exercise, so implementation is
a bit....free form. I think there are two interesting things to look at,
what tests to use, and how to use them.
Which Tests
I first surveyed all of the languages that implement this exercise and
looked at what they tested. In order of prevalence, the five most common
test types cover:
1. Can 2 queens attack each other?
2. [Can 2 pieces occupy the same
space](https://github.com/exercism/xelixir/blob/0965c4e107de68979a493b82f9f0859773fcb83b/exercises/queen-attack/queen_attack_test.exs#L26)?
3. [Comparing string representations of the
chessboard](https://github.com/exercism/xelixir/blob/0965c4e107de68979a493b82f9f0859773fcb83b/exercises/queen-attack/queen_attack_test.exs#L33)
4. [Does a chessboard start with the queens …
=> Implement Queen Attack

SETUP.md
help.exercism.io was deprecated sometime around December 2015.
Closes #92
=> SETUP.md: link to exercism Rust page not help.exercism.io

exercises/queen-attack/example.rs, exercises/queen-attack/tests/queen-attack.rs
Transferring ownership to can_attack is poor design. It prevents you
from using the piece after the function has been called. A more Rust-ish
approach is to borrow.
I know this exercise is now available, so I'm not sure how easy it is to change the API now. But I sure hope we can!
=> Change API to borrow piece to can_attack

exercises/dominoes/example.rs, exercises/dominoes/tests/dominoes.rs
Some solutions may automatically declare a singleton input to be valid
without checking it can actually be chained. Singletons still need to be
checked because a singleton (1, 1) can be chained with itself, but
(1, 2) can't. This adds a test for (1, 2). The test for (1, 1) already
existed.
The example solution needs to be corrected to address this as well.
=> dominoes: test singletons that can't be chained

exercises/dominoes/tests/dominoes.rs
The input is valid (it's a list of dominoes), it's just that it can't be
chained.
Closes #100
=> dominoes: Rename invalid_input -> no_chains

_test/tournament_setup.sh
At the time of e1acae44f0e82e64b3e6b257c2bc2f32cdad3acc, it was
necessary to use this script because tests were run in a temporary
working directory. Thus the convention of `{slug}_setup.sh` was born.
Then in fc69e6eba391f68700a7631fdba06c5f034f0c5e this became unnecessary
because instead the entire directory is getting copied. Not only that
but the convention of running `{slug}_setup.sh` was removed.
Since tournament_setup.sh is unnecessary and no longer being run, let's
remove it.
Closes #105.
=> _test: rm tournament_setup.sh

exercises/rna-transcription/example.rs
The presence of the removed line causes a compile-time warning. This
warning was introduced in #81 with the removal of the AsRef tests for
the rna-transcript exercise.
To help us detect warnings in the future, #107 is opened as well.
=> rna-transcript: remove unused AsRef use

.travis.yml, _test/check-exercises.sh
I'm motivated because I've seen that I introduced warnings in #81 and
they were not caught.
Definitely open to discussion on whether it should be required! I don't
want this to be a nuisance, but I do generally like to avoid warnings.
=> travis: add a required build that fails on warnings

exercises/custom-set/example.rs, exercises/custom-set/tests/custom-set.rs
I'm addressing two things in this commit.
Our suite of tests for Custom Set did not follow the [standard json file in x-common](https://github.com/exercism/x-common/blob/d6cd42db16fce5090bb486821a36d0fb1bfb7df2/custom-set.json) They tests have different function names, don't cover symmetric_difference and introduced some functions (`is_superset`) that aren't in the standard test file.
I have not implemented the entire standard test suite as it covers sets of [mixed types](https://github.com/exercism/x-common/blob/d6cd42db16fce5090bb486821a36d0fb1bfb7df2/custom-set.json#L475) which I don't think is even possible in Rust. Vectors have to be homogeneous. Tuples can mix types, but can't change size. Mixed type sets may be possible, but implementing that seems way beyond the scope
of this …
=> Update Custom Set tests to follow standard, update API

exercises/queen-attack/example.rs, exercises/queen-attack/tests/queen-attack.rs
Fixes #118
`Queen::new` now expects a `ChessPosition` instead of a tuple. `ChessPosition::new` returns a Result, indicating if the position is valid or not.
I've added a few tests at the start to capture the behavior of `ChessPosition`.  The tests of Queen have their API usage updated, and have been renamed for readability.
=> Queen Attack: Replace tuple with ChessPosition

exercises/custom-set/example.rs, exercises/custom-set/tests/custom-set.rs
Details about the updated test suite are at
https://github.com/exercism/x-common/pull/232
This commit brings our tests in line with the new standard and removes
now-unnecessary code from the example solution
=> Update Custom Set to follow new standard suite

config.json, exercises/scrabble-score/Cargo.lock, exercises/scrabble-score/Cargo.toml, exercises/scrabble-score/example.rs, exercises/scrabble-score/tests/scrabble-score.rs
Implements the Scrabble Score exercise.
As of right now there is no official test suite for Scrabble Score. There is a PR (https://github.com/exercism/x-common/pull/161), but it is not yet merged.
I am following the test suite in that PR, with one exception. I thought it was likely that a common naive implementation would be to map through the chars, find the score and then simply unwrap the value. Like this:
```rust
word.chars().map(|c| values.get(&c).fold(0, |sum, v| sum + v.unwrap())
```
So I have added a test that uses a non-English character that will cause this implementation to panic.
I've put this exercise between the Nucleotides and Roman Numerals, figuring that it did similar character iteration and value mapping.
My example implementation probably leaves a lot to be desired. I …
=> Add Scrabble Score

exercises/word-count/tests/word-count.rs
The `check_word_count` function tries remove elements from the `HashMap`
which may not be there and then `.unwraps()` them directly causing a
panic if they are not there. This is changed to `unwrap_or(0)` to show
that no values were found to improve the failure message in this case.
=> Update test to prevent panic with missing value

.gitignore
Just so that we don't accidentally commit backup files, compiled code or
source files.
=> Ignore extraneous Rust files

SETUP.md
I was trying to figure out how how I even found this repository. I think
I stumbled into it via the contributing guide on the main exercism repo.
I thought it would be nice to have each exercise contain a pointer to
the repo, so that students can easily see where all this code comes
from.
=> Point students to the xrust Repository

config.json, exercises/pangram/Cargo.lock, exercises/pangram/Cargo.toml, exercises/pangram/example.rs, exercises/pangram/tests/pangram.rs
Implements the Pangram problem and follows the current canonical test
suite.
=> Implement pangram

exercises/allergies/tests/allergies.rs
Fixes #135
- Introducing tests that were missing
- Handling the ordering problem in all tests that check vectors,
encapsulating the solution introduced in #134
- Updating test names to not start with `test_`
- Cargo starts each test result line with "test ", followed by
the test's name.. So these tests looked like "test
test_allergic_to_peanuts".
- Trying to give the final test a useful name. "ignore non allergen
score parts" didn't make much sense to me when I worked on this
exercise. I think the new name better describes what we're trying to
capture.
=> Update Allergies tests to canonical set

exercises/allergies/tests/allergies.rs, exercises/pangram/tests/pangram.rs, exercises/wordy/tests/wordy.rs
https://github.com/exercism/xrust/pull/132/files/adc92c53b5b30d446065ec1b69fa245f9c6033a9#r67608318
https://github.com/exercism/xrust/pull/131/files/4599bf939c3e99f89ae4adc64eb647291f6ef0c0#r67608265
https://github.com/exercism/xrust/pull/142#issuecomment-226972184
I've returned to the previous way of checking, but with `panic!`s so
that I can return useful error messages.
=> Collection of small test fixes

exercises/tournament/tests/output1.txt, exercises/tournament/tests/output2.txt, exercises/tournament/tests/output3.txt
With these output files present, implementation that do not actually
write files will be able to pass the tests, defeating the purpose. See
PR #153 for an example of such a lazy implementation.
They were added in 65b691e235ff2c0bc908950267917460d765ac48 in what I
can only assume was an accident, since they were added long after the
tournament exercise was added to this track in
ee0a6fde1cc8c6c7d5f984511cc6aaddc6dc75ad.
=> tournament: rm output files

exercises/anagram/example.rs, exercises/word-count/example.rs
This was added in Rust 1.2.0, making the custom `lowercase` function
unnecessary.
=> anagram, word-count: use `str#to_lowercase`

exercises/grade-school/example.rs, exercises/parallel-letter-frequency/example.rs, exercises/tournament/example.rs, exercises/word-count/example.rs
These shorten the functions by removing the need to match on the `Entry` cases.
This seems good to make the examples more idiomatic.
Note the exercises that still match on `Entry` cases but were not changed by this PR:
* ~~grade-school: I judged that pushing an element onto the vector then sorting it was sufficiently different from creating a vector with a single element. I can be convinced otherwise.~~
* nucleotide-count: As we discuss in #149, invalid nucleotides should maybe produce errors, so the decision resulting from that discussion may mean using `or_insert` doesn't make sense.
=> parallel-letter-frequency, tournament, word-count: Use `Entry#or_insert`

exercises/dominoes/example.rs, exercises/forth/example.rs
Instead of `loop` that simply `break` in the `None` case, it's better to
use `while let`.
=> dominoes, forth: Use while let

exercises/grade-school/example.rs
They're equivalent, but I figure if there's already a function that does
the clone, might as well use it instead of `map` and making someone read
the body of the map.
=> grade-school: Use `cloned` instead of `map(|k| k.clone())`

exercises/wordy/example.rs
The previous code just added a `: isize` type, but this is already
inferrable from the function signature, so it can just be returned
immediately.
=> wordy: Immediately return in `operand`

exercises/allergies/example.rs
It feels a bit odd to match when the result is going to be a boolean,
and doesn't feel like an idiomatic use of matching.
=> allergies: replace a match -> bool with a comparison

exercises/etl/example.rs
Instead of creating a `BTreeMap` and adding to it, we can just use
`flat_map` on the input and `collect` the result.
=> etl: use flat_map

exercises/hello-world/example.rs
I couldn't figure out why it was necessary, and I actually didn't know
about it off the top of my head (says something about how much Rust I
know). So I tried to remove it to see what compiler error would happen
if it wasn't there. Nothing, it worked.
Well, if it's not necessary, perhaps we should remove it then... simpler
solution for our first exercise should be good, right?
=> hello-world: No ref in pattern

config.json, exercises/robot-simulator/Cargo.lock, exercises/robot-simulator/Cargo.toml, exercises/robot-simulator/example.rs, exercises/robot-simulator/src/lib.rs, exercises/robot-simulator/tests/robot-simulator.rs
Implement Robot Simulator
This follows the [current standard test suite](https://github.com/exercism/x-common/commit/183934754b1847612809db410a8aeb640678f188#diff-7dba901ac525b4fbb77d291df9c5ff9e)
The stub file, as we discussed in #117, is just enough to run `cargo test` and not get any errors from ignored tests.
=> Implement Robot Simulator

exercises/hamming/tests/hamming.rs
I noticed this after @petertseng mentioned the error handling in [#147](https://github.com/exercism/xrust/pull/147#issuecomment-232076551).
The Hamming exercise performs error checking with comparison to `Err(.)`. Most tests (Nucleotide Codons, Queen Attack, Wordy) only check with `is_err()`. The exceptions are Circular Buffer and Forth, but they use more complex error reporting with different conditions and provide an `Error` enum with the correct return values.
Because there is only one error conditions I suggest to remove the fixed value and only check with `is_err()`.
=> Hamming: Make error checking identical to other tests

config.json, exercises/variable-length-quantity/Cargo.lock, exercises/variable-length-quantity/Cargo.toml, exercises/variable-length-quantity/example.rs, exercises/variable-length-quantity/src/lib.rs, exercises/variable-length-quantity/tests/variable-length-quantity.rs
I tried to solve the variable length quantity exercise, because I quite like the encoding scheme. Unfortunately, there are no other implementations of this problem yet, so I am looking for feedback for the function names and test design.
If you know a better way to store bytes back to front into a `Vec` I would be glad to know this, because allocating a vector and then reversing it seems a bit weird.
Values larger than 0x0FFFFFFF could also be tested in `to_bytes`. The `from_bytes` is lacking test for error conditions, like numbers which cannot be represented in `u32` and incomplete byte sequences.
=> Variable Length Quantity

problems.md
The downside of this file is that we have to keep in in sync with
config.json. I'm not sure of a way to leverage travis.yml to check that for
us. Though maybe there is an approach.
Even with that drawback, I think having this file is useful. The PR that
kicked of our problem ordering process is already out of date. And
having something in the repo (instead of a gist or a blog post) makes it
easier to find.
=> Add file that documents the thought behind problem order

exercises/rectangles/tests/rectangles.rs
This was added to x-common in
https://github.com/exercism/x-common/pull/288
It originated from the Lua track. Neither this track nor the Python
track had it prior.
=> rectangles: Add new large test

exercises/grade-school/tests/grade-school.rs
This is the idiomatic and recommended style for this macro.
> (Notice that unlike the println! macro we’ve used in the past, we use
> square brackets [] with vec! macro. Rust allows you to use either in
> either situation, this is just convention.)
>
> https://doc.rust-lang.org/book/vectors.html
=> Use [] instead of () for vec!

config.json, exercises/ocr-numbers/Cargo.lock, exercises/ocr-numbers/Cargo.toml, exercises/ocr-numbers/example.rs, exercises/ocr-numbers/src/lib.rs, exercises/ocr-numbers/tests/ocr-numbers.rs, problems.md
This is not ready for merge. Just getting it up here so that we can start the discussion/bikeshedding.
I've created the tests and the stub file. No working implementation yet. I'm really not sure what implementations people will use for this one. Will be interesting to see.
The one goofy thing I've done here is turn off rustfmt for each test. I don't see a way to turn it off at the file or directory level. I've confirmed that currently a [directory-level ignore (https://github.com/rust-lang-nursery/rustfmt/issues/705) is not supported. But maybe there's a file wide directive that I'm missing?
=> Implement ocr-numbers

exercises/variable-length-quantity/example.rs, exercises/variable-length-quantity/tests/variable-length-quantity.rs
My initial solution to this exercise decided if a byte sequence was incomplete based on whether the accumulator/total is zero when you run out of bytes. This works for the current test case, `0xff`, which leaves `0x7f` in your accumulator, but not for `0x80`.
=> Test variable-length-quantity for an incomplete byte sequence of zero

exercises/anagram/tests/anagram.rs
One can currently pass the tests by comparing a sorted `into_bytes()`, but the same bytes may represent different `char`s.
=> Test anagram for same bytes but different chars

config.json, exercises/space-age/Cargo.lock, exercises/space-age/Cargo.toml, exercises/space-age/example.rs, exercises/space-age/src/lib.rs, exercises/space-age/tests/space-age.rs, exercises/space-age/topics.md, problems.md
First version that passes the tests.
This first commit is intended so we can discuss the crate's API and the tests. There are two decisions I made here that I can see people finding odd.
1. Creating each class as a separate struct.
- I did this because I want students to learn about traits. Obviously they'll have do deal with the `From` trait, but I can also see implementations grappling with shared behavior between the various planets that can be handled via traits.
2. ~~Testing that a struct is equal to a float~~ This was dumb
I'm not bound to either of these decisions, but they were intentional.
-  ~~Update example code to implement `From<u64>` and `From<f64>` generically~~ Skipping, not necessary and probably requires the `num` crate anyway.
=> Implement Space Age

exercises/nucleotide-count/example.rs
In #155, this operation was performed for other exercises (tournament,
parallel-letter-frequency, word-count), but nucleotide-count was skipped
because #149 indicates that invalid nucleotides maybe should produce
errors.
We don't need to wait for x-common to get a nucleotide-count.json before
deciding to make the current implementation more idiomatic though.
If it's eventually decided that `or_insert` doesn't make sense, we can
change it then.
=> nucleotide-count: Use `Entry#or_insert`

exercises/space-age/tests/space-age.rs
Missing parentheses were causing the test to check `expected - abs(actual)` instead of `abs(expected - actual)`.
Fixes #188.
=> space_age: properly check float delta

config.json, exercises/bracket-push/Cargo.lock, exercises/bracket-push/Cargo.toml, exercises/bracket-push/HINTS.md, exercises/bracket-push/example.rs, exercises/bracket-push/tests/bracket-push.rs, problems.md
I'm on the fence about using `&str`. If we don't provide the stub file, it will increase the difficulty of implementing `from`.
But if we include the stub file, then there's almost no extra work involved. Which also might reduce the amount students learn from the exercise.
Sometimes you gotta work with borrowed stuff, right? Writing a `from` implementation for a borrow seems like a useful thing to learn.
So I think my current wish is to:
- Write the tests to expect `From<&'a str>` (`From<&'static str>` would also work, I think)
- Don't include the stub file
=> Implement Bracket Push

exercises/hexadecimal/example.rs
Since there is already a common idiom to use for iterate with index, we
should use it instead of a custom one.
Impact is fairly invisible since hexadecimal has been deprecated, but
still useful for anyone who glances at this code using the repo.
=> hexadecimal: use enumerate() instead of zip(positions)

exercises/react/example.rs, exercises/react/tests/react.rs
=> react: example: Check all dependents to avoid partial write

exercises/hamming/tests/hamming.rs
This fixes issue #194 as the unnecessary alias
`extern crate hamming as dna`
is shortened to just the extern crate statement along with the then necessary changes to the used module name in the asserts.
=> Fixes issue #194.

README.md
a step in fixing https://github.com/exercism/exercism.io/issues/3112.
=> attribute the rust icon (moved here from exercism.io)

README.md
As of #214 we now have attribution for our icon. By the terms of the
license, we must provide a link to the license. Let's comply.
=> README: Link to Creative Commons license

exercises/acronym/tests/acronym.rs
Added in https://github.com/exercism/x-common/pull/405
The "PHP: Hypertext Preprocessor -> PHP" case made it unclear whether
the reason the answer is "PHP" is because it's the first acronym in the
word, or because it's the first letter of each word.
To disambiguate, we add "GNU Image Manipulation Program -> GIMP", which
makes it clear that the answer is not GNU.
=> acronym: Add GIMP case

_test/check-exercises.sh
Add support for optional `Cargo-example.toml` files to satisfy the CI and do not pollute the empty project config file. See discussion in #225
One thing I could not figure out though: where is it defined what files the CLI tool will download? Do I have to modify anything else to prevent the download of `Cargo-examle.toml`?
=> Use example.rs specific Cargo.toml file during CI

docs/INSTALLATION.md, docs/TESTS.md
Fixes #232
- Update the installation directions to point people to the main page.
This has a few advantages to the other link:
1. It will take them to a language-localized page, if available.
2. It will give them a OS-specific install link.
3. It's kept more up-to-date than The Book.
- Update tests doc
Some of the changes here are just little edits. And I'm mentioning that
some exercises now come with a stub file is `src/lib.rs`.
The compilation errors generated by ignored tests is a frequent source
of confusion, I think. So I documented the easiest way around it,
commenting out the tests.
=> Update language docs

config.json, exercises/nucleotide-count/example.rs, exercises/nucleotide-count/tests/nucleotide-count.rs, problems.md
`count` and `nucleotide_counts` both return a Result now.
Closes #149
---
[Too many other language implementations](http://x.exercism.io/problems/nucleotide-count) to look through them all and see what they did. There is no canonical-data.json for this problem yet and I do not have the time to make one.
=> nucleotide-count: Error on invalid nucleotide

README.md
In https://github.com/exercism/x-common/pull/125, the x-common
CONTRIBUTING guide was created.
After that, the x-api contributing guide was gutted in
https://github.com/exercism/x-api/commit/a157350c6c9025314be8fbbaf82b90810bd9204e
This means that it doesn't really make sense to link to the x-api
contributing guide anymore - it has very little relevant information for
contributing to this track.
Consider that the template for a new track repository has been updated
so that they link to the x-common CONTRIBUTING guide too, not x-api:
https://github.com/exercism/x-template/commit/5f9143266d05b29317638f45f1cabaccb860e6ca
=> README: Link to x-common, not x-api, CONTRIBUTING guide

.travis.yml, _test/check-exercises.sh, exercises/parallel-letter-frequency/HINTS.md, exercises/parallel-letter-frequency/benches/benchmark.rs
Addresses #244.
This runs benchmarks in a separate Travis-CI job. This way they run in parallel, only on nightly and benchmark failures aren't mixed with test failures.
`cargo bench` output:
```
running 2 tests
test bench_parallel   ... bench:     114,524 ns/iter (+/- 33,720)
test bench_sequential ... bench:      43,880 ns/iter (+/- 613)
test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured
```
You can see why I made this benchmark. 😄 
Visible in the job: https://travis-ci.org/exercism/xrust/jobs/191194852
=> Benchmark parallel-letter-frequency. Closes #244

config.json
As noted in #195, difficulty rating is hard.
This commit proposes a difficulty rating scale that should be completely
unambiguous, requiring no judgment:
In the last version of problems.md before it was rewritten in #242:
* Everything in "Introduction" stays at 1.
* Everything in "Getting Rusty" gets a 4.
* Everything in "Rust Gets Strange" gets a 7.
* Everything in "Putting it all Together" gets a 10.
It is acknowledged that this is not a perfect difficulty scheme. See,
for example, how many exercises are at 4.
However, it is more accurate than leaving them all at 1 because it is
generally true that those exercises in "Getting Rusty" are more
difficult than those in "Introduction".
It is a starting point from which further adjustments can be made.
I posit that there is little motivation …
=> config.json: Add difficulties

exercises/scrabble-score/tests/scrabble-score.rs
After passing all tests for scrabble-score, I noticed I still didn't have all letters.
Adding them to my implementation at that point of course was trivial, but since there wasn't a test, I wrote one.
Here it is offered for inclusion at the source!
so comments, suggestions, nits and other (constructive) criticism welcome;
This is only my second[1] exercism contribution, so I may need some guidance ;-)
[1] [first contribution](https://github.com/exercism/xrust/pull/249)
=> scrabble-score: add a test for the entire alphabet

config.json, exercises/rotational-cipher/Cargo.lock, exercises/rotational-cipher/Cargo.toml, exercises/rotational-cipher/example.rs, exercises/rotational-cipher/tests/rotational-cipher.rs
This cipher is the same as atbash except it is implemented in a way that allows for 27 possible keys. Some call this the Caesar cipher but the official cryptography term is rotational cipher. For more info see the readme in this pull request.
This exercise should come right after the atbash cipher in terms of ordering and difficulty.
=> added rotational-cipher exercise

exercises/luhn/example.rs, exercises/luhn/tests/luhn.rs
The luhn test suite didn't cover a lot of cases, including:
- Strings of zeros
- Non-alphabetic characters
- Numbers which are only valid if you reverse the string
This adds those tests and updates the example to properly reject symbols (and check that the sum isn't zero).
Let me know if I'm doing something wrong!
**_EDIT:_** FYI I was previously using `!c.is_whitespace()` rather than `c != ' '`. I switched because technically other whitespace like `\t` and `\n` isn't allowed by the letter of the rules.
=> luhn: Update example and add more tests

exercises/grade-school/example.rs, exercises/grade-school/src/lib.rs, exercises/grade-school/tests/grade-school.rs
Previously, grade was expected to return an `Option<&Vec<String>>`.
Because there's a reference inside the lifetime, any implementing School
would have been required to maintain ownership of some vectors so that
they can be lended out. This unnecessarily restricts the implementation.
For example, some implementations may instead have preferred to use
BTreeSet.
If we expect grade to return `Option<Vec<String>>`, the fact that
ownership is given means that a new vector can be made from whatever
internal representation is used.
Closes #254.
=> grade-school: Expect `Option<Vec<String>>` from grade; add stub file

config.json, exercises/hello-world/example.rs, exercises/hello-world/src/lib.rs, exercises/hello-world/tests/hello-world.rs
The introductory exercise should require as little Rust knowledge as
necessary. We'd like to introduce `cargo test` here since it will be
used for all exercises, but introducing Option is too much.
https://github.com/exercism/x-common/issues/520
---
I wouldn't recommend merging this until the corresponding change is made in x-common.
Let's get it ready to go before then.
=> hello-world: simplify to unconditional "Hello, World!"

README.md
It seems good to have the build status easily visible and should make it
easier to get to the build status (instead of have to look for it at
travis-ci.org)
=> README: Add Travis image

config.json, exercises/nucleotide-codons/tests/codons.rs, exercises/protein-translation/Cargo.lock, exercises/protein-translation/Cargo.toml, exercises/protein-translation/example.rs, exercises/protein-translation/tests/codons.rs, exercises/protein-translation/tests/proteins.rs
As noted in https://github.com/exercism/x-common/issues/268 these two
exercises are the same. In this transitionary period, we deprecate
nucleotide-codons (but keep its files available).
If we wish to replace nucleotide-codons with protein-translation
completely, then a database surgery will be needed to transfer all
submissions from nucleotide-codons to protein-translation.
=> replace nucleotide-codons with protein-translation

exercises/hello-world/GETTING_STARTED.md
=> Update hello-world GETTING_STARTED.md to match simplified exercise

exercises/triangle/tests/triangle.rs
[The triangle problem description](https://github.com/exercism/x-common/blob/d7a3c09b6758a8a5d59a2e140e6684031316280a/exercises/triangle/description.md) says the following:
> An isosceles triangle has at least two sides the same length. (It is sometimes specified as having exactly two sides the same length, but for the purposes of this exercise we'll say at least two.)
However, previously the tests for this exercise only allowed isosceles triangles with exactly two sides of the same length.
Removing the expectation that equilateral triangles must return false for `.is_isosceles()` allows students the freedom to decide which definition of "isosceles" they want to implement.
=> triangle: Allow equilateral triangles to also be isosceles

exercises/triangle/tests/triangle.rs
This word is hard to spell! See exercism/x-common#749 for another misspelling.
=> triangle: Fix spelling of "isosceles" in tests

config.json
They were created for #248, but since they're not in the ignore_pattern
they are being served.
See for proof:
http://x.exercism.io/v2/exercises/rust/luhn-from
http://x.exercism.io/v2/exercises/rust/luhn-trait
And note how description.md and metadata.yml appear inside the response.
=> config: Ignore description.md and metadata.yml

exercises/luhn-from/.meta/description.md, exercises/luhn-from/.meta/metadata.yml, exercises/luhn-trait/.meta/description.md, exercises/luhn-trait/.meta/metadata.yml
If, as proposed in https://github.com/exercism/trackler/issues/45, the
proper location of these files moves to the .meta directory, this allows
Trackler to freely change its expectations without having to wait for
this track to move and/or support multiple locations at once.
If the proposal is accepted and implemented, the original files may be
removed. Of course, until then, the original files must remain, since
Trackler still expects them at the original location.
=> copy description.md and metadata.yml to .meta directory

exercises/dominoes/Cargo.lock, exercises/dominoes/Cargo.toml, exercises/dominoes/tests/dominoes.rs
There have always been nine elements, ever since the origin of this test
in https://github.com/exercism/xrust/pull/13#discussion_r115148635
The description incorrectly claimed ten.
https://github.com/exercism/x-common/pull/777
=> dominoes 1.0.1: correctly declare nine elements in largest case

exercises/tournament/Cargo.lock, exercises/tournament/Cargo.toml, exercises/tournament/example.rs, exercises/tournament/tests/tournament.rs
https://github.com/exercism/x-common/pull/773
=> tournament 1.3.0: Add simple start cases, remove invalid lines

exercises/difference-of-squares/Cargo.lock, exercises/difference-of-squares/Cargo.toml, exercises/difference-of-squares/tests/difference-of-square.rs
exercism/x-common#791
---
Supporting commit: Test one function at a time
Instead of testing all three functions for 5 and then all three
functions for 100, let's test one function at a time, so that the
student can make sure one function is solid before moving onto the next.
This also better matches the order the tests are listed in in x-common
(though we are free to change the order if we really want).
Honestly, I don't feel strongly about this, so this is just arbitrary.
=> difference-of-squares 1.1.0: Add tests for 1

exercises/forth/tests/forth.rs
This detects failed attempts where the stack looks as expected but
eval still returns the wrong result.
Also, this should point out some implementation errors more clearly
because you see a specific error result and not just the mismatching
stack content. Especially when there are multiple eval() calls in a row.
=> assert that eval() returns ok where it should

exercises/minesweeper/Cargo.lock, exercises/minesweeper/Cargo.toml, exercises/minesweeper/example.rs, exercises/minesweeper/tests/minesweeper.rs
https://github.com/exercism/x-common/pull/330
As noted, ultimately the list of cases encompasses all the same tests as
before, with a few additions:
* No rows
* No columns
* Mine surrounded by spaces
* 6x6 asymmetric board with 8 mines
* The mines-at-edges cases have been combined (one for horizontal, one
for vertical)
No attempt was made to make the diff as small as possible. Instead, the
file was simply overwritten with a small generator script (#280)
```ruby
require 'json'
data = JSON.parse(File.read(File.join(__dir__, 'canonical-data.json')))
puts <<PREAMBLE
extern crate minesweeper;
use minesweeper::annotate;
fn remove_annotations(board: &[&str]) -> Vec<String> {
board.iter().map(|r| remove_annotations_in_row(r)).collect()
}
fn remove_annotations_in_row(row: &str) -> String { …
```
=> minesweeper 1.0.0: Use x-common cases

config.json, exercises/rna-transcription/Cargo.lock, exercises/rna-transcription/Cargo.toml, exercises/rna-transcription/example.rs, exercises/rna-transcription/tests/rna-transcription.rs
The invalid input cases originally came from
exercism/x-common#119
Today's JSON file can be found at
https://github.com/exercism/x-common/blob/master/exercises/rna-transcription/canonical-data.json
This track was already using all the valid inputs and simply needed to
add these invalid inputs.
=> rna-transcription 1.0.0: reject invalid inputs

exercises/raindrops/Cargo.lock, exercises/raindrops/Cargo.toml, exercises/raindrops/tests/raindrops.rs
Added in https://github.com/exercism/x-common/pull/370
Although I doubt anyone will make the same mistake in this language, I
don't care enough to declare that we should elide these cases.
Note that even though Rust now has the same cases as 1.0.0, we don't
have descriptions like in https://github.com/exercism/x-common/pull/450.
I don't find them terribly necessary, but I suppose they can be added if
they seem good.
We would likely no longer be able to have the tests on one line in that
case, since some descriptions are rather long.
=> raindrops 1.0.0: Add 8, 27, 3125

exercises/forth/example.rs, exercises/forth/src/lib.rs, exercises/forth/tests/forth.rs
Questioning the assumptions: Why must the output be a string?
Reasons I thought of:
* It was this way in the original version of the exercise:
https://github.com/exercism/exercism.io/pull/1188
* But, we have no obligation to follow that.
* It matches the fact that we have strings as inputs.
* But, it is probably more work for the student to create a string.
* It can be argued that it's easier to check the vector.
Previous discussions:
https://github.com/exercism/x-common/pull/394#discussion_r81705078
https://github.com/exercism/xhaskell/pull/412
This doesn't get this track all the way to forth 1.0.0, but is a useful
step there.
=> forth: return `Vec<Value>`, not `String`, from `stack`

exercises/gigasecond/Cargo.lock, exercises/gigasecond/Cargo.toml
Ever since `rust 1.19` was promoted to beta, Travis builds have been
failing.
1.18:
https://travis-ci.org/exercism/xrust/jobs/237495440
1.19:
https://travis-ci.org/exercism/xrust/jobs/240210670
The errors are multiple errors of the form:
error: to use a constant of type `format::ParseError` in a pattern, `format::ParseError` must be annotated with `#[derive(PartialEq, Eq)]`
--> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.2.19/src/format/parsed.rs:476:22
|
476 |                 (Err(OUT_OF_RANGE), _) | (_, Err(OUT_OF_RANGE)) => return Err(OUT_OF_RANGE),
|                      ^^^^^^^^^^^^
That means the necessary commit required to fix it is
https://github.com/chronotope/chrono/commit/0b3218289fe9422ac48631423689fe86658905f9
which appears, at the earliest, in …
=> gigasecond: chrono 0.3

exercises/protein-translation/example.rs, exercises/protein-translation/tests/proteins.rs
Split the earlier pull request into 2 commits -- remove tests for codon compression, and add tests for `of_rna`. It resolves #267.
=> Protein translation (fix #267)

exercises/gigasecond/src/lib.rs
The signature of the function is not at all obvious.
EDIT: It seems this is being discussed in #269, to be it's obvious we want the signatures, the exercises  baffling to a begginer otherwise. I want to use exercism to teach rust at a workshop, I'll gladly add a bunch of stubs if the PRs will be accepted.
=> Add hints to gigasecond lib.rs

config.json
This has been a long time coming.
Ever since https://github.com/exercism/rust/pull/167#r70376973 lifetimes
should not have been a topic for rectangles.
The reasons were discussed there already:
* The "Putting it All Together" problems do not emphasise Rust language
features in general.
* The specific feature "lifetimes" is not implied by this problem. A
sampling of ten submitted solutions shows two solutions with
lifetimes.
I used the https://github.com/exercism/x-common/issues/834 command to
inspect other tracks' topics to see if we can glean any insight here.
C#/F#: parsing, transforming
Lua: strings, performance, control-flow (if/else, loops), algorithms
Based on these, my recommendation:
A possible topic is string parsing, because we are reading in a string
and trying to make sense of …
=> config: rectangles topics: replace lifetimes with algorithm

exercises/gigasecond/Cargo.lock, exercises/gigasecond/Cargo.toml, exercises/gigasecond/example.rs, exercises/gigasecond/src/lib.rs, exercises/gigasecond/tests/gigasecond.rs
When I tried to figure out issues on Playground, I noticed UTC -> Utc.  This looks like a change between 0.3 and 0.4 chrono.   I've updated to use 0.4 and updated the tests and lib.rs.  
Edit: And example.rs after second commit.
=> Update chrono to 0.4, for UTC -> Utc change.

README.md, problem_ordering.md
The leading 'x' is kind of arbitrary. Especially now that we can set
topics on the repositories, we don't need a pattern to distinguish what
is a track or not.
The repository itself has already been renamed.
See https://github.com/exercism/meta/issues/1
=> docs: remove leading 'x' from repository name

_test/WINDOWS_README.md, config.json, exercises/pig-latin/Cargo-example.toml, exercises/pig-latin/Cargo.lock, exercises/pig-latin/Cargo.toml, exercises/pig-latin/README.md, exercises/pig-latin/example.rs, exercises/pig-latin/tests/pig-latin.rs
Implementation of the pig-latin exercise.   This is much less of a mess than my last pull request.   Not sure if difficultly level (2) is right in the JSON.   Someone that has more experience where this would fit in might tweak that value, before going live.  
I also added a file in _test with instructions for running check-exercises.sh for Windows Rust users.  This includes setting up the Ubuntu on Windows sub system and testing against Windows file system hosted files.  With this, I was able to run tests to completion on WIndows.
=> Added pig-latin exercise and Windows Testing Notes

.gitignore
Now that we have an empty src/lib.rs for each exercise as of
https://github.com/exercism/rust/pull/270, we should ease the process of
adding the file by no longer ignoring it.
=> gitignore: remove src

config.json, exercises/clock/.meta/hints.md, exercises/clock/Cargo.lock, exercises/clock/Cargo.toml, exercises/clock/README.md, exercises/clock/example.rs, exercises/clock/tests/clock.rs
I think we found the winner of the most test cases.   Test Driven Drudgery.
Is there a not equal assert?   I changed to assert!( 1 != 2 ).
Thought about using Add trait for adding int to Clock as minutes add, but thought it would get too confusing.  I figured the Display trait was enough.   Thoughts?
=> clock: Add exercise

exercises/custom-set/tests/custom-set.rs, exercises/rna-transcription/tests/rna-transcription.rs, exercises/robot-name/tests/robot-name.rs
This gives a better error message when the assertion is violated.
This was added in August 2016, after each of the changed tests were
added.
=> use assert_ne!(a, b) instead of assert!(a != b)

exercises/beer-song/src/lib.rs, exercises/bob/src/lib.rs, exercises/difference-of-squares/src/lib.rs, exercises/leap/src/lib.rs, exercises/proverb/src/lib.rs, exercises/raindrops/src/lib.rs, exercises/sum-of-multiples/src/lib.rs
Add stubs to leap, raindrops, bob, beer song, proverb difference of squares and sum of multiples.
=> Add stubs to some exercises

exercises/bowling/example.rs, exercises/grade-school/example.rs
Let me know if my understanding of the situation is incorrect and/or I gave an incorrect explanation.
=> grade-school, bowling: Remove unnecessary `mut`

README.md
Two places with !!!!!
README.md for each exercise is currently checked in.  Should this not happen?  I know i just did amends on a bunch, because I didn't have the correct source (even though it is generated later).
Last section, I'm not sure what goes on with /bin.   Easiest solution it to not include this at first.
=> First pass at Main README.md - Issue #278

exercises/bob/tests/bob.rs, exercises/crypto-square/tests/crypto-square.rs, exercises/say/tests/say.rs
After creating a script to count tests/ignore amounts, this is a fix for the incorrect exercises.
#352
=> Fixed inaccurate test/ignores.

exercises/sum-of-multiples/README.md
Basically what the title says. I stumbled across the duplicated sentence while doing the exercises.
=> sum-of-multiples: Removed a duplicated sentence in README

exercises/all-your-base/tests/all-your-base.rs, exercises/alphametics/tests/alphametics.rs, exercises/bowling/tests/bowling.rs, exercises/circular-buffer/tests/circular-buffer.rs, exercises/hamming/tests/hamming.rs, exercises/largest-series-product/tests/largest-series-product.rs, exercises/nucleotide-count/tests/nucleotide-count.rs, exercises/ocr-numbers/tests/ocr-numbers.rs, exercises/pascals-triangle/tests/pascals-triangle.rs, exercises/protein-translation/tests/proteins.rs, exercises/react/tests/react.rs, exercises/variable-length-quantity/tests/variable-length-quantity.rs, exercises/wordy/tests/wordy.rs
Resolves #338 
Test assertions should compare `Option` or `Result` values directly instead of unwrapping them.
=> Changes test assertions to compare wrapped values

.travis.yml, _test/count-ignores.sh
I don't like having to compare the number of tests and ignores manually,
so this script helps with that.
Closes #352.
=> count ignores

config.json, exercises/binary-search/.meta/hints.md, exercises/binary-search/Cargo.lock, exercises/binary-search/Cargo.toml, exercises/binary-search/README.md, exercises/binary-search/example.rs, exercises/binary-search/tests/binary-search.rs
I have added the binary-search exercise based on https://github.com/exercism/problem-specifications/tree/master/exercises/binary-search.
Additionally I have added 2 bonus tasks, so the students can practice the traits  Ord and AsRef if they feel adventurous.
=> Added exercise binary-search

.travis.yml, _test/check-exercises.sh, _test/ensure-lib-src-rs-exist.sh
The reasons to do this:
1. Easier to run (and thus test) it separately
2. Previous scheme wasn't propagating the exit codes correctly. the
`exitcode` is a new variable local to the subshell (as I understand),
so a missing stub file would not actually cause an exit code of 1.
=> travis: Move lib/src.rs check to separate script

.travis.yml, README.md, _test/ensure-stubs-compile.sh, exercises/beer-song/src/lib.rs, exercises/bob/src/lib.rs, exercises/collatz-conjecture/src/lib.rs, exercises/decimal/.meta/ALLOWED_TO_NOT_COMPILE, exercises/difference-of-squares/src/lib.rs, exercises/forth/src/lib.rs, exercises/leap/src/lib.rs, exercises/proverb/src/lib.rs, exercises/raindrops/src/lib.rs, exercises/sum-of-multiples/src/lib.rs
travis: Enforce that stubs compile
Adding a stub with an incorrect signature would be confusing to
students. We will prevent that with CI.
Was desired in https://github.com/exercism/rust/pull/339#issuecomment-319645344
Closes https://github.com/exercism/rust/issues/371.
=> travis: Enforce that stubs compile, supporting commit (add unimplemented)

exercises/proverb/example.rs, exercises/proverb/tests/proverb.rs
Closes #379.
- Eliminate the inconsistencies pointed out in #379.
- Add a new test with different vocab to reduce the viability of hard-coded solutions
- Update example implementation to correctly handle the new tests
This should not break existing solutions, because users who have already
completed the exercise won't be prompted to re-try it. It simply makes
the exercise more rational for future users.
=> Standardize proverb tests

config.json, exercises/two-bucket/Cargo.lock, exercises/two-bucket/Cargo.toml, exercises/two-bucket/README.md, exercises/two-bucket/example.rs, exercises/two-bucket/src/lib.rs, exercises/two-bucket/tests/two-bucket.rs
This test is listed in the problem-specifications repo ([1]), but hadn't been
added to the rust track yet. This commit adds the description, test
cases, and a sample solution based on breadth-first search.
[1] https://github.com/exercism/problem-specifications/blob/master/exercises/two-bucket
=> Add two-bucket test

_test/count-ignores.sh
Otherwise, if I run from `_test`, the `dirname` of `.` is `.`, which
means we don't successfully get the repo directory; we just get `_test`
again.
=> count-ignores: Use `..` not `dirname` to get repo directory

exercises/isogram/README.md, exercises/two-bucket/README.md
We forgot to apply https://github.com/exercism/rust/pull/368 to
https://github.com/exercism/rust/pull/378 and
https://github.com/exercism/rust/pull/375.
=> isogram, two-bucket: use second-edition links

exercises/dominoes/Cargo.lock, exercises/dominoes/Cargo.toml
2.0.0 only changes `can_chain` to `expected`; no tests changed. Thus,
the corresponding operation is a no-op.
https://github.com/exercism/problem-specifications/pull/823
=> dominoes: no-op declare compliance with 2.0.0

exercises/isbn-verifier/README.md
We forgot to apply https://github.com/exercism/rust/pull/368 to
https://github.com/exercism/rust/pull/378
Further, it seems this was forgotten in
https://github.com/exercism/rust/pull/382
I honestly have no idea how I managed to miss it.
=> isbn-verifier: Use second-edition links in README

exercises/alphametics/src/lib.rs
Travis fails in general right now, because we have an unused variable in the Alphametics stub. This is causing #381 to fail right now, and possibly others.
This simply removes the unused name from the Alphametics stub. This changes no interfaces or tests; students may rename the variable to anything they prefer. It simply ensures that the `_test/ensure-stubs-compile.sh` test actually passes.
=> Remove unused variable from Alphametics stub

.travis.yml, _test/ensure-readmes-are-updated.sh
Checking readmes takes up non-trivial maintainer time, and is
prone to error. This script adds a check to the CI which ensures
that PRs are only accepted if their README.md files are
present and correct.
The intent and method come from the discussion which begins [here](https://github.com/exercism/rust/pull/354#issuecomment-341902986). 
It begins by isolating the exercises already impacted by the PR,
so that upstream changes to unrelated exercises don't cause undue
difficulty. It then simply ensures that the README.md within
the PR is identical to the one generated by `configlet generate`.
Outputs lists of exercises with missing or incorrect READMEs,
so people for whom CI fails due to this test not passing should
have an easy time understanding what went wrong and how to fix it.
=> Add CI test to ensure that README.md files are present and correct

README.md, _test/check-exercises.sh, bin/test-exercise, exercises/alphametics/.meta/test-in-release-mode
Instead of having to manually enable tests, copy the examples, and
clean up, this script automates all that.
=> Add a utility to assist manually testing an exercise

bin/test-exercise
Closes #395.
Previous implementation simply deleted all lines containing the string
`[ignore]`. This was not desired behavior, because it also deleted
lines which used the attribute inline.
The updated version now removes the string `#[ignore]` and any
trailing whitespace. If the line is blank in consequence, it deletes
the entire line; otherwise it leaves it.
Given test input:
```rust
tests! {
test_classification {
#[ignore] test_1(1, Classification::Deficient);
#[ignore] test_2(2, Classification::Deficient);
#[ignore] test_4(4, Classification::Deficient);
}
}
#[test]
#[ignore]
fn test_me() {
unimplemented!();
}
{
#[test]
#[ignore]
fn test_indented() {
unimplemented!();
}
}
#[test] #[ignore] fn test_full_inline() { unimplemented!() }
{
#[test] #[ignore] fn test_full_inline_indented() { …
```
=> test-exercise: sed now more precisely excises #[ignore]

config.json, exercises/macros/.gitignore, exercises/macros/.meta/description.md, exercises/macros/.meta/metadata.yml, exercises/macros/Cargo.toml, exercises/macros/README.md, exercises/macros/example.rs, exercises/macros/src/lib.rs, exercises/macros/tests/macros.rs
Closes #397.
This exercise requires that students implement a `hashmap!` macro
to simplify creation of hashmap literals. The intent is to gently
introduce macros-by-example by having them implement a macro which
is both simple but useful.
The [maplit crate](https://crates.io/crates/maplit) which inspired
this exercise uses the [MIT license](https://opensource.org/licenses/MIT),
which as far as I can tell permits this derivative use of its code.
Used first edition book link in the readme because second edition's
macros chapter is not yet written.
=> Add macro implementation exercise

exercises/diffie-hellman/tests/diffie-hellman.rs
Closes #404.
Removes the unused variable from the test.
=> diffie-hellmann: remove unused variable from test

exercises/rna-transcription/example.rs, exercises/rna-transcription/tests/rna-transcription.rs
Also ran the example code and tests through `rustfmt`
**Reference Issues**
#407
=> rna-transcription: abbreviate to 'rna' and 'dna'

exercises/simple-linked-list/.meta/hints.md, exercises/simple-linked-list/README.md
Closes #413.
I still don't know what the underlying root cause of this error is;
a variety of Markdown renderers have all struggled on the same line,
and each has produced a different output. The one thing all the output
has in common is that it's wrong.
Luckily, we don't need to know what's precisely wrong with this in
order to be able to fix it. This version should be much easier to
render consistently and correctly.
=> simple-linked-list: fix hints.md

exercises/bob/Cargo.toml, exercises/bob/README.md, exercises/bob/example.rs, exercises/bob/tests/bob.rs
Closes https://github.com/exercism/problem-specifications/issues/943.
It was possible for a message directed to Bob to be both a question and
yelling, which meant it was unclear which rule should take effect.
Resolve ambiguity by simply adding a rule for that case.
https://github.com/exercism/problem-specifications/pull/1025
=> bob 1.1.0: Add yelling question rule

exercises/atbash-cipher/example.rs, exercises/crypto-square/example.rs, exercises/etl/example.rs, exercises/forth/example.rs, exercises/pangram/example.rs
remove `use std::ascii::AsciiExt` for rust 1.23
In rust 1.23, the `AsciiExt` methods are implemented directly on the
concerned types, so attempting to import `AsciiExt` results in an
unused import.
Rust language PR:
https://github.com/rust-lang/rust/pull/44042
PSA:
https://users.rust-lang.org/t/psa-dealing-with-warning-unused-import-std-ascii-asciiext-in-today-s-nightly/13726
This started warning as an unused import on nightly sometime between
2017-11-02 and 2017-11-09:
https://travis-ci.org/exercism/rust/builds/296391447
https://travis-ci.org/exercism/rust/builds/299770403
This started warning on beta exactly when 1.23.0 became Beta (it was
accepted on 1.22.0):
https://travis-ci.org/exercism/rust/builds/303139434
https://travis-ci.org/exercism/rust/builds/306431846
As 1.23 is now stable …
=> remove `use std::ascii::AsciiExt` for Rust 1.23

exercises/scrabble-score/tests/scrabble-score.rs
Resolves #264.
Implements both of @dexterlemmer's proposals from that issue.
=> scrabble-score: improve non-english letter tests

exercises/isbn-verifier/README.md, exercises/protein-translation/README.md, exercises/reverse-string/README.md, exercises/rna-transcription/.meta/hints.md, exercises/rna-transcription/README.md, exercises/rna-transcription/example.rs, exercises/rna-transcription/tests/rna-transcription.rs
PR to address issue #423.
The tests are re-ordered because it is natural to test validation before `to_rna` using the changed data structures.
=> rna-transcription: Make DNA and RNA validate input on creation.

exercises/robot-name/Cargo-example.toml
Closes #431
Exercise has no library stubs which require the rand crate, so
dependency is removed. Students should learn to use crates.io
to search for dependencies such as this on their own.
=> robot-name: Move rand dependency to Cargo-example.toml

exercises/reverse-string/src/lib.rs
Basically as-titled. It took me an embarrassing amount of time to figure out how to reference the `_` in the current function template (i.e. change it to something else). I've really enjoyed the Rust track so far, just trying to help clarify what I found confusing. 😄 
I tried to make the minimum number of changes here and ensured that `_test/check-exercises.sh` was able to validate the reverse-string exercise before submitting.
=> reverse-string: Update function template to use a variable name instead of an underscore

exercises/nth-prime/example.rs, exercises/nth-prime/src/lib.rs, exercises/nth-prime/tests/nth-prime.rs
I found it a bit confusing when I pulled down this exercise and didn't have a template for the function. Ended up pulling the function name and type out of the `tests/nth-prime.rs` file but I think having this in place would help myself and others.
One alternate approach would be to use a return type of `Result<usize, &'a str>` to allow `Err("Some message")` values.
The full function definition would then be:
```
pub fn nth<'a>(n: usize) -> Result<usize, &'a str> {
unimplemented!()
}
```
I wasn't sure if this was better, worse or of no consequence since it introduces the `'a` lifetime annotations as well.
I tried to make the minimum number of changes here and ensured that `_test/check-exercises.sh` was able to validate the nth-prime exercise before submitting.
=> nth-prime: Provide a function template

config.json, exercises/collatz-conjecture/example.rs, exercises/collatz-conjecture/src/lib.rs, exercises/collatz-conjecture/tests/collatz-conjecture.rs
**Preface**: I'd like to open this PR as a discussion of when we should use Option vs Result. The result of this discussion might also be applicable to perfect-numbers.
---
Since there is only one kind of error that can occur (a non-positive
number), no extra information is given by the `str`, and I do not like
to encourage using `str` as an error type.
I examined a user poll of when to use Result vs Option:
https://www.reddit.com/r/rust/comments/2j0k21/rust_option_vs_result/
One user says to use Option when there is only one failure mode, which
supports the approach taken in this commit.
However, in contrast, there are others who say Result is for any case
when you need to explain the failure. It is possible that we may want to
explain the failure even if there is only one way for a …
=> collatz-conjecture: Use Option<T> instead of Result<T, str>

exercises/perfect-numbers/example.rs, exercises/perfect-numbers/src/lib.rs, exercises/perfect-numbers/tests/perfect-numbers.rs
Since there is only one kind of error that can occur (a non-positive
number), no extra information is given by the `str`, and I do not like
to encourage using `str` as an error type.
I examined a user poll of when to use Result vs Option:
https://www.reddit.com/r/rust/comments/2j0k21/rust_option_vs_result/
One user says to use Option when there is only one failure mode, which
supports the approach taken in this commit.
Same operation as that performed for collatz-conjecture in
https://github.com/exercism/rust/pull/441
=> perfect-numbers: Use Option<T> instead of Result<T, str>

_test/check-exercises.sh
Otherwise, Travis may assume we're hung if we don't produce output in
10+ minutes. Normally we don't think checking all exercises takes this
long, but this prepares for the future and prevents spurious failures in
instances when outside circumstances cause slowness.
This approach was suggested in response to such a failure in
https://github.com/exercism/rust/pull/435#issuecomment-368254549
=> check-exercises: Output progress dot when DENYWARNINGS

_test/check-exercises.sh
Notice that below `test-exercise` there is a check of `$?`. This means
nothing should come after `text-exercise`.
If we fail to do this, warnings will never cause the build to fail (as
we would like them to), because the `$?` is examining the exit code of
`echo`.
We need to move the `echo` (progress dot) that we added in
https://github.com/exercism/rust/pull/446
https://github.com/exercism/rust/pull/446/commits/a3a7b16c0715d03be93e942ef55ec136917ff3b5
=> check-exercises: Move `echo` before `test-exercise`

exercises/gigasecond/.meta/hints.md, exercises/gigasecond/README.md, exercises/gigasecond/example.rs, exercises/gigasecond/src/lib.rs, exercises/gigasecond/tests/gigasecond.rs
This updates the dependencies for the gigasecond exercise to conform to the [usage guidelines](https://docs.rs/chrono/0.4.0/chrono/#usage) for the [chrono](https://docs.rs/chrono/0.4.0/chrono) cargo package:
> Avoid using use chrono::*; as Chrono exports several modules other than types. If you prefer the glob imports, use the following instead:
I realize using `chrono::*` might have been an intentional decision to avoid having to expose beginners to importing `time::Duration` as well, but I think it probably makes more sense to mirror a real environment closely when exposing people to these exercises.
I tried to make the minimum number of changes here and ensured that `_test/check-exercises.sh` was able to validate the gigasecond exercise before submitting.
=> gigasecond: Update dependency to conform to usage guidelines

exercises/variable-length-quantity/example.rs, exercises/variable-length-quantity/src/lib.rs, exercises/variable-length-quantity/tests/variable-length-quantity.rs
We prefer domain-specific errors to strings because they are
programmatically inspectable. We would prefer to encourage students to
use domain-specific errors rather than strings.
As discussed in #444:
https://github.com/exercism/rust/issues/444
=> variable-length-quantity: Use domain-specific error

exercises/allergies/tests/allergies.rs, exercises/dominoes/example.rs, exercises/dominoes/tests/dominoes.rs, exercises/grade-school/tests/grade-school.rs, exercises/poker/tests/poker.rs, exercises/react/tests/react.rs, exercises/rectangles/example.rs, exercises/rectangles/tests/rectangles.rs, exercises/simple-linked-list/tests/simple-linked-list.rs, exercises/sum-of-multiples/tests/sum-of-multiples.rs, exercises/word-count/tests/word-count.rs
I believe this covers the following Clippy lints:
1. writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices.
* Where this was encountered, the signatures were changed from `Vec<T>` to `&[T]` in one commit; the resulting code compiles. Then a second commit was additionally made to change uses of `vec!` into slices, which is not necessitated by the first commit by the commit but is enabled by it.
2. this argument is passed by value, but not consumed in the function body
* Where this was encountered, the signatures were changed from `Vec<T>` to `&[T]` and the usages were changed from `vec!` to slices in one commit, since both changes need to happen together for the tests to compile.
3. useless use of `vec!`
* Where this was encountered, …
=> Use &[T] instead of &Vec<T> where possible

exercises/pig-latin/README.md
Resolves #453:
I updated the README for the pig-latin exercise to correspond to the template in [`problem-specifications`](https://github.com/exercism/problem-specifications).
The update was discussed in the `problem-specifications` repo [here](https://github.com/exercism/problem-specifications/pull/1171).
=> Updated pig-latin README

exercises/alphametics/src/lib.rs, exercises/book-store/src/lib.rs, exercises/crypto-square/src/lib.rs, exercises/decimal/src/lib.rs, exercises/poker/src/lib.rs
Resolves #442 
Changed the parameter to `input`, and uses it in `unimplemented!()` to silence the unused variable warning.
Some of the exercises reported in the issue used `_` as a prefix and not as a lone parameter (e.g. in isbn-verifier, `_isbn`).  I wasn't if those were also a problem, so I didn't change them.
Changed exercises:
(reverse-string was already changed)
=> Swaps all `_` only parameters for `input`

exercises/macros/.meta/ALLOWED_TO_NOT_COMPILE
The stub in fact does not compile and has never compiled ever since the
exercise was added in https://github.com/exercism/rust/pull/401.
However, it is intentional that the stub does not compile, so we allow
it not to.
This was not caught by https://github.com/exercism/rust/pull/372 because
of https://github.com/exercism/rust/pull/381 having tricked the Rust
compiler into thinking it had already compiled the stub.
This is required to be able to merge
https://github.com/exercism/rust/pull/483.
=> macros: Allow stub to not compile

_test/ensure-stubs-compile.sh
Since https://github.com/exercism/rust/pull/372 we compile stubs to
ensure they are correct.
We were observed to still be compiling stubs as of
d44df84079a6d26c50b3d3d00c09d0da8f0b3c6f, whose parent is
a471e1854b86227a95bc8ab35c726c939369c484, the evidence being the build
of https://github.com/exercism/rust/pull/388:
https://travis-ci.org/exercism/rust/builds/298485455
We can see that many warnings are emitted from compiling the
stubs.
As of https://travis-ci.org/exercism/rust/builds/299096339 those
warnings disappeared.
Diagnosis: The test-exercise introduced in #381 tricks the compiler by
leaving the file in place, rather than the previous check-exercises
which always worked inside a temporary directory. As a result, when
running `ensure-stubs-compile` (which happens after …
=> ensure-stubs-compile: Ensure compilation: Touch src/lib.rs

config.json, exercises/armstrong-numbers/.gitignore, exercises/armstrong-numbers/Cargo.toml, exercises/armstrong-numbers/README.md, exercises/armstrong-numbers/example.rs, exercises/armstrong-numbers/src/lib.rs, exercises/armstrong-numbers/tests/armstrong-numbers.rs
Currently, it is after `series` and before `collatz-conjecture`. I'm not 100% sure on the positioning but the exercise is complete
Problem Specification
---
https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers
=> Added armstrong-numbers exercise

config/exercise_readme.go.tmpl
Resolves #414
Removed the link to the rust team page because it didn't work for non-team members.
Left the text "rust team members" but removed the link.
=> Remove link to rust team page

exercises/ocr-numbers/example.rs, exercises/ocr-numbers/src/lib.rs, exercises/ocr-numbers/tests/ocr-numbers.rs
We prefer domain-specific errors to empty tuple because the former are
programmatically inspectable. We would prefer to encourage students to
use domain-specific errors rather than empty tuple.
As discussed in #444.
---
One slight disadvantage is now it appears we have to be opinionated about what information is contained by the errors. The `InvalidRowCount` seems relatively uncontroversial, but one might imagine that the `InvalidColumnCount` could also include which line had an invalid column count. But, careful, that's hard to test because there are multiple lines with invalid column count, so should we accept all of them?
If we wanted to let students change what data the error variants will carry (perhaps they like to provide more information than what the test asks for), I guess we …
=> ocr-numbers: Return domain-specific error

exercises/all-your-base/example.rs, exercises/all-your-base/src/lib.rs, exercises/all-your-base/tests/all-your-base.rs
We prefer domain-specific errors to empty tuple because the former are
programmatically inspectable. We would prefer to encourage students to
use domain-specific errors rather than empty tuple.
As discussed in #444:
https://github.com/exercism/rust/issues/444
=> all-your-base: Return domain-specific error

exercises/react/tests/react.rs
react: Express callback expectations precisely after each `set_value`
**Problem statement**:
Consider a test with two `set_value` calls and which expects that a
callback has, ultimately, been called with the two values, one for each
`set_value`.
The tests currently do not check that one value was added during each
`set_value` call. For all we know, maybe an implementation:
* magically manages to predict the future and calls the callback twice
on the first `set_value` call, with the correct value.
* calls the callback zero times on the first `set_value` call, but twice
on the second `set_value` call.
To more precisely define the `set_value` expectations, this commit uses
a `Cell`-based implementation to test callbacks.
---
**Discussion**:
Is this clearer to students than the old …
=> react: Express callback expectations precisely after each `set_value`

exercises/largest-series-product/example.rs, exercises/largest-series-product/src/lib.rs, exercises/largest-series-product/tests/largest-series-product.rs
To encourage students to be specific about error information.
Since specific errors were just added, stub is provided to help get
student running.
We decided that stubs are a good idea in
#269
We decided that domain-specific errors are a good idea in
#444
=>  largest-series-product: Expect specific errors; add stub

exercises/custom-set/example.rs, exercises/custom-set/tests/custom-set.rs
The current tests of CustomSet pass in an owned Vec to `CustomSet::new`.
This actually seems to make sense, as it allows a FromIterator approach
and avoids cloning.
Note that this doesn't obviate the need for the T to be Clone, because
unions will surely require cloning.
The alternative approach expressed by this PR is to state that `new`
will not consume the input, instead cloning its elements.
The example had to be reworked to make this work, so this affects the
interface students are expected to adhere to.
I (the author of this commit) am no longer sure this is a good idea, so
let's have some discussion on it.
=> custom-set: Use `&[...]` instead of `vec![...]`

exercises/react/example.rs, exercises/react/src/lib.rs, exercises/react/tests/react.rs
Closes #462.
Details are in individual commit messages.
I have no particular preference on whether the five commits comprising this PR should be squashed.
=> react: return domain-specific errors

exercises/crypto-square/example.rs, exercises/crypto-square/tests/crypto-square.rs
The initial implementation of this exercise diverged from the
README: it stripped out the extra padding spaces specified, and
it eliminated all non-alphabetical characters instead of just
getting rid of punctuation.
This commit rectifies both of those diversions. This closes #458.
However, in doing so it uses a method only introduced in Rust 1.24;
only those people who are relatively recent in their Rust compilers
will be able to compile the example.
As the example is not primarily for students, this should be acceptable.
=> crypto-square: Bring exercise implementation in line with README

exercises/circular-buffer/tests/circular-buffer.rs
This PR removes the compiler directive. Instead, all otherwise unused
`Result`s are now `unwrap()`'d.
Closes #475.
=> circular buffer: remove allow(unused_must_use)

exercises/all-your-base/src/lib.rs, exercises/grade-school/src/lib.rs, exercises/ocr-numbers/src/lib.rs, exercises/react/src/lib.rs, exercises/robot-simulator/src/lib.rs, exercises/space-age/src/lib.rs
Closes #481.
Note that in the case of the react exercise, it wasn't possible to follow the standard procedure of adding a use of the variables in the unimplemented block. This is because react uses the generic types `F` and `T`, which are not bounded by the `Debug` trait. In that case, I fell back to the underscore-prefix pattern; students who reach a level 10 exercise should not be confused by it.
=> Remove #[allow(unused_variables)]

exercises/armstrong-numbers/src/lib.rs
This discrepancy was discovered by the following useful command:
```shell
xrust$ rg 'fn .*\b_' exercises/ -trust
```
=> armstrong-numbers: remove leading underscore from variable in stub

_test/ensure-stubs-compile.sh
Strictly speaking this should have been done ever since #483, but it
wasn't necessary then because touching a file doesn't impose any costs.
But if we were to impose additional work on ensure-stubs-compile, then
we would actually want to do this. This commit paves the way for future
additions to this script.
=> ensure-stubs-compile: continue early if allowed not to compile

_test/ensure-stubs-compile.sh, exercises/prime-factors/src/lib.rs
We'd eventually like to deny all warnings from the stubs themselves as
well, but this is a good intermediate state.
Immediate motivation is avoiding an overflowing literal, but I imagine
there are other unforeseen benefits as well.
Note that this required backing up and restoring the tests directory,
since we are editing it.
Closes #461 
Note for reviewers: This PR contains a commit that re-breaks the stub, to validate that this check in fact prevents such stubs. I'd like to see the CI fail with that commit, then that commit reverted, then the CI pass. The entire thing should be squashed when merging so that the net change is only to ensure-stubs-compile.
=>  ensure-stubs-compile: Deny warnings in tests

_test/check-stubs.sh, exercises/beer-song/src/lib.rs, exercises/bob/src/lib.rs, exercises/collatz-conjecture/src/lib.rs, exercises/difference-of-squares/src/lib.rs, exercises/forth/src/lib.rs, exercises/grains/src/lib.rs, exercises/leap/src/lib.rs, exercises/pascals-triangle/src/lib.rs, exercises/perfect-numbers/src/lib.rs, exercises/proverb/src/lib.rs, exercises/raindrops/src/lib.rs, exercises/saddle-points/src/lib.rs, exercises/simple-linked-list/src/lib.rs, exercises/sum-of-multiples/src/lib.rs, exercises/two-bucket/src/lib.rs, exercises/variable-length-quantity/src/lib.rs
Closes #484 
Includes `_test/check-stubs.sh`, which discovers any compilation errors in the stubs.
Eliminates all stub warnings, not just unused variables.
simple-linked-list uses generics which are not bounded by `Debug`, so we can't use the standard "print it in `unimplemented!()` trick there. We fall back on underscore-prefixing affected variables in this case.
=> Eliminate stub warnings

.travis.yml
We never took action on nightly failing, and we prefer to get results
faster and not use up as many of the organisation-wide five build slots.
Closes https://github.com/exercism/rust/issues/498
---
I don't really consider this high-priority to merge, simply because we only really care about doing fewer builds when there are many PRs in flight so many PRs have to get through Travis CI. In normal circumstances... I guess we don't care?
But I guess I offer the PR so that we have it.
It'd be really interesting if these builds still happen but as a low-priority thing, so that they only happen if we have spare Travis CI slots, but I don't think this capability is offered right now.
=> travis: No longer run nightly builds

exercises/react/example.rs, exercises/react/src/lib.rs, exercises/react/tests/react.rs
Closes https://github.com/exercism/rust/issues/473
~~I strongly advise that this should not be merged yet, for at least the following reason:~~
`set_cell_value` now can only fail in one way (cell does not exist) since it is no longer possible to designate an input cell to it. Therefore, it no longer needs to return `SetValueError`. We can just return a boolean, even.
Except for that point, I guess everything else is how I expect it to be.
I'm also happy to hear ideas about being able to move `set_value` onto input cells directory, in which case I don't see the need for this PR.
=> react: Distinguish cell IDs

exercises/armstrong-numbers/README.md
Fixed in https://github.com/exercism/problem-specifications/pull/1237/commits/c2e0b3defcc600fe16d73f2ad4b4cad30e313dbe. This brings the change into the rust repo.
---
Edit by @coriolinus:
Fixes #526
This annotation in the first comment in the discussion will automatically close that issue when this is applied.
=> Fix typo in problem specification

exercises/diamond/example.rs
This rustc release has deprecated the `AsciiExt` trait.
It turns out that the diamond exercise used that trait, and
therefore no longer compiles under DENYWARNINGS=1.
This removes its use of the deprecated trait.
=> Fix rustc 1.26 warnings

exercises/reverse-string/.meta/hints.md, exercises/reverse-string/Cargo.toml, exercises/reverse-string/README.md, exercises/reverse-string/tests/reverse-string.rs
The Readme talks about a bonus test case with grapheme clusters, but it
wasn't in the test suite.
Looking through the submitted solutions, very few of them attempted
reversing on grapheme clusters.
This might encourage more people to attempt it.
=> Add a bonus test in reverse string

config.json, exercises/twofer/.gitignore, exercises/twofer/Cargo.toml, exercises/twofer/README.md, exercises/twofer/example.rs, exercises/twofer/src/lib.rs, exercises/twofer/tests/two-fer.rs
Hello, i created my first exercise and would really appreciate your feedback.
=> Twofer exercise

exercises/hamming/example.rs, exercises/hamming/src/lib.rs, exercises/hamming/tests/hamming.rs
This is effectively a difference of two sizes, so we should return `usize`
=> hamming: Update return type

exercises/gigasecond/tests/gigasecond.rs
Since README for language track mentions that `rustfmt` should be applied for Rust sources.
=> gigaseconds: RustFmt-ed tests source file

config.json
Contributes to https://github.com/exercism/rust/issues/543
=> Add topics to those exercises missing them

exercises/acronym/tests/acronym.rs
This will add a test with an empty string as input to the acronym exercise.
=> acronym: Add test for empty string

exercises/diffie-hellman/.meta/hints.md, exercises/diffie-hellman/README.md, exercises/diffie-hellman/example.rs, exercises/diffie-hellman/tests/diffie-hellman.rs
Mainly to prevent using `a as u32` solution, since it yields false results when a is larger then u32::MAX
=> diffie-hellman: Added big numbers tests

exercises/nucleotide-count/example.rs, exercises/nucleotide-count/src/lib.rs, exercises/nucleotide-count/tests/nucleotide-count.rs
Contributes to #551.
I guess it also closes #512, since no further comments were made about rewriting  returned `Result` or using `Option` / `panic!`
=> nucleotide-count: Added template to stub file

exercises/isbn-verifier/tests/isbn-verifier.rs
Added two tests: one with special characters and one with long digit string. 
The motivation behind these tests is that it is possible to write a solution, that simply filters input string and counts the sum without checking the input string length, and still pass all the tests(for example `test_invalid_isbn_too_long` test, that contains valid isbn and only one extra `X` that could be filtered)
=> isbn-verifier: Added tests for long string and special characters

exercises/rna-transcription/src/lib.rs
The error type in the `new` method is chosen from the example
=> rna-transcription: Added template to stub file

exercises/accumulate/.meta/ALLOWED_TO_NOT_COMPILE, exercises/accumulate/src/lib.rs
I really doubt that the template is needed here, since the point of the exercise is to teach students about closures and how to pass them as function arguments and fully implementing the functions reduces learning.
If this is the case, then perhaps something like this would suffice:
```rust
/*
/// What should _function type be?
pub fn map_function(input: Vec<i32>, _function: ???) -> Vec<i32> {
unimplemented!("Transform input vector {:?} using passed function", input);
}
/// What should _closure type be? 
pub fn map_closure(input: Vec<i32>, _closure: ???) -> Vec<i32> {
unimplemented!("Transform input vector {:?} using passed closure", input);
}
*/
```
Or without multi-line comments and `ALLOWED_TO_NOT_COMPILE`?
=> accumulate: Added template to stub file

exercises/binary-search/.meta/hints.md, exercises/binary-search/Cargo.toml, exercises/binary-search/README.md, exercises/binary-search/tests/binary-search.rs, exercises/triangle/.meta/hints.md, exercises/triangle/Cargo.toml, exercises/triangle/README.md, exercises/triangle/example.rs, exercises/triangle/tests/triangle.rs
Currently, Travis always fails. This is my fault: I edited the [`_test/count-ignores.sh`](https://github.com/exercism/rust/blob/master/_test/count-ignores.sh) script to identify `#[ignore]` and `#[test]` attributes which appear anywhere on a line, not just at its beginning. This identified two exercises which had commented-out tests, which were not ignored: binary-search and triangle.
It would have been possible to revert to the old behavior, but that was also demonstrably wrong, incorrectly failing #577. Instead, I've added `#[ignore]` flags to the appropriate tests, uncommented them, and put them behind a feature gate, as we've done before for the reverse-string exercise. 
Travis does not currently check that feature-gated tests pass, but in case we add that capability in the future, …
=> Fix ignore counts

exercises/grep/README.md
Basically applies #578 for the `grep` exercise.
It seems like `bob` was also updated from the latest `problem-specification`.
It is a minor change, so maybe it is OK to leave it in this PR?
=> grep: Fixed typo in the README

exercises/wordy/example.rs, exercises/wordy/src/lib.rs, exercises/wordy/tests/wordy.rs
Contributes to the #551 
The returned type of the `WordProblem::answer` function is `Result<i32, String>`, but perhaps `Option<i32>` is more suited here?
=> wordy: Added template to the stub file

exercises/custom-set/src/lib.rs
=> custom-set: Added template to the stub file

exercises/parallel-letter-frequency/src/lib.rs
Was not sure about `worker_count` type:  on one hand it is a variable that hold the count of something, so
`i32` is natural here, on the other hand this variable would be used to chunk the input data in separate parts, therefore a lot of casts like `as usize`.
=> parallel-letter-frequency: Added template to the stub file

docs/LEARNING.md
Update `The Rust Programming Language` link to point to 2018-edition.
> The 2018 edition of the book is a "living version" of the book; based on the second edition, it will be updated as Rust updates. If you're not sure what version of the book to read, you should prefer this version. [(Source)](https://doc.rust-lang.org/book/)
=> Update "The Rust Book" links to 2018-edition.

exercises/bracket-push/.meta/hints.md, exercises/bracket-push/README.md, exercises/bracket-push/example.rs, exercises/bracket-push/src/lib.rs, exercises/bracket-push/tests/bracket-push.rs
I'm just going to quote Peter Tillemans' post from the slack channel. He put it very nicely.
>Peter Tillemans [11 août à 23 h 35]
Regarding the Brackets exercise, the way the challenge is made, the student is forced to use an object-like interface where you have to initialise the 'object' before calling a method on it. This 'object' ends usually up with either the result of the brackets balance or the input text or some intermediate value of the data transformation pipeline. This challenge lends itself well to a purely functional solution. I also feel it pushes students to use stateful solutions where none are warranted. (Actually @mawis pointed this out originally).
The hint in the Readme points students towards using lifetimes, but most just accept the `impl From<&'a str> for Brackets` …
=> brackets: simplify required interface

exercises/accumulate/.meta/hints.md, exercises/accumulate/README.md, exercises/accumulate/example.rs, exercises/accumulate/src/lib.rs, exercises/accumulate/tests/accumulate.rs
The distinction between fn pointers and closures is unusal and unnecessary. The common solution with generics works for both anyway.
Furthermore, it was evident from the old examples that this was never about
function pointers (`fn(i32) -> i32`) like the hint claimed, but about trait objects (`&Fn(i32) ->
i32`). Those also implement the `Fn` trait and therefore they, too, work with the generic version.
Edit: I just thought of, maybe I should also change the input and output type. With equal types everything can be done in place which I think takes away from the exercise, it's just iteration, function calling and mutation. A general accumulate has to convert between types which forces creation of a new `Vec`. If the input type is not `Copy`, this also ties into move semantics and …
=> accumulate: make exercise more idiomatic

exercises/circular-buffer/src/lib.rs
Contributes to the #551 
It is unclear what `write` method should return on success, so the return type is `Result<(), Error>`.
Perhaps `()` could be replaced with `usize` as to indicate the index of the successful write?
=> circular-buffer: Added template to the stub file

exercises/leap/tests/leap.rs
The exercise has just 5 test cases. This can easily let some bugs slip through.
This adds a check for a range of years (1600 to 1699) and a few additional centuries. The range is kept short so the user isn't spammed with a huge list of incorrect years with wrong code. It also avoids having the full solution in the tests where students could stumble upon it.
I got this faulty code from a student which passes all the old tests:  
```rust
year % 4 == 0 && !year % 100 == 0 || year % 400 == 0
```
=> leap: add more test cases

exercises/clock/tests/clock.rs
This test helped me find a bug in my solution, specifically where I did the modulo operation.
I had this:
```rust
fn mod_n(a: i32, n: i32) -> i32 {
if n <= 0 {
panic!("Tried mod with negative base: {:?}", n);
}
if a > 0 {
a % n
}
else {
a % n + n
}
}
```
And it should've been this:
```rust
fn mod_n(a: i32, n: i32) -> i32 {
if n <= 0 {
panic!("Tried mod with negative base: {:?}", n);
}
if a >= 0 {
a % n
}
else {
a % n + n
}
}
```
"0 hours" was treated like a negative amount, but the solution still passed all the tests. Anyway, I hope this helps, and lemme know if I should change something!
=> clock: Add test case for comparing 24:00 and 00:00

.travis.yml, _test/ensure-lib-src-rs-exist.sh
As discussed in #551 the script in this PR now has a check to ensure that the stub files of the exercises
are not empty.
The reasons why `ensure-lib-src-rs-exist.sh` was chosen for this PR and not `ensure-stubs-compile.sh` are:
- The content of the stub file is not a concern of `ensure-stubs-compile.sh` - it should check if the stub compiles, even if it is empty
- When `ensure-lib-src-rs-exist.sh` checks for the stub and thinks it exists only because the file exists (even though it could be empty) is sort of false-positive
The `[ "$(cat "$dir/src/lib.rs")" == "" ]` line was added for the check, because when `rustfmt` works on an empty file it inserts the `0a` symbol in it, and the `-s` flag check is useless in this case.
In case this PR is merged, closes #551
=> ensure-lib-src-rs-exist: Updated the script to check if the stub file is empty

exercises/clock/Cargo.toml
Closes #642.
I performed a manual comparison of the [test suite][1] and the [canonical data][2],
and determined that the set of tests is identical in each. This PR is therefore
limited to updating the version string to match that of the canonical data.
[1]: https://github.com/exercism/rust/blob/master/exercises/clock/tests/clock.rs
[2]: https://github.com/exercism/problem-specifications/blob/master/exercises/clock/canonical-data.json
=> clock: update test suite to match canonical data

exercises/nth-prime/example.rs, exercises/nth-prime/src/lib.rs, exercises/nth-prime/tests/nth-prime.rs
As there is no longer any case which would return `None`, this also
imples returning a simple `u32` instead of an `Option<u32>`. Removing
the `Option` implied removing the test case testing for `None`.
In the past this may have served as a very gentle introdution to the
`Option` type, but that may have been accidental: it wasn't mentioned
in the "topics" section for this exercise in `config.json`. Therefore
it should be fine to let some other exercise serve as an introduction
to the `Option` type.
Closes #626.
=> nth-prime: use 0-based indexes instead of 1-based

exercises/dot-dsl/example.rs, exercises/dot-dsl/tests/dot-dsl.rs
Closes #640. Doesn't test edges or edge attributes, but hopefully
once students have implemented enough to pass this test, they'll
implement edges properly also.
=> dot-dsl: Add get_node and get_attr methods to required signatures

config.json, exercises/accumulate/.meta/hints.md, exercises/accumulate/README.md, exercises/accumulate/example.rs, exercises/accumulate/tests/accumulate.rs
Implements the test scheme I proposed in #629 which enforces that solutions are generally applicable and minimally restrictive.
Because ignored tests still cause compile failures, I had to comment them out entirely. I've used a multi-line comment so that including more tests can be done by just moving 2 characters. This is similar to how the C++ track organizes their tests and it's also quite fitting here, because it further encourages going through the tests in order.
An alternative would be to add a series of cargo features and conditionally compile the tests but that would be more work for students and a new concept to learn.
=> accumulate: expand tests to require general solutions

exercises/macros/tests/macros.rs
fixes #600
I put a test fn in a new module that doesn't import HashMap, so that if a student uses `HashMap::new()` in the macro, the compiler will throw one and only one compile error.
=> macros: test macro without HashMap in scope

README.md, exercises/crypto-square/README.md, exercises/diamond/example.rs, exercises/dominoes/README.md, exercises/dot-dsl/.meta/ALLOWED_TO_NOT_COMPILE, exercises/grep/.meta/hints.md, exercises/grep/README.md, exercises/luhn-trait/.meta/metadata.yml, exercises/luhn-trait/README.md, exercises/nucleotide-codons/tests/codons.rs, exercises/ocr-numbers/tests/ocr-numbers.rs, exercises/react/example.rs, exercises/rectangles/tests/rectangles.rs, exercises/rna-transcription/example.rs, exercises/say/tests/say.rs, exercises/simple-cipher/README.md, exercises/triangle/.meta/hints.md, exercises/triangle/README.md, exercises/variable-length-quantity/example.rs
Noticed another typo while doing the exercises so I ran a spell check.
=> fix misspellings

exercises/pig-latin/example.rs, exercises/pig-latin/tests/pig-latin.rs
There was no test for
```
**Rule 4**: If a word contains a "y" after a consonant cluster or as the
second letter if a two letter word it makes a vowel sound (e.g. "rhythm"
-> "ythmrhay", "my" -> "ymay").
```
=> Add test for pig latin rule 4

exercises/macros/tests/macros.rs
=> macro: suppress unused_variable warning in test

exercises/pythagorean-triplet/README.md
Added missing constraint to the Pythagorean triplet problem that is outlined in the linked Project Euler problem.
=> Update Pythagorean triplet README.md with missing constraint

exercises/say/tests/say.rs
The test_max_u64 testcase was not actually testing u64::max_value()
but instead was testing i64::max_value(), for clarity fixed the testcase
to use the correct value.
Works with implementation from https://github.com/lutostag/exercism/tree/master/rust/say
=> say: fix testcase

README.md
It seems like a common scenario for the new contributors to submit a PR that modifies the README of the exercise, with the section that came from the `problem-specifications` repository being modified directly in the `README.md` file. After that a maintainer have to ask the contributor to submit a PR on the `problem-specifications` repository, before changes on this repository could be merged.
With the new README section in this PR, I hope that the above workflow could be improved for all parties involved.
=> README: Added a section about modifying exercises' README

_test/ensure-stubs-compile.sh
A follow-up for #688, that targets another time-consuming Travis script - `_test/ensure-stubs-compile.sh`
=> ensure-stubs-compile: Rewritten the script to target only modified exercises

exercises/paasio/tests/paasio.rs
The tests don't use it. The description in the readme doesn't make it a
requirement.
As such, I think it's better removed.
The alternative would be to write a test, or modify an existing test so
that it is used. If others are less keen on this being removed, I'll do
that.
=> paasio: Add ReadStats.get_ref test

_test/ensure-stubs-compile.sh
Since it is a track policy to not have empty stub files, the check is no longer needed
=>  ensure-stubs-compile: Removed the redundant empty stub check

_test/ensure-lib-src-rs-exist.sh
The original message suggests that it is OK to have an empty stub file, which contradicts the current track policy.
=> ensure-lib-src-rs-exist: Rephrased the missing stub file message

exercises/gigasecond/.meta/hints.md, exercises/gigasecond/README.md
When I used https://docs.rs/chrono/0.4.0/chrono/, the paragraph under
Duration has 3 dead links. Suggest changing this link to
https://crates.io/crates/chrono where the links under the Duration
section work.
=> gigasecond:change chrono crate link

docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md
These are used in the following:
https://exercism.io/tracks/rust/installation
https://exercism.io/tracks/rust/learning
https://exercism.io/tracks/rust/resources
There is a nice page header on those pages that say "Installing Rust",
"Learning Rust", and "Useful Rust Resources" respectively.
Particularly useful because the previous header of RESOURCES was
"Recommended Learning Resources" which is against the purpose of
RESOURCES as stated in:
https://github.com/exercism/docs/blob/master/language-tracks/documentation/for-consumers.md#file-structure
https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md#improve-product-facing-copydocumentation
=> docs: rm headings from INSTALLATION, LEARNING, and RESOURCES

config.json, exercises/pythagorean-triplet/Cargo.toml, exercises/pythagorean-triplet/example.rs, exercises/pythagorean-triplet/src/lib.rs, exercises/pythagorean-triplet/tests/pythagorean-triplet.rs
Updates the ` pythagorean-triplet` according to the latest canonical-data.
The canonical-data introduced the `sum` input parameter, therefore the stub template is updated alongside with the test suite and the example solution.
Closes #712
=>  pythagorean-triplet: Updated the test suite to the version 1.0.0

exercises/accumulate/.meta/hints.md, exercises/accumulate/README.md
Correct the links to `FnMut` and `FnOnce` to be their documentation
pages rather than the generic `Fn` documentation page.
=> accumulate: correct README function links

util/exercise/src/lib.rs
Must have been left from the original PR, that added the crate.
=> exercise crate: Removed the redundant 'which rustfmt' Command invoke

exercises/crypto-square/example.rs, exercises/decimal/example.rs, exercises/pascals-triangle/example.rs, exercises/poker/example.rs, exercises/queen-attack/example.rs, exercises/rectangles/example.rs, exercises/robot-simulator/example.rs, exercises/roman-numerals/example.rs, exercises/triangle/example.rs, exercises/two-bucket/example.rs
Appears that this has been available since Rust 1.17:
https://rust-lang-nursery.github.io/edition-guide/rust-2018/data-types/field-init-shorthand.html
Although I didn't check, surely it's the case that many examples were
written before Rust 1.17 so they didn't get a chance to take advantage.
Since we are long past Rust 1.17, let's take the chance now.
Clippy suggested:
warning: redundant field names in struct initialization
https://travis-ci.org/exercism/rust/builds/456356560
for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#redundant_field_names
=> clippy: Use field init shorthand

exercises/saddle-points/tests/saddle-points.rs
Some test cases could still reject results if the order was different
than expected. These are now using the helper function
find_sorted_saddle_points.
=> saddle-points: Ignore order of results

exercises/pythagorean-triplet/example.rs
Not student-facing, prioritise accordingly lower as necessary.
It's possible to get some improvements in pythagorean-triplet performance, which I have found helpful when testing locally.
Two commits are included, with each successive commit going farther down the "more performant but harder to understand" path. Reviewers should decide which point on the path is an appropriate point for Travis and locally running.
(Though I've implicitly made my position clear by having submitted this PR)
=> pythagorean-triplet example performance

exercises/proverb/example.rs, exercises/proverb/src/lib.rs, exercises/proverb/tests/proverb.rs
Clippy suggested
https://travis-ci.org/exercism/rust/builds/456432005
warning: this argument is passed by value, but not consumed in the function body
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#needless_pass_by_value
This gets its own PR simply because there's a student-facing change, though it is not terribly interesting. So I also don't really find this urgent. I originally thought there would be more student-facing changes, but I suppose that's unlikely if the files I was looking at were all the example solutions.
=> proverb: Use `&[T]` instead of `Vec<T>`

util/exercise/Cargo.lock, util/exercise/Cargo.toml, util/exercise/src/cmd/configure.rs
This PR adds the handling of the `null` field, read both from `config.json` and user input, by the `configure` subcommand.
Closes #719
=> exercise crate: Made configure subcommand handle null 'unlocked_by' field

exercises/circular-buffer/Cargo.toml, exercises/circular-buffer/tests/circular-buffer.rs
The tests are the same as the initial unversioned version of canonical-data:
https://github.com/exercism/problem-specifications/pull/488
This is because all subsequent changes did not change test content:
1.0.0 (formatting change only):
https://github.com/exercism/problem-specifications/pull/681
1.0.1 (clarify overwrite):
https://github.com/exercism/problem-specifications/pull/892
1.1.0 (move inputs to `input` object):
https://github.com/exercism/problem-specifications/pull/1186
The Rust track already had most of the tests; these mostly add some
clarity around `clear` and addds a test for an `overwrite` following a
`read`.
=> circular-buffer 1.1.0

exercises/proverb/Cargo.toml
Actually, the canonical data was born from the Rust implementation.
https://github.com/exercism/problem-specifications/pull/994
1.1.0 moves inputs to the `input` object.
https://github.com/exercism/problem-specifications/pull/1157
The Rust track has all the canonical tests, although in a different
order. Reviewers should indicate whether an ordering change in the Rust
tests is desired.
=> proverb: no-op declare compliance with 1.1.0

exercises/clock/Cargo.toml, exercises/clock/tests/clock.rs
I ran into a solution that would give the wrong solution if the minutes were exactly a multiple of 60 and negative.
=> clock: Add test for exactly -60 minutes.

util/exercise/Cargo.lock, util/exercise/Cargo.toml, util/exercise/src/cmd/update.rs
Adds a check for the `property` field during the traversal of the `canonical-data` for cases, which only have subcases, but no actual cases (for instance `grep` exercise)
=> exercise crate: Added a check for a property during a recursive exercise update

exercises/two-bucket/Cargo.toml, exercises/two-bucket/tests/two-bucket.rs
Note that two-bucket was added to the Rust track at
https://github.com/exercism/rust/pull/375
At the time it declared 1.0.0 compliance, but was actually compliant
with 1.2.0 already!
Further updates to 1.3.0 and 1.4.0 require no action on the Rust track's
part.
1.0.1: Fix exercise name
https://github.com/exercism/problem-specifications/pull/715
Unversioned(!): Change descriptions
https://github.com/exercism/problem-specifications/pull/716
(Our descriptions are no better or worse, so might as well keep them)
1.1.0: Add cases where goal equals one bucket's capacity
https://github.com/exercism/problem-specifications/pull/763
Rust already had these cases, so just update the descriptions
1.2.0: Fix a test case added in 1.1.0
https://github.com/exercism/problem-specifications/issues/911 …
=> two-bucket: declare compliance with 1.4.0 by changing descriptions

exercises/binary-search/Cargo.toml, exercises/binary-search/tests/binary-search.rs
this test can catch a solution that explicitly checks for an empty array
but fails to check if the bounds cross
https://github.com/exercism/problem-specifications/pull/1399
=> binary-search 1.3.0: test for when left and right bounds cross

exercises/pythagorean-triplet/README.md
This is as described in https://github.com/exercism/problem-specifications/pull/1395
The current README will really confuse non math-savvy students, as it asked to find `a*b*c`, while the tests actually check for the triplets.
Change it to asks for the triplet explicitly. Give the answer for N = 1000 as it's also spoiled in the test file ;)
=> Fix pythagorean-triplet readme, in accordance to the updated tests

exercises/gigasecond/README.md
This helps address my comments in
https://github.com/exercism/rust/pull/710#issuecomment-438078198
=> gigasecond:add clarity to exercise goal

exercises/leap/Cargo.toml, exercises/leap/example.rs, exercises/leap/src/lib.rs, exercises/leap/tests/leap.rs
This PR syncs the `leap` exercise with the `problem-specifications` repo.
It introduces the following changes:
- Adds all the cases from canonical data. The cases that were present in the suite were not present in the canonical version, so I added new cases in a `test_description_in_lowercase` format. The old cases were not touched (except the one that checked the 1996 year - it was present in canonical data, so I replaced it with the formatted case). Perhaps some old test cases could be deleted?
- Replaced `i32` argument type with `u64` - no negative years are expected, so I thought it would make sense
Relevent PR: https://github.com/exercism/problem-specifications/pull/1359
=>  leap: Updated exercise to 1.4.0 version

exercises/bob/Cargo.toml, exercises/bob/tests/bob.rs
Relevant PRs:
- https://github.com/exercism/problem-specifications/pull/1282
- https://github.com/exercism/problem-specifications/pull/1293
- https://github.com/exercism/problem-specifications/pull/1319
Appart from the new tests, some old tests were renamed / got their input
value modified.
=> bob: Updated the exercise to the 1.4.0 version

exercises/hamming/Cargo.toml, exercises/hamming/README.md, exercises/hamming/src/lib.rs, exercises/hamming/tests/hamming.rs
Relevant PRs:
- https://github.com/exercism/problem-specifications/issues/625
- https://github.com/exercism/problem-specifications/pull/844
- https://github.com/exercism/problem-specifications/pull/845
- https://github.com/exercism/problem-specifications/pull/875
- https://github.com/exercism/problem-specifications/pull/953
- https://github.com/exercism/problem-specifications/pull/1129
- https://github.com/exercism/problem-specifications/pull/1389
Basically adds every test case from the current canonical-data.json  without deleting the old ones.
=>  hamming: Updated the exercise to the 2.1.1 version

exercises/nucleotide-count/Cargo.toml, exercises/nucleotide-count/tests/nucleotide-count.rs
Relevant PRs:
- https://github.com/exercism/problem-specifications/pull/666
- https://github.com/exercism/problem-specifications/pull/951
- https://github.com/exercism/problem-specifications/pull/957
- https://github.com/exercism/problem-specifications/pull/1126
Basically renamed the old test cases and the process function.
=> nucleotide-count: Updated the exercise to the 1.3.0 version

exercises/wordy/Cargo.toml, exercises/wordy/tests/wordy.rs
In keeping with [1.3.0][], we want to test that this fails in an
expected way rather than an unexpected way.
[1.3.0]: https://github.com/exercism/problem-specifications/pull/1383
Specifically for Rust, we want to make sure that this results in `None`
rather than accessing an out-of-bounds index due to always assuming that
the inputs will have at least three space-separated elements (of the
form "What is X...?").
https://github.com/exercism/problem-specifications/pull/1401
=> wordy 1.5.0: Test question `What is?` with no operands or operators

config.json
Addresses https://github.com/exercism/exercism/issues/4536
Arbitrarily chose 25 as the char limit; renamed all topics over that len
=> Shorten topics

exercises/hexadecimal/src/lib.rs, exercises/nucleotide-codons/src/lib.rs
Needed because https://github.com/exercism/rust/pull/707, and the track
has a policy to not have empty stub files.
hexadecimal: Copied from the example.
nucleotide-codons: Copied from protein-translation.
Since the build on master is broken without this, I regret to inform
that this will be merged as soon as Travis CI passes, but post-merge
review is of course welcome.
=> hexadecimal, nucleotide-codons: Add stubs indicating deprecation

exercises/leap/README.md
Leap-year functions don't generally occur in standard libraries.
Is there a single example of a language we have that does this?
If there is one, then that would be the right way to solve this exercise
in that language. Presumably this exercise is primarily placed at the
top of core tracks. We should not encourage to re-implement standard
library functions at that point. But this is a hypothetical argument.
https://github.com/exercism/problem-specifications/pull/1418
=> leap: Remove recommendation to DIY in description

exercises/forth/example.rs
Prep for https://github.com/exercism/rust/pull/769 .
Blocking https://github.com/exercism/rust/pull/769 and all other otherwise-active maintainers declared inactivity, so I'm merging when tests pass.
=> forth: Prepare for 2018 by not using `Term` and using `?` not `try!`

docs/INSTALLATION.md
After the 2018 Edition the Rust site has been redesigned with the "Install Rust" link removed.
To avoid confusion this PR includes a direct link to the installation instructions.
=> INSTALLATION.md: Replaced the Rust homepage link with the direct link to the installation instructions

exercises/hello-world/GETTING_STARTED.md
Trying out rust for the first time noted that this link was wrong. 
We site at that link says: 
>Installation
>The 2018 edition of the book is no longer distributed with Rust's documentation.
>If you came here via a link or web search, you may want to check out the current version of the book instead.
>If you have an internet connection, you can find a copy distributed with Rust 1.30.
=> Fix link to installation section of the rust book.

exercises/parallel-letter-frequency/tests/parallel-letter-frequency.rs
Clippy suggestion
https://travis-ci.org/exercism/rust/builds/456496870
warning: Constants have by default a `'static` lifetime
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#const_static_lifetime
=> parallel-letter-frequency: remove static lifetime

exercises/hamming/Cargo.toml, exercises/hamming/tests/hamming.rs
Relevant PR:
- https://github.com/exercism/problem-specifications/pull/1412
Apart from adopting the latest canonical-data, I also tried to regroup the test cases, so there would be some logic in their placement
=> hamming: Updated the exercise to the 2.2.0 version

exercises/saddle-points/.meta/hints.md, exercises/saddle-points/README.md
In reference to my issue #787 this is proposed notice in the exercise description about inefficiency of _vector of vectors_ and cache locality aspect.
Update to `README.md` seem to pick up some changes from master exercise repository.
I'm open to any suggestions about wording.
=> saddle-points: Added efficiency notice about vector of vectors

README.md, util/exercise/Cargo.lock, util/exercise/Cargo.toml
This PR removes the dependency on the `openssl` by disabling the default feature of the `reqwest` and `git2` crates. This frees the users of the crate from configuring the opensll library on their systems.
The `default-tls` feature of the `reqwest` was replaced with the `rustls-tsl` feature. Apart from removing dependency on the `openssl` this reduced the number of the compiling crates by 4, thus saving some compilation time.
The disabling of the default features of the `git2` crate introduced additional crates to compile, but the crate is only used to find the `bin` directory in the repository. The `exercise` crate already has this functionality, which means that `git2` crate could be removed in the future.
=> exercise crate: Removed the dependency on the openssl

exercises/macros/.meta/description.md, exercises/macros/README.md
Thanks for this exercise!
The old link went to a 404 page. I believe this is the correct link — it's the link to the macros chapter of the current book. The old link looked like it was pointing at the appending of a previous version of the book; I think that the macro info must have been promoted to its own chapter in the new book.
=> Update link to macros chapter in Rust book

exercises/paasio/tests/paasio.rs
The error becomes visible when README.md (which is read during the test) has odd number of bytes.
This situation occured with last README.md update 5f23d6af5a2fa3898cd46e2d3c85b5c72d355f6e
=> passio: test fix when reading odd number of bytes

exercises/clock/src/lib.rs
There is no need to consume the original value of Clock, when making a new Clock via the `add_minutes` method.
=> clock: Modified the add_minutes stub function to take self by reference

config.json
In the process of reworking the Rust track through the [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project), this promotes the side exercise "Reverse String" to be our first core exercise after "Hello World". This is due to it being a "Level 1" exercise, which means that it covers only basic datatypes and only one basic principle. This is still a work in progress and not the final track :)
=> Promoted "Reverse String" to be the first core exercise after "Hello World"

config.json
In the process of reworking the Rust track through the [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project), this promotes the side exercise "Gigasecond" to be a core exercise after "Reverse String". This is due to it being a "Level 1" exercise, which means that it covers only basic datatypes and principles. This is still a work in progress and not the final track :)
=> Promoted "Gigasecond" to be a core exercise.

config.json
After the recent pull requests for Round 2 of the Track Anatomy Project, the mentoring queue looks much more manageable. However, there's still an overwhelming number of students waiting for mentoring, and waiting times can be long. There are 3 bottlenecks in the current progression: Bracket Push, Saddle Points, and Pythagorean Triplet. Together they are responsible for 250 students being blocked. As a mentor, I feel overwhelmed by this amount, and we suspect that the amount scares away other (potential) mentors as well.
To solve this we decided to take an extreme measure: turn the 3 bottleneck exercises into side exercises. The only goal is to get the mentor queue in good shape. It doesn't say anything about if any of these exercises should or should not be a core exercise. Any of them …
=> Temporarily demoted "Bracket Push", "Saddle Points", and "Pythagorean Triplet" to side exercises.

config.json
This pull request is part of the [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project). For more on the background there, please see [issue #809](https://github.com/exercism/rust/issues/809) opened by @kytrinyx.
This remedies [issue #4779](https://github.com/exercism/exercism/issues/4779) and logically places the two side exercise, "Luhn From" and "Luhn Trait", to be unlocked by the core exercise, "Luhn".
Your feedback on the technical aspects of this pull request are very welcome here. For questions or discussions about the track anatomy project we have opened [issue #809](https://github.com/exercism/rust/issues/809).
=> Changed "Luhn From" And "Luhn Trait" To Be Unlocked By "Luhn".

exercises/rna-transcription/.meta/hints.md, exercises/rna-transcription/README.md, exercises/rna-transcription/example.rs, exercises/rna-transcription/src/lib.rs, exercises/rna-transcription/tests/rna-transcription.rs
`clippy::wrong_self_convention` is being violated at present.
=>  rna-transcription: rename method to_rna() to into_rna(), fixes clippy::wrong_self_convention

exercises/tournament/tests/tournament.rs
Call this one a little pedantic, but as soon as I opened this test file I couldn't bear to look at the expected outputs without lining up the headers properly. Just thought I'd save other obsessive people like myself the hassle in future! ;)
=> tournament: line up the expected table header with the rest of the table

exercises/ocr-numbers/tests/ocr-numbers.rs
Clippy warning
https://travis-ci.org/exercism/rust/builds/456496870
warning: `cfg_attr` is deprecated for rustfmt and got replaced by tool_attributes
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/#deprecated_cfg_attr
=> ocr-numbers: change `cfg_attr(rustfmt, rustfmt_skip)` to `rustfmt::skip`

exercises/dot-dsl/tests/dot-dsl.rs
Suggested by clippy:
https://travis-ci.org/exercism/rust/builds/517554492
warning: an inclusive range would be more readable
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#range_plus_one
Note that this `&attributes[i..=i]` is saying "one-element slice (the
ith element of `attributes`)". An equivalent construction would be
`&[attributes[i]]`. The latter would copy `attributes[i]`, so we'll
avoid by continuing to slice.
---
I ask reviewers to pay careful attention to the factual accuracy of the last paragraph and also judge whether this is a desirable thing to continue to do, as opposed to the alternative construction presented.
=> dot-dsl: Use zip instead of enumerate + map-with-indexing

exercises/tournament/tests/tournament.rs
When getting the tests to pass one by one, the final test is to sort teams by
score and then fallback to alphabetical by team name when scores match. Since
the earlier draw test also results in two teams with one score, it kinda ruins
the flow by requiring solution to be sorting by team name already.
---
Also interestingly enough, in my case I chose to sort the items unstably (for speeeeed), which meant that the test would intermittently alternate between passing and failing. I'm almost torn about fixing this edge-case because while it might vex some people, it could also lead many of them to learning that `unstable_sort` deliberately randomizes the tiebreaker, which could send them down all sorts of interesting rabbit holes ;)
=> tournament: rework the 'a_draw_is_one_point_each' test to handle any ordering

exercises/nth-prime/.meta/hints.md, exercises/nth-prime/README.md, exercises/nth-prime/tests/nth-prime.rs
In the exercise description 13 is 6th number while in tests it's 5th, I changed it to be consistent with python version
=> nth-prime: tests do not match problem specifications

config.json
The rust track had several deprecated exercises. As they were removed
from the list of exercises available to students some time ago,
https://github.com/exercism/rust/pull/773 removed the actual exercises,
in order to clean things up. This produced a CI failure, but it was
overridden, because it was a configlet bug, not a real problem.
Overriding the CI failure was a mistake: I hadn't considered that
this would cause _every_ CI job to fail from that point forward.
I opened https://github.com/exercism/configlet/pull/160 fixing the
issue with configlet, but it has not yet been reviewed, and there
will be an unknowable amount of time before it is reviewed and
approved. In order to make configlet stop complaining and restore
CI functionality to the track, this PR moves the removed exercises …
=> Forego formerly deprecated exercises

exercises/wordy/.meta/hints.md, exercises/wordy/Cargo.toml, exercises/wordy/README.md, exercises/wordy/example.rs, exercises/wordy/tests/wordy.rs
The wordy Readme has the following:
> ## Bonus — Exponentials
> 
> If you'd like, handle exponentials.
> 
> > What is 2 raised to the 5th power?
> 
> 32
I've added tests for this, hidden behind the `exponentials` feature flag
=> Wordy: test for bonus condition

exercises/accumulate/tests/accumulate.rs, exercises/clock/tests/clock.rs, exercises/custom-set/tests/custom-set.rs, exercises/decimal/tests/decimal.rs, exercises/dot-dsl/tests/dot-dsl.rs, exercises/hexadecimal/tests/hexadecimal.rs, exercises/luhn-from/tests/luhn-from.rs, exercises/luhn-trait/tests/luhn-trait.rs, exercises/macros/tests/macros.rs, exercises/nucleotide-codons/tests/codons.rs, exercises/two-fer/Cargo.toml, exercises/two-fer/tests/two-fer.rs
Some `extern crate` lines were left in the exercise test suites after the `2018 edition` migration.
This PR removes them.
=> exercises: Removed the 'extern crate' from the test suites

exercises/luhn-trait/.meta/description.md, exercises/luhn-trait/README.md
Closes https://github.com/exercism/rust/issues/845. Attn @bartmassey. 
Removes idiomaticity note which had become stale.
=> luhn trait: remove obsolete documentation

exercises/rail-fence-cipher/tests/rail-fence-cipher.rs
Closes https://github.com/exercism/rust/issues/842. Attn @bartmassey.
Eliminate spaces from wide character test, which resolves ambiguity about whether spaces must be filtered.
=> rail fence cipher: remove spaces from wide char test

exercises/triangle/tests/triangle.rs
Currently, if all sides are zero, the triangle is deemed invalid. But if any side is zero, that is also an invalid triangle.
=> triangle: added tests for only one side being zero

exercises/reverse-string/.meta/hints.md, exercises/reverse-string/README.md
I thought the exercise was unmaintained since the necessary iterator to handle graphemes was removed in rust 1.3 (and google got me straight to that information;-), but a human mentor said it is intended for users to hunt for a crate.
So add some pointer to crates.io and how to use external crates to the hints section of this exercise. This is the first real exercise, so do not expect users to know about crates.io yet and provide the link on how to use crates that the auto-mentor provides straight up in the hints.
=> Reverse string hint

exercises/doubly-linked-list/tests/doubly-linked-list.rs
I've been watching submissions of the new exercise and the very first one (from an independent mode user) uses a node struct like this:
```rust
struct Link<T> {
value : T,
next : Option<Box<Link::<T>>>,
prev : *mut Link::<T>,
}
```
with no separate `Drop` implementation. This is a bad idea because `Box` recursively calls the drop of its contained type. That causes 2 function calls per element in the list, leading to a stackoverflow on large lists.
This PR adds a test provoking exactly that.
=> doubly-linked-list: test drops of large lists

exercises/parallel-letter-frequency/.meta/hints.md, exercises/parallel-letter-frequency/README.md
Parallel-letter-frequency has a link in its Readme to read about
concurrency in Rust. Unfortunately it used to link to a splash page
saying it wasn't the current version of the book. I've changed it to
point to the current version of the book.
=> Parallel-letter-frequency: correct link

.travis.yml, _test/check-uuids.sh, config.json
Want to prevent any invalid UUIDs from being entered.
Want to put this in configlet lint, but can't:
exercism/configlet#99
exercism/configlet#168
So it will go in individual tracks' .travis.yml for now.
It appears that the site will accept pretty much arbitrary strings as
UUIDs for now, but we want to make less work for ourselves when valid
UUIDs are required.
=> travis: reject invalid UUIDs

exercises/simple-linked-list/tests/simple-linked-list.rs
This PR aims to close #834, making sure that the `peek` method always references the head element and doesn't remove it (like `pop`).
=> simple-linked-list: test_peek_returns_head_element tests head element

exercises/macros/tests/macros.rs
I was mystified that replacing `$(...),*` with `$(...),+` in my macro rule seemed to work fine.
=> Add test for single macro argument

exercises/react/tests/react.rs
RemoveCallbackError::NonexistentCell was not tested yet, add new test.
Fixes #465
=> react: Test removing callback from nonexistent cell

exercises/two-bucket/example.rs, exercises/two-bucket/src/lib.rs, exercises/two-bucket/tests/two-bucket.rs
The student solution would need to employ one of several strategies:
* (If searching the state space) Notice that there are no further states
to be visited, and yet the solution has not been reached.
* Notice that the goal is not divisible by the GCD of the bucket sizes,
therefore can be rejected immediately.
In case the student assumes that all non-coprime bucket counts will
invalidate the goal, a counterexample to that is given as well (buckets
not coprime but goal is still possible).
There are ten implementing tracks:
bash csharp fsharp go java javascript python ruby rust typescript
Of these tracks, only two of them (Bash, Go) currently test the
condition where it is not possible to reach the goal.
Having this test serves as a reminder that it remains wise to handle the
situation where …
=> two-bucket: test inability to reach the goal

exercises/leap/tests/leap.rs
Having observed basic solutions on other Rust exercises ignoring the fact that years might not necessarily only be four digit, bys adding tests for years in the past might assist the aspiring Rust programmer.
=> leap: More test cases for years in the past (less than four digits)

exercises/paasio/README.md
See how it is currently listed as Paasio:
http://exercism.io/tracks/rust/exercises/paasio
Given that the exercise is about input/output statistics for a
platform-as-a-service, "PaaS I/O" seems a better way than the default.
https://github.com/exercism/problem-specifications/pull/1589
=> paasio: Title as "PaaS I/O" instead of default Paasio

config.json
This used to be `println` which actually occures nowhere in the excercise.
Change this to:
* `strings` - because the function returns a string and we compare strings
* `test_driven_development` - as this is the first excercise and people learn the red, green flow.
Both topics are taken from https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt
This also addresses #529 for `hello world`.
=> hello world: make topics match the content

exercises/pig-latin/Cargo-example.toml
Otherwise, ONCE_INIT deprecated in ~~Ruby~~Rust 1.38.0.
https://travis-ci.org/exercism/rust/jobs/590089919
Need 1.4.0 with this commit:
https://github.com/rust-lang-nursery/lazy-static.rs/commit/1dbd5ae6ccb33c1f88fe521c9ab1f8f0e4cf5193
=> pig-latin example: Use lazy_static 1.4.0

exercises/bowling/tests/bowling.rs
I am the culprit; In ffc10d5fd7c35c1387da70b27cfe41981bc1b25e, authored
by me, the double semicolons were introduced. I am sorry.
As you can see on Travis CI, they are a warning in upcoming 1.39.0.
https://travis-ci.org/exercism/rust/builds/590089916
=> bowling: Replace double semicolons with single

exercises/triangle/tests/triangle.rs
For completeness' sake, and just in case someone comes up with a crazy solution that would pass everything else but break at this point, I've added a pair of tests for invalid triangles to the bonus floating-point section.
=> triangle: Add invalid floating-point tests

exercises/custom-set/src/lib.rs
=> custom-set: remove Debug trait bound from stub

exercises/beer-song/example.rs, exercises/beer-song/src/lib.rs
Why not to use more appropriate data type for the given excercise? There are no negative numbers of beer bottles.
If it's not merged, *I owe you `-1` beer!* :wink:
=> Beer Song: use u32 instead of i32

util/exercise/Cargo.lock
This slightly improves compilation time, as the total number of \
dependencies is reduced.
=> exercise tool: update dependencies

README.md
The issues tab is fairly well-known, but the track status board is both more obscure and more useful for potential contributors looking for a way to helpfully contribute which doesn't require too much effort.
=> add links to readme describing where new contributors can find pending issues

exercises/leap/Cargo.toml, exercises/leap/tests/leap.rs
See https://raw.githubusercontent.com/exercism/problem-specifications/master/exercises/leap/canonical-data.json
for the current canonical data.
=> leap: update to canonical data v1.6.0

config.json
There were quite a few topics that were string related
and not listed in the [topics list](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt).
* Replace all of them with `strings` which is in the list.
* Add `parsing` if the topic was `string_parsing`.
=> topics: standardize `strings` topic

exercises/armstrong-numbers/Cargo.toml, exercises/armstrong-numbers/tests/armstrong-numbers.rs
See https://github.com/exercism/problem-specifications/blob/master/exercises/armstrong-numbers/canonical-data.json for the current canonical data.
=> armstrong-numbers: update to canonical data v1.1.0

exercises/reverse-string/Cargo.toml, exercises/reverse-string/tests/reverse-string.rs
Relevant PRs:
- 1.1.0 -> 1.2.0: exercism/problem-specifications#1519
See https://raw.githubusercontent.com/exercism/problem-specifications/master/exercises/reverse-string/canonical-data.json for the current canonical data.
=> reverse-string: update to canonical data v1.2.0

exercises/acronym/Cargo.toml, exercises/acronym/example.rs, exercises/acronym/tests/acronym.rs
Acronym 1.7.0 has several new test cases and removed a couple of others.
Of particular note is the new `apostrophes()` test case, which broke the
original example implementation.
=> acronym: Update to 1.7.0

exercises/gigasecond/Cargo.toml
Version 2.0.0 modifies the name of the input variable, which has no bearing on the tests.
Relevant PRs:
- 1.1.0 -> 2.0.0: exercism/problem-specifications#1405
See https://raw.githubusercontent.com/exercism/problem-specifications/master/exercises/gigasecond/canonical-data.json for the current canonical data.
While this update does not require any change to the tests, there is some divergence between the tests' names and those from the specs. I'm a bit on the fence about whether it would be better to update the names as well while we're at it.
=> gigasecond: update to canonical data v2.0.0

exercises/atbash-cipher/tests/atbash-cipher.rs
Now atbash-cipher exercise use `assert_eq!(expected, actual)` format for tests. 
I think it's better to reverse the order, since this format is more natural and is used by most Rust projects I've seen so far.
Also, tests in other exercises use `assert_eq!(actual, expected)` format, so it would improve consistency.
=> Reformat tests in atbash-cipher exersice

exercises/saddle-points/.meta/hints.md, exercises/saddle-points/README.md
Closes #791 
Of the 5 choices in that issue, results of the discussion were (effectively):
"Do not do 2."
"Do 2 or 3 to be consistent with Rust."
"Do 3 for now since it is easy, then 1 later."
"1 would be possible using a little more code."
As option 2 effectively has a negative vote, and 3 has two votes for, modifying hints.md comes out as the maintainer-preferred solution. This PR implements that and regenerates the README appropriately. Or rather, READMEs. While doing so, I discovered two other READMEs were dated and their latest version was more readable, so I included them in this PR.
=> Clarify Rust indices from 0 in saddle-points and regenerate READMEs

exercises/minesweeper/README.md, exercises/robot-name/README.md
Based on discussion in #900. I was going to originally add more to this PR but then, after reading closer, I saw there was not, in fact, any significant change in the problem specifications on the test or other levels that required improvement! So, this will do.
EDIT: whoops, reread recommendations, revised commit descs slightly, but should be good now?
=> Regenerate READMEs for minesweeper, robot name

exercises/atbash-cipher/Cargo.toml, exercises/atbash-cipher/tests/atbash-cipher.rs
Version 1.2.0 adds two tests: "decode with too many spaces" and "decode with no spaces".
Relevant PRs:
- 1.1.0 -> 1.2.0: exercism/problem-specifications#1277
Of possible relevance is exercism/problem-specifications#529, which removed the "encode ignores non ascii" test from the specs, but that test is still present in the Rust track tests. I feel it would be best to remove it, as it doesn't really add much for this particular exercise (compared to, say, "reverse-string"), but I thought I'd check others' opinion first.
=> atbash-cipher: update to canonical data v1.2.0

exercises/clock/.meta/hints.md, exercises/clock/README.md
That suggestion was meant to get students to explore the available
type-conversion traits, not as a serious command that students
have to implement it. This PR makes the hypotheticality of the
suggestion more explicit.
=> clock: deemphasize suggestion to implement From<Clock> for String

exercises/space-age/Cargo.toml, exercises/space-age/tests/space-age.rs
Version 1.2.0 modifies the input values so that the number of seconds fits into an `i32`. The expected values are updated to reflect the change.
Relevant PRs:
- 1.1.0 -> 1.2.0: exercism/problem-specifications#1441
=> space-age: update to canonical data v1.2.0

exercises/luhn/Cargo.toml, exercises/luhn/tests/luhn.rs
Relevant PRs:
- https://github.com/exercism/problem-specifications/pull/1420
- https://github.com/exercism/problem-specifications/pull/1480
- https://github.com/exercism/problem-specifications/pull/1500
- https://github.com/exercism/problem-specifications/pull/1523
=> luhn: Updated the exercise to the version 1.6.1

config.json
This continues the progress of #529 
Rebased on 2019-11-18T06:43Z
This unifies the various config.json topics for format, plurality, conciseness, and to explicitly identify "type theory" ideas using terms that are familiar to people who discuss them (and thus, searchable in meta-language discussion, as opposed to just in Rust... thus `option_type` and `result_type` instead of just option or result or plural forms of same.
=> Unify config.json topics

exercises/saddle-points/example.rs
Optimizations:
- row maximum is calculated once per row, not once per matrix element
- no `Vec` allocations for column minimums, using iterators is sufficient
---
Commit also shows some Rust "tricks":
- assign several variables in one `let` statement
- `match` on several items
- use logical or `|` in `match` arms conditions
---
What do you think of the suggested changes?
=> Optimize saddle-points; show some Rust "tricks"

docs/RESOURCES.md
The discord link was pointing to the game Rust.
=> Changed discord link to official rust language discord server

util/exercise/src/cmd/templates/macros.rs, util/exercise/src/cmd/templates/test_file.rs, util/exercise/src/cmd/templates/test_fn.rs
Follow-up to #908 . Sadly, since macros and included templates do not share the global context of the caller, we can't devolve the logic to the callees. But at least we can make the intent clearer by renaming the variable (thanks to @coriolinus for the suggestion!).
I also removed some indentation in the template (comments and properties) when it had no impact on readability. I'm a bit more hesitant to do so within the loops.
=> exercise-util: rename "dont_ignore" to "first_test_case" in templates

bin/fetch-configlet
Looks like Github has recently started returning non-uppercased
HTTP headers, at least some of the time. This broke the script,
which looked for a case-sensitive 'Location' header to find the
newest version. We can see this problem in spurious build failures like [this](https://travis-ci.org/exercism/rust/jobs/655967583?utm_medium=notification&utm_source=github_status).
This fixes the script such that it no longer cares whether the initial
L is capital or not, and if it breaks again in the future, it will
give a more informative error.
Request relatively rapid review for this, given that we have an [external PR](https://github.com/exercism/rust/pull/928) which is broken pending this fix.
=> Fix the fetch-configlet script, which broke recently

exercises/circular-buffer/example.rs, exercises/circular-buffer/tests/circular-buffer.rs
Verifies that clear() actually clears the buffer. Resolves #930.
=> Add new test for clear() to 'Circular Buffer'

exercises/macros/.meta/hints.md, exercises/macros/README.md, exercises/macros/tests/invalid/Cargo.toml, exercises/macros/tests/invalid/comma-sep.rs, exercises/macros/tests/invalid/double-commas.rs, exercises/macros/tests/invalid/leading-comma.rs, exercises/macros/tests/invalid/only-arrow.rs, exercises/macros/tests/invalid/only-comma.rs, exercises/macros/tests/invalid/single-argument.rs, exercises/macros/tests/invalid/triple-arguments.rs, exercises/macros/tests/invalid/two-arrows.rs, exercises/macros/tests/macros.rs
- This uses code inspired by buildtry, but this is less flexible.
- These tests contain invalid syntax, and are designed not to compile.
- Student macros should produce an error instead of compile.
- Add note about Rust 1.36 requirement
---
Output of all passing tests like with `example.rs` and this [student's implementation](https://exercism.io/mentor/solutions/80240c6472fd40f4a6ae5924e2bd0f33):
```
running 13 tests
test test::type_not_in_scope ... ok
test test_empty ... ok
test test_single ... ok
test test_no_trailing_comma ... ok
test test_nested ... ok
test test_trailing_comma ... ok
test test_compile_fails_triple_arguments ... ok
test test_compile_fails_two_arrows ... ok
test test_compile_fails_double_commas ... ok
test test_compile_fails_only_arrow ... ok
test …
```
=> macros: Add new tests to check for invalid syntax without trybuild

exercises/diffie-hellman/.meta/hints.md, exercises/diffie-hellman/Cargo-example.toml, exercises/diffie-hellman/Cargo.toml, exercises/diffie-hellman/README.md, exercises/diffie-hellman/example.rs, exercises/diffie-hellman/tests/diffie-hellman.rs
Fixes https://github.com/exercism/rust/issues/936
* Add tests with inputs near the u64 type limits as a solutions may
panic 'multiplication overflow' while passing existing tests
* Fix example code to also pass these tests
=> diffie-hellman: Add test cases for inputs near the type limits

exercises/macros/tests/macros.rs
This test makes sure that students use `::std::collections::HashMap`
instead of just `std::collections::HashMap`. It is intended
to show that a user can override the intended type.
They receive this error if the wrong scoping is used:
```
---- test_type_override stdout ----
thread 'test_type_override' panicked at 'Do not allow users to override which HashMap is used', tests/macros.rs:81:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> macros: Add tests to check for HashMap scoping

exercises/macros/tests/macros.rs
- This is a continuation of #649
- Move the tests above the compilation failure tests.
- Add a line to test with parameters. If students submit a macro
with a specific match for e.g. ` () => {{ ::std::collections::HashMap::new() }};`
but then not include the same for the default case.
=> macros: additional tests without HashMap in scope

exercises/macros/example.rs, exercises/macros/tests/macros.rs
- A recursive solution, including the one in `example.rs` should
use `$crate::` to prefix the recursive macro call. Otherwise,
renaming the module fails.
=> macros: Check recursive solutions use $crate

exercises/matching-brackets/tests/matching-brackets.rs
I Wrote code that passed all of the testcases but it had a bug. If there was any isolated error with mismatched brackets or extra brackets when the stack was empty it would essentially ignore the error.
My code https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1661c960aaf13f061dbeb747a587cece
These testcases could also be push up to the problem description repo.
Should i also open a pull request to the problem description repo?
=> Add testcases to matching brackets

config.json
Per discussion on Slack, Atbash Cipher is a "redundant" exercise in many ways as while the exercise involves string processing, it has many tedious fine details and is not that exciting to implement in Rust. Also learned a bit of `jq`!
If desired, I believe two other changes might be prudent but I wanted to discuss them before I implemented them as I am not sure of their technical details, whether consensus is available, and if they should go in this or another PR.
1. I believe the implementation of Space-Age is considerably simpler than Clock, while they are both similar exercises, and thus they should swap places. They both involve mathematics and `impl` but one is very simple and involves a lot of pregenerated boilerplate to work with. The other involves many stylistic choices, …
=> Remove Atbash Cipher from Rust core

exercises/macros/tests/invalid/Cargo.toml, exercises/macros/tests/invalid/comma-sep.rs, exercises/macros/tests/invalid/double-commas.rs, exercises/macros/tests/invalid/leading-comma.rs, exercises/macros/tests/invalid/only-arrow.rs, exercises/macros/tests/invalid/only-comma.rs, exercises/macros/tests/invalid/single-argument.rs, exercises/macros/tests/macros.rs
- Try to assign to variable, in most cases this is `<_, _>`
- only-arrow and only-comma use `<(), ()>`
- Also enables leading-comma which was accidentally not enabled
=> macros: Assign invalid tests to variable

exercises/macros/tests/macros.rs
- Had a student who had inverted the logic between trailing-comma
and non-trailing comma. This change ensures that it works in both
cases.
- Also added lines between the two similar tests to check for all
three possible inputs.
=> macros: Check for additional scoped syntax

exercises/gigasecond/tests/gigasecond.rs
A student has reported that clippy now complains about this line in tests. Indeed, it's not necessary.
=> gigasecond: Remove no-op import from tests

exercises/macros/tests/macros.rs
- Some students implement the solution in different ways. This
ensures that they prefix the namespace to make sure no one
overrides it.
=> macros: Additional syntax for hashmap override

exercises/protein-translation/tests/proteins.rs
Length which is not divisible by 3 should not make the test panic, but rather
return None.  That is not the case if it happens after a stop codon.
=> protein-translation: Add couple of test to exercise proper decoding

exercises/forth/example.rs, exercises/forth/tests/forth.rs
I've seen solutions to this exercise which test if the first character
or lexeme in an `eval` call is `:`, handle a definition if it is, and
then process the rest of the input as normal operations. I feel like
that shouldn't be allowed; a Forth interpreter should be able to
handle definitions interleaved with operations and sequences of
multiple definitions.
=> forth: Two tests which have definitions not as the first word in an `eval`

exercises/leap/tests/leap.rs
Hello, while looking at the test I saw some case who are not using `process_leapyear_case` function, in this commit I replaced plain `assert_eq` by `process_leapyear_case`.
=> [leap-test] Use process_leapyear_case when possible

exercises/rna-transcription/tests/rna-transcription.rs
`assert!(something().is_err())` is an antipattern in testing because
it hides the particular error, and most of the time that is undesired.
It's better to expect a particular error result. This demonstrates
better error-handling techniques for students.
=> rna-transcription: avoid using assert!(something().is_err())

config.json, exercises/grep/.meta/hints.md, exercises/grep/Cargo-example.toml, exercises/grep/README.md, exercises/grep/example.rs, exercises/grep/src/lib.rs, exercises/grep/tests/grep.rs
The `failure` crate is getting old, and has largely been superseded
in the ecosystem by the `anyhow` crate, which better uses the standard
library (and which only became possible with Rust v1.34). We should
demonstrate more modern techniques to students.
See:
- bytecodealliance/wasmtime#436
- https://blog.yoshuawuyts.com/error-handling-survey/
- https://internals.rust-lang.org/t/failure-crate-maintenance/12087
=> grep: replace failure with anyhow

exercises/book-store/example.rs
At some point, std::mem::replace gained the `#[must_use]` attribute:
if you don't use the previous value, there's no reason not to just
assign to the target directly. This caused a warning to be emitted,
which broke our check that no examples generate warnings.
This PR fixes that.
FWIW, I'm apparently to blame for the original use of mem::replace;
at this remove, I have no idea what I was thinking then.
=> book-store: don't use std::mem::replace unnecessarily

exercises/grains/.meta/tests.toml, exercises/perfect-numbers/README.md
Last week, we sent a PR in which tests.toml file were added for all exercises that have canonical data. Due to an issue, the grains exercise's tests.toml file was not included. This PR adds the tests.toml file for the grains exercise.
=> Add tests.toml file for grains exercise

exercises/leap/tests/leap.rs
```
warning: this import is redundant
--> tests/leap.rs:1:1
|
1 | use leap;
| ^^^^^^^^^ help: remove it entirely
|
= note: `#[warn(clippy::single_component_path_imports)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports
warning: 1 warning emitted
```
=> Clippy says to remove `use leap;` at the beginning

exercises/anagram/.meta/hints.md, exercises/anagram/README.md
We've had several instances, most recently #988, of students opening issues or pull requests addressing the fact that the function signature in the stub of anagram is insufficient for a real implementation in the compiler. This PR should make it more clear that this is an intentional learning point.
=> anagram: add hint that lifetime errors are expected

exercises/anagram/tests/anagram.rs
```
Checking anagram v0.0.0 (/home/rmason/code/exercism/rust/anagram)
warning: this import is redundant
--> tests/anagram.rs:1:1
|
1 | use anagram;
| ^^^^^^^^^^^^ help: remove it entirely
|
= note: `#[warn(clippy::single_component_path_imports)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports
warning: 1 warning emitted
Finished dev [unoptimized + debuginfo] target(s) in 0.41s
```
=> Fix anagram.rs to be in line with clippy

exercises/clock/tests/clock.rs
During my own exercising found an edge case in my code where I handled subtracting 60 minutes but not any of the multiples of 60 minutes, so adding a test hoping it will help others too
=> Add a test to construct clock with negative 120 minutes

exercises/parallel-letter-frequency/tests/parallel-letter-frequency.rs
For cases with identical data, the for loop is not needed
=> [parallel-letter-frequency]: Clippy says to use resize or static creation

README.md
This was supposed to have been done with the move to GitHub Actions:
https://github.com/exercism/rust/pull/975
https://github.com/exercism/rust/issues/974
https://github.com/exercism/rust/issues/982
Better late than never
=> README: Replace Travis CI badge with GHA

exercises/dominoes/tests/dominoes.rs, exercises/saddle-points/tests/saddle-points.rs
clippy:
warning: Use sort_unstable instead of sort
note: `#[warn(clippy::stable_sort_primitive)]` on by default
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#stable_sort_primitive
When sorting primitive values (integers, bools, chars, as well as
arrays, slices, and tuples of such items), it is better to use an
unstable sort than a stable sort.
Using a stable sort consumes more memory and cpu cycles. Because values
which compare equal are identical, preserving their relative order (the
guarantee that a stable sort provides) means nothing, while the extra
costs still apply.
=> dominoes, saddle-points: sort_unstable instead of sort

exercises/grep/tests/grep.rs
clippy:
warning: statics have by default a `'static` lifetime
note: `#[warn(clippy::redundant_static_lifetimes)]` on by default
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_static_lifetimes
=> grep: remove `'static` for statics

exercises/fizzy/tests/fizzy.rs
clippy:
warning: this `.into_iter()` call is equivalent to `.iter()` and will not move the `array`
note: `#[warn(clippy::into_iter_on_ref)]` on by default
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#into_iter_on_ref
Readability. Calling `into_iter` on a reference will not move out its
content into the resulting iterator, which is confusing. It is better
just call `iter` or `iter_mut` directly.
=> fizzy: iter instead of into_iter

.github/workflows/tests.yml, _test/check-configlet-fmt.sh, _test/check-exercise-crate.sh, _test/check-exercises.sh, _test/ensure-stubs-compile.sh, config.json
When moving off of Travis in
https://github.com/exercism/rust/pull/975, there were some instances of
TRAVIS_PULL_REQUEST left over as a transitionary strategy.
Now we have been hurt by leaving TRAVIS_PULL_REQUEST in:
In https://github.com/exercism/rust/pull/1006 a new GitHub Actions job
was added that forgot to set TRAVIS_PULL_REQUEST and caused incorrect
behaviour.
So let's remove TRAVIS_PULL_REQUEST and instead change it to
GITHUB_EVENT_NAME.
Documentation:
https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables
=> replace TRAVIS_PULL_REQUEST with GITHUB_EVENT_NAME

exercises/nucleotide-codons/tests/codons.rs
clippy:
warning: unneeded `return` statement
note: `#[warn(clippy::needless_return)]` on by default
help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
Removing the `return` and semicolon will make the code more rusty.
I understand this exercise is deprecated and that we already did this to
protein-translation in 3d3cd9a524130d6bf38212c39b5134fc7841e16e.
Clippy doesn't know this when we run it against all the exercises, so
might as well just do this to get closer to zero Clippy warnings in
tests (which we are pretty close to)
=> nucleotide-codons: rm unneeded return

.github/workflows/tests.yml
Even if we don't have any activity on master for a while, it is still
valuable to run the CI periodically - this will keep a record of whether
there are any changes caused by new Rust toolchain releases, etc.
All our observed behaviour with our current `push` and `pull_request`
tell us that multiple entries under `on` indicate OR (the workflow runs
on any of these events)
Corroborated by documentation:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#on
Documentation on schedule:
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule
=> GitHub Actions: Also run weekly

_test/ensure-stubs-compile.sh
You used to be able to provide a completely empty stub file. But this
option was removed in ba54bca7f0391480fa6b8bbe2d4c63b959c9d35e.
=> ensure-stubs-compile: rm "remove all non-commented lines"

exercises/diamond/example.rs, exercises/nucleotide-count/example.rs, exercises/pangram/example.rs, exercises/robot-name/example.rs, exercises/roman-numerals/example.rs, exercises/say/example.rs
=> remove unnecessary static lifetimes from exercise examples

exercises/decimal/example.rs, exercises/palindrome-products/example.rs, exercises/perfect-numbers/example.rs
=> rewrite if chains with match in exercise examples

exercises/anagram/example.rs, exercises/grade-school/example.rs, exercises/high-scores/example.rs
=> rewrite sort as sort_unstable where applicable in exercise examples

exercises/minesweeper/example.rs, exercises/simple-cipher/example.rs
=> use byte literals instead of casting char to u8 in exercise examples

exercises/book-store/example.rs
=> prefer slices over borrowed vecs in exercise examples

exercises/react/example.rs, exercises/react/src/lib.rs
=> remove unneeded unit return type in exercise examples

.github/workflows/tests.yml, bin/format_exercises, exercises/acronym/tests/acronym.rs, exercises/all-your-base/example.rs, exercises/bob/tests/bob.rs, exercises/bowling/tests/bowling.rs, exercises/decimal/example.rs, exercises/diamond/tests/diamond.rs, exercises/dot-dsl/example.rs, exercises/forth/example.rs, exercises/forth/tests/forth.rs, exercises/minesweeper/example.rs, exercises/minesweeper/tests/minesweeper.rs, exercises/ocr-numbers/tests/ocr-numbers.rs, exercises/paasio/tests/paasio.rs, exercises/palindrome-products/example.rs, exercises/parallel-letter-frequency/tests/parallel-letter-frequency.rs, exercises/poker/example.rs, exercises/rail-fence-cipher/tests/rail-fence-cipher.rs, exercises/rectangles/example.rs, exercises/rectangles/tests/rectangles.rs, exercises/scale-generator/example.rs, exercises/two-bucket/example.rs, exercises/two-bucket/src/lib.rs, exercises/two-bucket/tests/two-bucket.rs, exercises/wordy/tests/wordy.rs, exercises/xorcism/tests/xorcism.rs
Part of #659 
To be discussed before merging: Is there any chance at all that a contributor may have a version of `rustfmt` that is different from that run by GitHub Actions, and therefore causes hardship on them in complying with `rustfmt`?
=> GitHub Actions: Enforce exercises' formatting; format exercises

exercises/bowling/example.rs, exercises/doubly-linked-list/example.rs, exercises/fizzy/example.rs, exercises/forth/example.rs, exercises/phone-number/example.rs, exercises/poker/example.rs, exercises/rail-fence-cipher/example.rs
```sh
for ex in exercises/*; do
(
cd "$ex"
cp example.rs src/lib.rs
if [ -f Cargo-example.toml ]; then
cp Cargo-example.toml Cargo.toml
fi
cargo +nightly clippy -Z unstable-options --fix --allow-dirty
cp src/lib.rs example.rs
git checkout -- src/lib.rs Cargo.toml
)
done
```
Helps address #1012.
=> apply automatic clippy fixes to examples

exercises/matching-brackets/example.rs
clippy::needless_collect
Instead, check whether element exists in collection during iteration.
Helps address https://github.com/exercism/rust/pull/1012
=> matching-brackets: rm needless collect

exercises/circular-buffer/src/lib.rs, exercises/parallel-letter-frequency/src/lib.rs
clippy::useless_format
https://rust-lang.github.io/rust-clippy/master/index.html#useless_format
Helps address https://github.com/exercism/rust/pull/1011
=> circular-buffer, parallel-letter-frequency: use to_string()

exercises/anagram/tests/anagram.rs, exercises/pythagorean-triplet/tests/pythagorean-triplet.rs
https://rust-lang.github.io/rust-clippy/master/index.html#from_iter_instead_of_collect
Apparently it should be rare to call `from_iter()` directly.
This lint is a fairly recent addition (merged 17 days ago):
https://github.com/rust-lang/rust-clippy/commit/a2bf404d34529e2b916bdc514bd71309e86908bd
Observing that the necessary code change still works on 1.47.0 (note
that 1.48.0 was released very recently), it seems safe to make the
change now.
=> anagram, pythagorean-triplet: use collect() instead of from_iter()

exercises/doubly-linked-list/.meta/description.md, exercises/doubly-linked-list/README.md, exercises/doubly-linked-list/example.rs, exercises/doubly-linked-list/src/lib.rs, exercises/doubly-linked-list/tests/doubly-linked-list.rs, exercises/simple-linked-list/example.rs, exercises/simple-linked-list/src/lib.rs, exercises/simple-linked-list/tests/simple-linked-list.rs
https://rust-lang.github.io/rust-clippy/master/index.html#len_without_is_empty
This alleges that for certain types, len() may be expensive, but
is_empty() is likely to always be cheap, and therefore it's good custom
to have both. I find this sufficiently persuasive. On the principle that
the track instill good habits in students, we will add and test such a
method.
I understand that for the example solutions, len() is actually cheap.
In addition, I understand that for a list it's always possible to be
able to cheaply determine the `len()` simply by keeping an extra field
that gets updated on every insert.
Nevertheless I think it's a good idea anyway.
---
doubly-linked-list: Test len in more places
I simply thought we could increase the thoroughness without being an
undue burden on …
=> simple-linked-list, doubly-linked-list: Add is_empty

exercises/doubly-linked-list/example.rs, exercises/doubly-linked-list/src/lib.rs
It's understandable that clippy says the `next` here conflicts with
Iterator's `next`, but I really think that's the best name for it unless
we go with something like `forward` and `back`.
There is one other example of Cursors on the internet:
https://contain-rs.github.io/linked-list/linked_list/struct.Cursor.html
This one also uses `next`, so it seems they did not find a better
solution to this than we could.
Helps address https://github.com/exercism/rust/pull/1011
Helps address https://github.com/exercism/rust/pull/1012
=> doubly-linked-list: Allow should_implement_trait

_test/ensure-stubs-compile.sh
We don't find it too useful to have students implement Default.
All other warnings in stubs have been dealt with, and we find it useful
to ensure there are no further ones.
I've determined via https://github.com/petertseng/exercism-rust/actions/runs/373860276 that when #1027, #1028, #1029, and this are merged, there are no more Clippy warnings or errors in stubs.
Closes https://github.com/exercism/rust/issues/659
This is appropriate because:
* stubs and tests are now ensured to have no Clippy warnings or errors
* examples are ensured to have no errors, and we're unconcerned about
them having warnings since students don't see them
* rustfmt is enforced
=> ensure-stubs-compile: Deny all warnings except new_without_default

exercises/forth/src/lib.rs
Closes #961: as discussed, this adjusts the return type to `&[Value]` in order to reduce the amount of cloning required and since it is used for tests only, it does not truly break the type's API.
=> Fix #961: Change Forth stack return type to slice

exercises/forth/example.rs
As discussed in #1032, the PR was merged too quickly, so this is to
complete the contribution by updating the exercise's example in order to
be compatible with the modified unit tests.
=> forth: Finish closing #961 - update example

exercises/pangram/example.rs
Same idea as https://github.com/exercism/rust/pull/1027 but for examples
not stubs.
=> pangram: use collect() instead of from_iter()

exercises/phone-number/example.rs, exercises/scale-generator/example.rs
I'm honestly not really convinced by the phone-number one but I guess
it's one fewer mention of number_len so it's fine.
https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains
=> phone-number, scale-generator: use range::contains

config.json, exercises/xorcism/.meta/description.md, exercises/xorcism/.meta/hints.md, exercises/xorcism/README.md, exercises/xorcism/example.rs, exercises/xorcism/src/lib.rs, exercises/xorcism/tests/xorcism.rs
This should implement all of the changes discussed in #1040, barring one. Outside of a comment around `impl Trait` and removing the link to `ExactSizeIterator`, I did not modify the instructions in README.md. I believe with the change in tests to focus on `munge_in_place` first, the user will have sufficient ramp-up experience implementing the simpler exercise before jumping into the more complex one.
=> Changes to Xorcism discussed in #1040

bin/fetch-canonical_data_syncer.sh
This commit alters the `fetch-canonical_data_syncer` script so that it
will stay working after we make changes to the `canonical-data-syncer`
repo.
The plan for those changes is:
1. Rename the existing `canonical-data-syncer` repo to `configlet-v3`.
2. Use that repo to develop `configlet` for Exercism v3. The existing
functionality will be adapted into a `configlet`-style CLI with a
`sync` subcommand.
3. When Exercism v3 is launched, rename the existing `configlet` repo to
`configlet-v2`, and the `configlet-v3` repo to `configlet`.
After step 1, GitHub will redirect `canonical-data-syncer` traffic to
the renamed repo. However, the fetch script was implemented to download
the latest release, and in future the latest release will not be
backwards-compatible with `canonical-data-syncer`: it …
=> fetch-canonical_data_syncer: Download v0.17.0, not latest

exercises/anagram/.meta/hints.md, exercises/anagram/README.md
Many solutions repeatedly change the case of word, and also repeatedly sort it every time it is compared with a possible anagram. Also, often a possible anagram is case-changed for comparing with the case-changed word and then case-changed again for the purposes of sorting. By minimizing the case changes and using sort_unstable the solutions are usually two to three times faster.
Another hint would be to test the lengths of word and the possible anagram before doing any case changes and sorting of the possible anagram, but I left that out as I considered it might be too much detail up front. But that is another performance tip I often find myself making.
=> anagram: Update README.md

exercises/macros/tests/invalid/Cargo.toml, exercises/macros/tests/invalid/comma-sep.rs, exercises/macros/tests/invalid/double-commas.rs, exercises/macros/tests/invalid/leading-comma.rs, exercises/macros/tests/invalid/no-comma.rs, exercises/macros/tests/invalid/only-arrow.rs, exercises/macros/tests/invalid/only-comma.rs, exercises/macros/tests/invalid/single-argument.rs, exercises/macros/tests/invalid/triple-arguments.rs, exercises/macros/tests/invalid/two-arrows.rs, exercises/macros/tests/macros.rs
This solution currently passes all of the tests but is incorrect:
```rust
#[macro_export]
macro_rules! hashmap {
( $($key:expr => $val:expr),* $(,)?) => {
{
use crate::HashMap;
let mut map = HashMap::new();
$(
map.insert($key, $val);
)*
map
}
};
}
```
The macro accepts `hashmap!(,)` but because the solution also uses `crate::HashMap`, the invalid cases all fail to compile due to the import even if they would otherwise succeed. This PR prevents this sort of failure by providing the same imports to the negative cases as to the positive cases.
=> Add HashMap import to invalid test cases for Macros

exercises/macros/tests/invalid/Cargo.toml, exercises/macros/tests/invalid/missing-argument.rs, exercises/macros/tests/macros.rs
Another test to catch an invalid student solution. Thanks to @bobahop for catching it.
```rust
#[macro_export]
macro_rules! hashmap {
( $($key:expr => $val:expr$(,)?),* ) => {{
let mut hash_map = ::std::collections::HashMap::new();
$(
hash_map.insert($key, $val);
)*
hash_map
}};
}
```
=> Add new missing-argument.rs test for Macros

exercises/grade-school/example.rs, exercises/grade-school/src/lib.rs, exercises/grade-school/tests/grade-school.rs
Also update the hint about why `grade` doesn't return a reference.
Fixes CI failures on `master` branch.
=> grade-school: update to fix clippy lints

problem_ordering.md
I ran https://github.com/tbroadley/spellchecker-cli and it said:
```
problem_ordering.md
15:3-15:4  warning  Use `An` before `exercise`, not `A`
```
I am trying this to see if I can contribute to the repository.
=> grammar fix

concepts/option/about.md, concepts/option/introduction.md, concepts/option/links.json
> Purpose: Provide information about the concept for a student who has completed the corresponding concept exercise to learn from and refer back to.
[introduction.md purpose](https://github.com/exercism/docs/blob/main/anatomy/tracks/concepts.md) 
I'm leaning toward keeping the `concepts/` on the shorter side for two reasons:
- I tend to want to write novels... 😄 
- it seems much easier to expand these appropriately in our merging review and when eventually soliciting student contributions
Fix #1078.
=> close 1078 option cleanup

concepts/structs/about.md, concepts/structs/introduction.md
Close #1079.
I'm leaning towards keeping code samples out of our introduction.md's
and into `about.md`.
I like the style of introducing the concept in 1 or 2 lines of prose.
=> simplify struct's introduction, add to about.md

.github/workflows/tests.yml, .markdownlint.yaml, bin/markdown_lint.sh, concepts/explicit-return/about.md, concepts/option/about.md, concepts/structs/about.md, concepts/structs/introduction.md, exercises/practice/hello-world/GETTING_STARTED.md
This was much easier to configure and it look's like we can preserve the shell runner script pattern.
By that I mean ./bin/markdown_lint.sh does the work. And a contributor can run it locally too.
Close #1132.
- can I lint hidden files (.meta/design.md)? yes, will need to modify invocation
- can I exclude legacy files? Yes
- can I start with a small subset of linting rules? yes. 
- what is the CLI? Using: https://github.com/igorshubovych/markdownlint-cli#markdownlint-cli
=> minimal markdownlint CLI

exercises/practice/poker/tests/poker.rs
In the Poker practice exercise, returning the correct number of hands isn't tested. If three duplicate hands are given, only one needs to be returned, currently.
In `test_three_of_a_kind_cascade_ranks()`, the possibility of using multiple decks is allowed, so this corner condition is technically possible. However, the primary motivation is to make sure that the right number of hands are returned in the `Vec`.
Alternatively `hs_from()` function could use a `BinaryHeap` instead of a `HashSet`.
=> Add test for Poker `test_dupicate_hands_always_tie()`

.markdownlint.yaml
We ran into this in a PR review so I think it is reasonable to enable
it.
As an aside, I researched if markdown CLI let's you enforce reference style links. By default no.
But the underlying library does let you specify custom rules.
See another project's [implementation](https://github.com/webhintio/hint/commit/c412f9aa7ba99eb7ef6c20b7c496d629530f3ecf).
In our case, I find that too much trouble and maintenance for now.
=> enable another markdown lint rule

_test/check-exercises.sh, bin/test-exercise
This fixes running these scripts on NixOS and any other environment
where `bash` has been installed somewhere besides `/bin/`.
=> delegate shell location to env

exercises/practice/react/example.rs, exercises/practice/react/src/lib.rs, exercises/practice/react/tests/react.rs, exercises/practice/simple-linked-list/example.rs, exercises/practice/simple-linked-list/src/lib.rs
I batch applied the camel case abbreviation changes.
I was not sure about the simple-linked-list lint so exempted it.
- [exemption applied here](https://github.com/exercism/rust/compare/clippy-beta-fixes?expand=1#diff-82b44a277ea9de5d666b7f807136f46e26f46d7ed16a71c4ca3925a342a1e0bcR61)
- [clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into)
- [example failure](https://github.com/exercism/rust/runs/1919516153?check_suite_focus=true#step:7:268)
Since the clippy lint is new, it [fails](https://github.com/exercism/rust/runs/1920253485?check_suite_focus=true#step:7:10) for stable clippy runs. If I've taken the correct approach i'm happy to find a way to exempt this in the script executing clippy. 
Otherwise I'm open to refactoring the simple-linked-list …
=> Clippy beta fixes

exercises/practice/poker/.meta/example.rs, exercises/practice/poker/src/lib.rs, exercises/practice/poker/tests/poker.rs
Hi!
As discussed recently with @coriolinus, the `None` case can never really occur and was not tested either. Just an empty vector actually covers the desired semantics.
Cheers,
Paul.
=> forth: Remove `Option<_>` type requirement

.markdownlint.yaml, concepts/option/about.md
I took the liberty of enabling a few more markdown lints.
I could not find how to lint one sentence per line, which would be nice
to have.
Otherwise I:
- disabled inline HTML since I don't see the reason we should allow
this. Funny enough, the lint caught an example using `Option<T>` without
code ticks.
- no bare URLs
- consistent code fence style
=> enable a few more markdown lints

concepts/numbers/links.json, exercises/concept/numbers/.docs/hints.md
From what I understand, the specification encourages specific hints over
general ones.
Since the links in general were just that I put them in `links.json`.
Close #1128.
=> clean up numbers hints documentation

.github/workflows/tests.yml, bin/lint_trailing_spaces.sh, exercises/practice/spiral-matrix/tests/spiral-matrix.rs, util/exercise/Cargo.toml, util/exercise/src/main.rs
I was curious about what [util/exercise](https://github.com/exercism/rust/tree/main/util/exercise) and noticed the `Cargo.toml` has trailing whitespace.
So I took the opportunity to add a lint in CI too.
[This](https://github.com/exercism/rust/runs/1973793069#step:8:4) is an example failure.
=> add a trailing whitespace lint

bin/format_exercises
This happened because newer versions of Bash (5.x) rightly fail on using
`continue` incorrectly.
I rewrote that section to simply run `rustfmt` if the example is allowed
to compile. I am unsure why that is in a subshell.
As an aside, I tested this locally on macOS by running `brew install
bash`, then changing the shebang to use `/usr/local/bin/bash`.
=> fix CI error

exercises/practice/decimal/.meta/config.json, exercises/practice/decimal/.meta/metadata.yml, exercises/practice/doubly-linked-list/.meta/metadata.yml, exercises/practice/fizzy/.meta/config.json, exercises/practice/fizzy/.meta/metadata.yml, exercises/practice/luhn-from/.meta/config.json, exercises/practice/luhn-from/.meta/metadata.yml, exercises/practice/luhn-trait/.meta/config.json, exercises/practice/luhn-trait/.meta/metadata.yml, exercises/practice/macros/.meta/config.json, exercises/practice/macros/.meta/metadata.yml, exercises/practice/xorcism/.meta/config.json, exercises/practice/xorcism/.meta/metadata.yml
Combine v2 `metadata.yml` values into the v3 `config.json`.
Note I have not touched the `exercise` utility which still generates
`metadata.yml`.
Close #1166.
=> remove legacy metadata.yml files

docs/maintaining.md
Jot down notes from our conversations on this topic from #1212 and `git log` :)﻿
=> capture a maintainer convention

config/exercise_readme.go.tmpl
Stabilization of [`cargo test -- --include-ignore`](https://github.com/rust-lang/rust/pull/80053) reached 1.51.
The pull request incidentally [cites Exercism](https://github.com/rust-lang/rust/pull/80053#issue-540237999) as a use case, it would be a shame not to make users aware of this update.
=> option `--include-ignored` is now available on stable 1.51

exercises/practice/scale-generator/src/lib.rs
With the new release of rust 1.51, the nightlies are now building rust 1.53. 1.53 includes a new clippy lint which complains about interfaces which return `Result<_, ()>`; they should return `Option<_>` instead. 
In `scale-generator`, this design is intentional; we'd typedef'd `Error` to () with a long comment above so that students could define their own error type. This change produces a new unit struct instead. 
After merging, this PR should cause the `main` branch to successfully pass CI again.
=> fix new lints for scale-generator

exercises/practice/forth/.meta/config.json, exercises/practice/forth/.meta/example.rs, exercises/practice/forth/tests/alloc-attack.rs
Closes #1221.
Implements the approach suggested in that issue.
=> [forth] add test ruling out eager expansion of custom arguments.

concepts/integers/introduction.md
Because `let my_int: i32 = 2.;` will still error even if there is nothing to the right of the decimal separator.
=> [integer] update introduction.md

exercises/concept/semi-structured-logs/.docs/hints.md, exercises/concept/semi-structured-logs/.docs/instructions.md
Close #1192.
I updated the heading structure per [the specification](https://github.com/exercism/docs/blob/main/building/tracks/concept-exercises.md).
I also broke out the sentences into separate lines as I recently learned
Markdown will only render newlines when you have an empty newline between.
=> update semi-structured-logs to v3 spec

concepts/box/links.json
A useful command to show non-empty `links.json` example:
```sh
fd links.json concepts --size +4b | xargs bat
```
=> add detailed description of `Box`'s implementation to appropriate concept links

exercises/practice/anagram/tests/anagram.rs
Prevent solutions that use the sum of the ascii values of each char
to find anagrams.
=> Add test case to rust/anagram to prevent ascii-sum-solutions

exercises/concept/role-playing-game/.docs/instructions.md
The instructions for this exercise when casting a spell with insufficient mana say this:
```
If the player does not have access to a mana pool, attempting to cast the spell must decrease their health by the mana cost of the spell. The damage returned must be 0.
```
The correct behavior is outlined in this test:
```rust
#[test]
fn test_cast_spell_with_no_mana_pool() {
const MANA_COST: u32 = 10;
let mut underleveled_player = Player {
health: 87,
mana: None,
level: 6,
};
let clone = Player {
..underleveled_player
};
assert_eq!(underleveled_player.cast_spell(MANA_COST), 0);
assert_eq!(underleveled_player.health, clone.health - MANA_COST);
assert_eq!(underleveled_player.mana, clone.mana);
assert_eq!(underleveled_player.level, clone.level);
}
```
That being said, the docs seem to indicate that …
=> fix rpg test case with insufficient mana

exercises/practice/two-fer/src/lib.rs
Fixes https://github.com/exercism/rust/issues/1266
We currently have students (22 to be precise) who have an in progress TwoFer. Although it is deprecated it should still work as an exercise for those students. This aims to fix the fact that the solution is provided in the stub by providing a minimal compiling solution.
As I've never written Rust and don't have it installed, I'm entirely guessing at the syntax from a quick Google. If CI passes then I think this is fine. If not, I'll try and iterate until it does compile, but obviously if someone with Rust skills wants to just fix it, that's fine too 🙂
=> Remove the solution from the stub file of deprecated two-fer

config.json, exercises/concept/lucians-luscious-lasagna/.docs/hints.md, exercises/concept/lucians-luscious-lasagna/.docs/instructions.md, exercises/concept/lucians-luscious-lasagna/.docs/introduction.md, exercises/concept/lucians-luscious-lasagna/.meta/config.json, exercises/concept/lucians-luscious-lasagna/.meta/design.md, exercises/concept/lucians-luscious-lasagna/.meta/exemplar.rs, exercises/concept/lucians-luscious-lasagna/Cargo.toml, exercises/concept/lucians-luscious-lasagna/src/lib.rs, exercises/concept/lucians-luscious-lasagna/tests/lucians-luscious-lasagna.rs
While checking the status of the various tracks, I found that Rust has some nice Concept Exercises, but did not have a proper initial Concept Exercises, which is usually named `basics` in other tracks. This PR attempts to add the skeleton of such an exercise, which would allow us to enable the other Concept Exercises for Rust (by setting `.status.concept_exercises` to `true` in the `config.json` file).
I've based this exercise on similar implementations that we've used in other tracks and at https://github.com/exercism/rust/issues/1059.
The big kicker: I don't know any Rust :) This implementation will thus probably have mistakes in it, that I hope someone can fix for me. Speaking of help, knowing no Rust at all, the `introduction.md` documentation also needs to be rewritten by someone …
=> Add lasagna exercise

exercises/practice/dominoes/tests/dominoes.rs, exercises/practice/dot-dsl/tests/dot-dsl.rs, exercises/practice/grep/tests/grep.rs, exercises/practice/pangram/tests/pangram.rs, exercises/practice/sublist/tests/sublist.rs, exercises/practice/tournament/tests/tournament.rs
This was made an error in Clippy recently, so we'll need to fix it if we
want CI to work.
According to https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
What it does:
Checks for address of operations (`&`) that are going to be dereferenced
immediately by the compiler.
Why is this bad:
Suggests that the receiver of the expression borrows the expression.
Commentary as it applies to the Rust track:
I can get behind the idea that it's better not to mislead the reader of
the code about how many levels of reference the called function needs.
Most of these stem from a misunderstanding of what expressions were
already borrowed. They are listed below. Note carefully inconsistencies
introduced in sublist and tournament, and consider whether we have a
solution for this …
=> clippy: remove needless borrows

exercises/practice/hello-world/src/lib.rs
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

config.json
The concept entries this PR removes from the config.json all did not have any documents. This causes syncing to fail, which previously did not happen because we hadn't yet made the blurb a required field (we do now). There were basically two options:
1. Remove the concept entries from the config.json that did not have any documents
2. Create empty placeholder documents for the concepts
I've opted for option nr. 1, as option nr. 2 would also mean that I'd have to set the `authors` property of the concept's `.meta/config.json` file to a non-empty array and I can't really do that.
Closes https://github.com/exercism/rust/issues/1299
=> Remove concepts without documents

exercises/concept/role-playing-game/tests/role-playing-game.rs
The exemplar for this test suggests the use of `u32.saturating_sub`. However, there are no test cases that capture a use-case for it.
This patch adds in a single test that covers that case. Not sure if there was any specific reason for not adding this case in the first place.
=> role-playing-game: Add test that forces handing of integer overflow.

config.json
Hotfix for #1303 
The exercise config has 2 instances of status attribute with conflicting values. Thus the exercise was still active but could not be unlocked (due to reasons described in the issue).
This PR removes the duplicate status key and sets the exercise to WIP.
=> Set CSV Builder to WIP

exercises/concept/csv-builder/.meta/config.json
Fixes #1185 by adding a blurb to the CSV-build concept exercise.
=> fix: add blurb to csv-builder

exercises/concept/magazine-cutout/tests/magazine-cutout.rs
Reject solutions that can't construct note when magazine has more than enough.
Several are already published.
=> Add test to Magazine Cutout to reject invalid solutions

concepts/planned, config.json
Partial fix for #1318 
This fixes all failures due to missing entry in concepts array.
Other than adding missing entries to concepts array, following changes were made to some exercise entries:
1. replace `hashmaps` with `hashmap`
2. replace `numbers` with `integers`
3. replace `string-use` with `string`
4. remove `intro-types`
=> Partial Fix for configlet lint failure

exercises/practice/clock/tests/clock.rs
Thanks for all the hard work, I really enjoy using excercism v3 in the browser. This PR stems from a little friction I encountered, feel free to close it as you see fit.
While trying to solve this exercise, I got confused when I ran the tests and sometimes the expected value was on the left side of the comparison and sometimes on the right.
In some cases it is obvious `assertion failed: '(left == right)' left: "12:03", right: "-10:03"`, but others were not `assertion failed: '(left == right)' left: "12:03", right: "11:03"` .. which required me to go back and forth between the test implementation, output of tests and my implementation.
My proposal is to keep all expected values on one side, since the tests started with them being on the right hand side, I sticked with that.
=> clock: make all expected values on the right

exercises/concept/magazine-cutout/tests/magazine-cutout.rs
The addition of this test (in PR) makes _those_ (see below) wrong solutions fail, when they currently pass but shouldn't.
```rs
pub fn can_construct_note(magazine: &[&str], note: &[&str]) -> bool {
magazine.iter().fold(0, |acc, &word| acc + note.contains(&word) as usize) >= note.len()
}
```
=> Add a test to magazine-cutout

exercises/concept/assembly-line/tests/assembly-line.rs
Fixes #1320 
The test helper rounds the actual value down to the nearest hundredth of a unit.
=> Relax precision for assembly-line tests

exercises/practice/anagram/tests/anagram.rs
The part "these words different letters" of a comment within a test case
seems to miss a word, add the word "contain".
Signed-off-by: Sebastian Fricke <sebastian.fricke@posteo.net>
=> Anagram-exercise: Add missing word to comment in test

exercises/practice/grains/.docs/instructions.md
The original instructions for this exercise omit the panic message that is required for two of the tests to pass.
=> grains: adds instructions for the panic message

exercises/practice/gigasecond/.docs/instructions.append.md
#1384 replaced chrono with time crate. Reflect this change in instructions.
=> gigasecond: update instructions

config.json
With https://github.com/exercism/rust-analyzer/pull/39 being merged, we can re-enable the analyzer again. Thanks @petertseng!
Reverts exercism/rust#1399
=> Revert "Disable analyzer"

exercises/concept/rpn-calculator/.docs/instructions.md
This PR improves the instructions for the RPN exercise, by specifying that your solution should return `None` if there is more than one item left in the stack. This was not mentioned elsewhere in the instructions, but [is included in unit tests](https://github.com/exercism/rust/blob/0c24b8ec71669467ce3a2c59d61b9c2519fbd46f/exercises/concept/rpn-calculator/tests/rpn-calculator.rs#L70-L75).
I could include an example which demonstrates this, but I feel as though this should be pretty clear after this change — and makes the instructions more concise by omitting a new example.
=> Improve instructions for RPN Calculator

exercises/concept/role-playing-game/tests/role-playing-game.rs
the `dead_player` in `test_reviving_dead_level9_player` is an invalid state. A level 9 character should have `Player{mana: None,..}` not `Player{mana:Some(0),..}`.
The inspiration for this PR is that this clean solution without a `mana` field in the first arm of the match statement: 
```
impl Player {
pub fn revive(&self) -> Option<Player> {
match &self {
&Self{health:0, level: 0..10, ..} => Some(Self{health: 100, ..*self}),
&Self{health:0, level: 10.., ..} => Some(Self{health: 100, mana: Some(100), ..*self}),
_ => None
}
}
}
```
must be modified to this solution with a `mana` field:
```
impl Player {
pub fn revive(&self) -> Option<Player> {
match &self {
&Self{health:0, level: 0..10, ..} => Some(Self{health: 100, mana: None, ..*self}),
&Self{health:0, level: 10.., ..} => …
```
=> fix test_reviving_dead_level9_player

exercises/practice/queen-attack/tests/queen-attack.rs
This extra test catches an issue that existing tests do not:
Imagine the following code to check if two positions are on the same `\` diagonal, where `rank` and `file` are `u8` fields:
```rust
impl ChessPosition {
fn incomplete_is_same_diagonal_1(&self, other: &ChessPosition) -> bool {
self.rank.max(self.file) - self.file.min(self.rank)
== other.rank.max(other.file) - other.file.min(other.rank)
}
}
```
This might return `true` even though the positions are **not** on the same diagonal (neither `\` nor `/`), and that's what my new test case checks for.
History: I ended up with the above myself when solving the exercise, and noticed it was incorrect. But together with the check for `/` diagonals (`self.rank + self.file == other.rank + other.file`) it passed all the existing tests.
My …
=> queen-attack: Add test case to catch an incomplete diagonal check

exercises/concept/rpn-calculator/tests/rpn-calculator.rs
Now, RPN input like "+ 2 2 *" is not tested.
There are solutions (using fold) that produce "4" for the above example, while it should be "None" due to incorrect input.
Adding one more test case will catch this kind of errors.
=> Rust, RPN Calculator, Added test for missing operands

exercises/practice/scale-generator/.meta/example.rs, exercises/practice/scale-generator/tests/scale-generator.rs
The problem has been explained in
https://github.com/exercism/problem-specifications/issues/1640:
All previous cases only required N notes from N intervals, but that
meant the last interval was completely ignored.
That causes confusion (what is the last interval there for?).
To fix this, all tests with the `interval` property are updated.
The `tonic` and `intervals` inputs have not changed. The `expected` has
changed only in that there is one more note added, indicated by the last
interval, which was previously ignored.
https://github.com/exercism/problem-specifications/pull/1888
=> scale-generator: Require N+1 notes from N intervals

exercises/concept/lucians-luscious-lasagna/.docs/introduction.md
Defining scope via indentation is a Python feature, and not true for Rust.
=> luscious-lasagna: remove Python content from text

exercises/practice/xorcism/Cargo.toml
Closes https://github.com/exercism/rust/issues/1422
The error message complains that the only supported hexlit package (offline) is v0.5.3. Per semver, as a version under 1.0, that's not compatible with v0.3.0. 
This should fix the issue, but I'm not sure how to test the PR against the site before merging. @ErikSchierboom ?
=> xorcism: bump hexlit version

bin/clean_topics_vs_practices.py, config.json
Addresses #1407. I think this also has something to do with #1089. Though I'm not entirely sure.
I also created a python script to automate this task.
=> Clean up topics vs practices in config.json

docs/RESOURCES.md
As of March 2020, irc.mozilla.org has been [permanently decommissioned](https://wiki.mozilla.org/IRC).
=> Remove IRC channel that no longer exists

exercises/practice/decimal/.meta/example.rs, exercises/practice/decimal/tests/decimal.rs, exercises/practice/macros/tests/macros.rs
[Failing lints](https://github.com/exercism/rust/runs/4815983072?check_suite_focus=true).
=> address clippy lints found in new beta clippy 1.59

exercises/practice/clock/tests/clock.rs
Fixed missing semicolons in test so clippy::semicolon-if-nothing-returned doesn't complain.
https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned
=> clock: fixed missing semicolons

exercises/concept/assembly-line/.docs/instructions.md
It appears this was missed in #1207.
=> assembly-line: Fix sample calls in instructions

exercises/practice/custom-set/.meta/example.rs, exercises/practice/custom-set/src/lib.rs, exercises/practice/fizzy/.meta/example.rs, exercises/practice/fizzy/src/lib.rs, exercises/practice/robot-simulator/.meta/example.rs, exercises/practice/robot-simulator/src/lib.rs, exercises/practice/simple-linked-list/.meta/example.rs, exercises/practice/simple-linked-list/src/lib.rs
This fixes the new lint: https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use
=> add `#[must_use]` to several stub and example functions

exercises/practice/reverse-string/.meta/config.json
To complete this exercise in the browser, the user will need access to Cargo.toml in order to add dependencies.
=> reverse-string: Added Cargo.toml to config.json

exercises/concept/magazine-cutout/.docs/instructions.md, exercises/concept/magazine-cutout/tests/magazine-cutout.rs
add one success example in the introductions for magazine-cutout, that would make readers understand the meaning of the exercise easier.
=> add more introduction details for magazine-cutout

.github/workflows/tests.yml, _test/cargo_clean_all.sh, exercises/practice/perfect-numbers/.meta/example.rs
1.59.0-beta.6 (0426998f5 2022-02-02) runs into an internal compiler
error unless we do this.
(This has been reported to rustc in
https://github.com/rust-lang/rust/issues/93131)
It may be a good idea to keep this `clean` in the long term anyway, so
as to ensure that nothing from the "Check exercises" step unduly affects
the "Ensure stubs compile" step.
=> tests: `cargo clean` before checking stubs compile

exercises/practice/alphametics/.meta/config.json, exercises/practice/alphametics/tests/alphametics.rs
It was possible to pass tests without minding width of sum word. A test
with too short sum word exists, however the equation itself is invalid
due to leading zero, causing a lucky coincidence for some solutions.
This patch adds a test which is invalid only due to sum word length.
=> alphametics: add test case for too short sum

exercises/practice/queen-attack/.docs/instructions.md
Included extra examples of when queens can see each other, and when they cannot; and also added an explanation for why the queens are labelled B and W to help alleviate user confusion.
=> Rust: Update queen-attack instructions to be clearer for non-chess players

exercises/concept/assembly-line/.meta/exemplar.rs
A rate can be a positive real number, it doesn't have to be a whole
number of cars. This eliminates a cast as well.
=> use f64 for production rate

exercises/practice/luhn/tests/luhn.rs
I was doing the exercise luhn and noticed that some incorrect code I wrote was passing the tests.
I was using `some_char.is_numeric()` to test whether the char is allowed. Later I used `some_char.to_digit(10).unwrap()` on allowed characters. This program passes all tests but panics, when the received string contains a numeric Unicode character such as `①`.
Where I used `some_char.is_numeric()` I should have used `some_char.is_digit(10)` to test if the Input string contains any disallowed characters. 
I hope that adding this test will prevent other  people from making the same mistake in their code.
=> Add test to exercise luhn

_test/check_exercises.sh, _test/count_ignores.sh, _test/ensure_stubs_compile.sh
Test scripts used to be able to assume that everything in the
`exercises/` directory was in fact an exercise, but with certain
mandatory reorganization in v3 that is no longer a safe assumption.
This change helps the scripts to identify things which are not exercises.
The lack of this PR is causing CI failures on #1479.
=> improve scripts' ability to ignore things which are not exercises

exercises/practice/sublist/tests/sublist.rs
Adds one more test case for the `sublist` exercise to cover the case where the first list is longer than the second list, but they do not have a superlist relationship with each other.
This is similar to the case in the problem-specifications for sublist called "second list missing element from first list".  https://github.com/exercism/problem-specifications/blob/main/exercises/sublist/canonical-data.json#L158-L166
I added a test like this when I was working through the exercise myself because my initial TDD (don't write it until the tests force me to) naive implementation returned `Comparison::Superlist` any time the first list was longer than the second without bothering to actually check the contents, and that solution passed all the tests, but was definitely not correct. So I figured …
=> sublist: Add test for a longer list that is not a superlist

exercises/practice/sublist/tests/sublist.rs
Use the standard test case from the problem specifications, rather than a custom one that is similar.
=> sublist: use test case from problem specifications

concepts/match-basics/about.md, concepts/string-vs-str/about.md, docs/archived/exercise-concepts/parallel-letter-frequency.md, exercises/practice/luhn/tests/luhn.rs, exercises/practice/minesweeper/.docs/instructions.md
ASCII is an abbreviation and stands for American Standard Code for Information Interchange (ref: https://en.wikipedia.org/wiki/ASCII). I think it should be capitalized in all instances in this doc.
=> Capitalize ASCII

exercises/practice/rectangles/tests/rectangles.rs
Some solutions to this exercise will look for the top corners of the rectangles, making sure they are connected by a horizontal line, then go on to walk down the left and right side to find corners at the same row, in which case a rectangle is detected. These solutions sometimes fail to check that the bottom two corners are connected by a horizontal line. This test case will catch that.
=> rectangles: Add test for three disjoint rectangles

exercises/concept/resistor-color/src/lib.rs, exercises/concept/semi-structured-logs/src/lib.rs, exercises/practice/all-your-base/src/lib.rs, exercises/practice/allergies/src/lib.rs, exercises/practice/bowling/src/lib.rs, exercises/practice/circular-buffer/src/lib.rs, exercises/practice/custom-set/src/lib.rs, exercises/practice/forth/src/lib.rs, exercises/practice/largest-series-product/src/lib.rs, exercises/practice/ocr-numbers/src/lib.rs, exercises/practice/react/src/lib.rs, exercises/practice/rna-transcription/src/lib.rs, exercises/practice/robot-simulator/src/lib.rs, exercises/practice/sublist/src/lib.rs, exercises/practice/variable-length-quantity/src/lib.rs
Looks like the upcoming version of Clippy adds a lint for instances
where you derive PartialEq, but not Eq, and don't explain why. This
PR fixes those instances.
=> fix Clippy 1.63 Beta lints

exercises/concept/resistor-color/src/lib.rs
To better convey the intent, the type for color values should be an int type (I chose ``u32`` here, but any ``u*`` would do) instead of ``usize``, as it's not an index or an address.
> The primary situation in which you’d use isize or usize is when indexing some sort of collection.
from [The Rust Programming Language](https://doc.rust-lang.org/book/ch03-02-data-types.html) book
=> resistor-color: changed color values from usize to u32

exercises/practice/grep/.meta/example.rs
lines are terminated by newlines, not separated by newlines. using
`split('\n')` is incorrect because it interprets the trailing newline
(which is required by the POSIX standard) to separate the last actual
line in the file with a nonexistent empty line. `lines()` is the correct
way to split by lines.
Thus, the workaround of removing the empty line is also removed from the
example.
This was brought up in https://github.com/exercism/rust/issues/1530.
=> grep: use `lines()` instead of `split('\n')`

exercises/practice/poker/tests/poker.rs
Implementations that add values for pairs could have higher values than low three of a kinds.
=> poker: Ensure 222 beats AAKK

exercises/concept/magazine-cutout/.docs/instructions.md
`thread 'main' panicked at 'assertion failed: can_construct_note(&magazine, &note)` due to "." in the given example from Magazine Cutout exercise.
=> fix: 2nd assert example from Magazine Cutout exercise

exercises/practice/series/tests/series.rs
series: add a test going well beyond the edge case of `len == digits.len() + 1`
=> series: add test asking for way too many digits

exercises/concept/magazine-cutout/.docs/introduction.md
This is minor, but "either A and B" is wrong in English, it implies "either (A and B) or (C)". What the sentence wants is "either (A) or (B)", so this fixes it.
There's no associated issue yet, I assume something this tiny doesn't need it. But let me know if I should open one first nonetheless.
(First-time contributor to Exercism)
=> magazine-cutout: fix small grammatical error in the introduction

exercises/concept/resistor-color/.docs/instructions.md, exercises/concept/resistor-color/.docs/introduction.md, exercises/concept/resistor-color/Cargo.toml
int-enum crate was updated - https://github.com/Juici/int-enum-rs/issues/4
to be compatible with the latest rust-analyzer - https://github.com/rust-lang/rust-analyzer/issues/13347
=> resistor-color: Use int-enum 0.5.0 for compatilibity with rust-analyzer, and enum-iterator 1.2.0 for routine update

exercises/practice/leap/.approaches/boolean-one-line/content.md, exercises/practice/leap/.approaches/boolean-one-line/snippet.txt, exercises/practice/leap/.approaches/config.json, exercises/practice/leap/.approaches/date-addition-chrono/content.md, exercises/practice/leap/.approaches/date-addition-chrono/snippet.txt, exercises/practice/leap/.approaches/date-addition-time/content.md, exercises/practice/leap/.approaches/date-addition-time/snippet.txt, exercises/practice/leap/.approaches/introduction.md, exercises/practice/leap/.approaches/match-on-a-tuple/content.md, exercises/practice/leap/.approaches/match-on-a-tuple/snippet.txt, exercises/practice/leap/.approaches/ternary-expression/content.md, exercises/practice/leap/.approaches/ternary-expression/snippet.txt, exercises/practice/leap/.articles/config.json, exercises/practice/leap/.articles/performance/code/main.rs, exercises/practice/leap/.articles/performance/content.md, exercises/practice/leap/.articles/performance/snippet.md
Initial commits for file structure and code. Details to follow...
=> Leap approaches

exercises/concept/health-statistics/.docs/hints.md, exercises/concept/health-statistics/.docs/instructions.md, exercises/concept/health-statistics/.meta/exemplar.rs, exercises/concept/health-statistics/src/lib.rs, exercises/concept/health-statistics/tests/health-statistics.rs
In this branch:
+ Setter methods for age and weight are renamed to follow [Rust API guidelines](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter). They indicate mutability, which is idiomatic in Rust.
+ Added `#[ignore]` to `test_name` as it was missing (and failing).
=> Health Statistics Concept Exercise Fix

exercises/practice/isogram/.approaches/config.json
Commit e76c930fc907 added approaches for the isogram exercise, but there was a typo in a `slug` value. [There is](https://github.com/exercism/rust/tree/b71ba70dc621b32de8970946317094319f9a1738/exercises/practice/isogram/.approaches) indeed a `bitfield` subdirectory.
In this situation, it is likely that an upcoming version of configlet will produce an error like:
```console
$ configlet lint
[...]
A 'slug' value is 'bitfied', but there is no sibling directory with that name:
./exercises/practice/isogram/.approaches/config.json
```
---
Ping @bobahop / @ErikSchierboom
=> isogram: approaches: fix slug

exercises/practice/xorcism/Cargo.toml, exercises/practice/xorcism/tests/xorcism.rs
Refers to [this issue](https://github.com/exercism/rust/issues/1513#issuecomment-1314025738).
rstest uses proc macros, which make the tests timeout due to long compile times. Replace rstest with a custom declarative macro.
Drawbacks:
- more indentation
- module structure of tests is flipped around
both of those seem minor to me.
Although declarative macros can be hard to read for those unfamiliar, that was already somewhat the case with `rstest`'s magic in my opinion. So I personally don't think it's worse in terms of the users being able to understand the tests.
The only other alternative I see is to disable the online tests altogether and leave a note about that in the exercise description. That probably wouldn't be that bad, since people solving this hard exercise most likely have a …
=> xorcism: remove rstest dependency (exercism#1513)

.github/labels.yml, CODE_OF_CONDUCT.md, bin/fetch-configlet
see individual commit messages.
these commits **MUST NOT** be squashed when merging
=> labels, CODE_OF_CONDUCT, fetch-configlet: sync from org-wide-files

exercises/practice/pangram/.approaches/introduction.md
Change `is_substring` to `is_subset` in introduction.md.
Changing
```
You can see if the `HashSet` of the alphabet `is_substring` of a `HashSet` of the lowercased `sentence`.
```
to
```
You can see if the `HashSet` of the alphabet `is_subset` of a `HashSet` of the lowercased `sentence`.
```
=> pangram approaches fix

exercises/practice/grains/.articles/performance/content.md
Fix typo for link to bit-shifting approach in performance article.
=> Grains approaches fix

exercises/concept/resistor-color/.meta/config.json
The configlet fmt command removed custom key-value pairs.
This adds the unformatted file back for resistor-color, which
looks like it is the only one where this happened.
See https://forum.exercism.org/t/online-test-timeout-with-recommended-solution/1574
=> Revert the configlet fmt on resistor-color

exercises/practice/hello-world/.docs/instructions.append.md
Hi, this is an update to the Hello World exercise of the Rust track. The track never introduces how to run tests to the user. It is described in the HELP file but I believe that file is meant for you to check when you get lost solving the exercise? It should continue to contain the more detailed information on how to run tests IMO but the basic command I believe should be a part of the README.
=> hello-world: Show how to run the tests in the instructions

exercises/practice/say/.docs/instructions.append.md
* Closes https://github.com/exercism/rust/issues/1611
=> say/docs: fix typo in say max value

config.json
We've had several complaints from students that the learning mode doesn't work well for them. I think it's best to disable it temporarily and then look at ways how to fix it.
=> Disable learning mode

exercises/practice/largest-series-product/.docs/instructions.md, exercises/practice/largest-series-product/.docs/introduction.md, exercises/practice/largest-series-product/tests/largest-series-product.rs
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
=> Sync largest-series-product docs with problem-specifications

exercises/practice/rna-transcription/.docs/instructions.append.md
I recently completed https://exercism.org/tracks/rust/exercises/rna-transcription, but couldn't quite figure out what the error type in the signatures of `DNA::new()` and `RNA::new()` was supposed to mean from looking at the tests. Unfortunately, I interpreted it as "the number of different nucleotides used before encountering the first invalid char", which just so happened to pass the test cases, even though it was wrong. (I can submit a separate PR for fixing up those test cases.)
It turns out though that the `usize` in `Result<Self, usize>` was meant to mean "the first invalid character index": https://exercism.org/tracks/rust/exercises/rna-transcription
This PR clarifies the meaning of the error value in the return type.
=> Clarify constructor return types for RNA Transcription exercise

exercises/practice/luhn-from/tests/luhn-from.rs, exercises/practice/luhn-trait/tests/luhn-trait.rs
9 is an edge case that is very important to keep testing in the advanced Luhn iteration exercises (Luhn From and Luhn Trait).
I know it because I was optimizing my solutions and after passing all the From and Trait tests, when I put those optimizations in my original Luhn solution, it failed the Luhn tests. Turns out the canonical specification had a test case for this! So I'm adding it to the advanced exercises as well.
=> Added digit 9 test case from the canonical test suite.

exercises/practice/paasio/tests/paasio.rs, exercises/practice/proverb/tests/proverb.rs
The Rust 1.72 beta introduced [a couple new clippy warnings](https://github.com/exercism/rust/actions/runs/5609359865/jobs/10262955846), which need fixing for our CI.
`clippy::redundant_closure_call`:
> try not to call a closure in the expression where it is declared
and `clippy::useless_vec`.
=> Fix new clippy warnings

exercises/practice/hexadecimal/src/lib.rs, exercises/practice/nucleotide-codons/src/lib.rs
I missed [one more clippy warning](https://github.com/exercism/rust/actions/runs/5612515528/job/15206434155) in the stubs.
It actually occurred in the stub of a deprecated exercise, which had a full implementation as a stub because of https://github.com/exercism/rust/pull/832.
I turned them back into regular stubs, so we don't have to maintain implementations of deprecated exercises.
=> Remove impls of deprecated exercises

exercises/practice/xorcism/Cargo.toml, exercises/practice/xorcism/tests/xorcism.rs
If we use dev-dependencies, breaking changes of those dependencies can break stundents' old solutions.
closes #1422
=> Remove dev-dependency hexlit

docs/TESTS.md
closes #1365
I'm not sure if the `docs/TESTS.md` file is the correct place to add this, but the [building documentation](https://exercism.org/docs/building/tracks/docs) has an example where that is the case.
I slightly updated the rest of that file as well.
=> Document available crates

.github/workflows/tests.yml
actions-rs is unmaintained, the last commit is from March 2020. https://github.com/actions-rs/toolchain
The Rust community recommends dtolnay/rust-toolchain these days, e.g. https://blessed.rs/crates#section-tooling
The fact that actions-rs is unmaintained shows for example in the [deprecation warnings](https://github.com/exercism/rust/actions/runs/5633367871) we're getting in CI
Judging from the [documentation](https://github.com/dtolnay/rust-toolchain#inputs), I think the toolchain specifier remains the same.
=> Replace actions-rs with dtolnay/rust-toolchain

exercises/practice/saddle-points/.docs/instructions.md
First line of demo grid is interpreted as a code block and the rest as paragraph text. Wrapping the whole thing in code tags forces it to be shown in fixed-width text instead.
=> Saddle-points: fix formatting of instructions

exercises/practice/all-your-base/src/lib.rs
This exercise was revised to use domain specific errors. However, a  leftover comment still suggests, that the specific value in Err(.) won't be checked.
=> all-your-base: Update outdated comment

.github/workflows/tests.yml, bin/check_exercises.sh, bin/ensure_stubs_compile.sh, bin/format_exercises.sh, bin/test_exercise.sh, rust-tooling/tests/bash_script_conventions.rs
Single commands that may error can stil be achieved with `|| true`.
With this change, we'll only see a limited number of clippy warnings
in CI. I think that's fine, the one fixing it can still remove these
flags locally while working on the fix to see all warnings.
=> Enforce idiomatic error handling in bash

exercises/practice/circular-buffer/.meta/example.rs
The trait bounds `Default + Clone` are semantically incorrect. A proper circular buffer needs to handle all kinds of elements.
The reason these bounds are here is because it allows to avoid `unsafe` while enjoying the most efficient memory layout.
However, there is another performance downside:
The implementations of `Default` and `Clone` may be expensive (e.g. cause heap allocations.)
As came up in this discussion, there are other weird side effects, for example for `Rc` which has a non-standard implementation of `Clone`: https://github.com/exercism/rust/pull/1652
The approach I chose here get's rid of the trait bounds and wraps every element in an `Option`.
In the worst case, this may lead to twice the memory consumption. (e.g. `Option<u64>` takes 16 bytes because of alignment and …
=> Improve example solution of circular-buffer

exercises/concept/low-power-embedded-game/tests/low-power-embedded-game.rs
Source:
https://github.com/exercism/rust/pull/1583
Students may think they have to work with values
instead of their position.
This confusion can easily be avoided if the first test uses strings.
=> Improve test order of low-power-embedded-game

.gitignore, bin/symlink_problem_specifications.sh, docs/CONTRIBUTING.md
This is handy when referring to `canonical-data.json` of an exercise,
while creating / updating the test template for it.
It's all available in the same spot.
=> Symlink problem-specifications for easy reference

.gitignore, bin/symlink_problem_specifications.sh, docs/CONTRIBUTING.md, exercises/practice/doubly-linked-list/.docs/instructions.md
=> doubly-linked-list: Fix inaccurate instructions

exercises/practice/variable-length-quantity/.docs/instructions.md, exercises/practice/variable-length-quantity/.meta/test_template.tera, exercises/practice/variable-length-quantity/.meta/tests.toml, exercises/practice/variable-length-quantity/src/lib.rs, exercises/practice/variable-length-quantity/tests/variable-length-quantity.rs
Notably, this removes any tests about overflow as well as the
overflow variant from the error enum in the stub.
Overflow handling is a valuable thing to learn and practice,
but there are other exercises which do that.
So it seems unnecesary to expand the case only on the Rust track
and maintain our own additional tests.
This is a backwards compatible change,
submissions which choose to handle overflow should still work fine.
=> Sync variable-length-quantity with problem-specifications

exercises/practice/word-count/.meta/example.rs, exercises/practice/word-count/.meta/test_template.tera, exercises/practice/word-count/.meta/tests.toml, exercises/practice/word-count/tests/word-count.rs
new tests found a bug in the example solution with apostrophe handling
=> Sync word-count with problem-specifications

bin/check_exercises.sh, bin/ensure_stubs_compile.sh, bin/test_exercise.sh
Most importantly, move all required files for testing to a tmp dir. This means the actual files in the repository are not modified anymore. Running these scripts locally does not interrupt the git workflow now.
The output is also cleaned up in various situations.
closes #1738
=> Cleanup test scripts

docs/archived/exercise-concepts/luhn.md, exercises/concept/csv-builder/.meta/exemplar.rs, exercises/practice/acronym/.meta/example.rs, exercises/practice/affine-cipher/.meta/example.rs, exercises/practice/atbash-cipher/.meta/example.rs, exercises/practice/book-store/.meta/example.rs, exercises/practice/bowling/.meta/example.rs, exercises/practice/custom-set/.meta/example.rs, exercises/practice/decimal/.meta/Cargo-example.toml, exercises/practice/decimal/.meta/example.rs, exercises/practice/dot-dsl/.meta/example.rs, exercises/practice/doubly-linked-list/.meta/example.rs, exercises/practice/forth/.meta/example.rs, exercises/practice/grade-school/.meta/example.rs, exercises/practice/hexadecimal/.meta/example.rs, exercises/practice/high-scores/.meta/example.rs, exercises/practice/largest-series-product/.meta/example.rs, exercises/practice/luhn-from/.meta/example.rs, exercises/practice/luhn/.meta/example.rs, exercises/practice/matching-brackets/.meta/example.rs, exercises/practice/palindrome-products/.meta/example.rs, exercises/practice/phone-number/.meta/example.rs, exercises/practice/pig-latin/.meta/example.rs, exercises/practice/queen-attack/.meta/example.rs, exercises/practice/react/.meta/example.rs, exercises/practice/rectangles/.meta/example.rs, exercises/practice/robot-name/.meta/example.rs, exercises/practice/scale-generator/.meta/example.rs, exercises/practice/simple-linked-list/.meta/example.rs, exercises/practice/tournament/.meta/example.rs
CI errors are now surfacing because of [this semi-conscious change](https://github.com/exercism/rust/pull/1746/files#diff-c97b02ca592b9137046a9842fd1d13e04f1baaba1085b41aee9856bea0cfcf6dL97-L100).
Previously, clippy was only run over the test files. Now it is run over the example solutions as well. I like it this way and applied the relevant fixes.
=> Fix clippy warnings in example solutions

exercises/practice/acronym/.docs/instructions.md, exercises/practice/acronym/.meta/test_template.tera, exercises/practice/acronym/tests/acronym.rs
motivated by [this forum post](https://forum.exercism.org/t/camelcase-test-unintentionally-removed-from-rust-acronym-exercise/7393/3).
(piggybacking the nicely formatted markdown table from upstream.)
=> acronym: Reintroduce camel case test

.github/workflows/tests.yml
Running the beta version of clippy in CI creates unnecessary churn.
This time, a lint was renamed and it is not easy to satisfy *both* the stable and beta version.
Within six weeks, our CI would probably be broken again.
I also vaguely remember changing a bunch of stuff because of a beta lint, which didn't end up being stabilized after all.
=> Don't run beta clippy in CI

rust-tooling/src/bin/generate_exercise.rs
Function declarations like
```rust
fn foo<T>(arg: T) {}
```
would result in a function name of `foo<T>`, so we need to strip the generics as well.
=> Test gen: strip generics from function names

exercises/practice/custom-set/.meta/example.rs, justfile
Also, `just test` now runs clippy over all exercises, making it easier to simulate CI locally.
=> Fix clippy warnings

exercises/practice/rotational-cipher/.docs/instructions.md, exercises/practice/rotational-cipher/.meta/example.rs, exercises/practice/rotational-cipher/.meta/test_template.tera, exercises/practice/rotational-cipher/.meta/tests.toml, exercises/practice/rotational-cipher/src/lib.rs, exercises/practice/rotational-cipher/tests/rotational-cipher.rs
The two tests with negative keys as input were removed.
The exercise instructions specify a range of 0 to 26.
The function signature of the skeleton was adjusted accordingly,
using `u8` instead of `i8` to make negative numbers impossible.
The removal of these tests was discussed on the forum:
https://forum.exercism.org/t/rotational-cipher-negative-keys/8273
=> Sync rotational-cipher with problem-specifications

exercises/practice/run-length-encoding/.docs/instructions.md, exercises/practice/run-length-encoding/.meta/test_template.tera, exercises/practice/run-length-encoding/.meta/tests.toml, exercises/practice/run-length-encoding/tests/run-length-encoding.rs, rust-tooling/src/exercise_config.rs
=> Sync run-length-encoding with problem-specifications

exercises/practice/rna-transcription/.meta/additional-tests.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/rna-transcription/.meta/test_template.tera, exercises/practice/rna-transcription/.meta/tests.toml, exercises/practice/rna-transcription/tests/rna-transcription.rs
There were some additional test, and I kept some of them.
They are related to error handling, which is a big focus for Rust.
So I felt it is appropriate to keep these additional tests.
=> Sync rna-transcription with problem-specifications

exercises/practice/proverb/.docs/instructions.md, exercises/practice/proverb/.meta/config.json, exercises/practice/proverb/.meta/test_template.tera, exercises/practice/proverb/.meta/tests.toml, exercises/practice/proverb/tests/proverb.rs
=> Sync proverb with problem-specifications

bin/test_exercise.sh
The fuzzy matching of the path to the exercise slug would match "pascals-triangle" before "triangle".
=> Fix test_exercise.sh script

rust-tooling/generate/templates/default_test_template.tera
Glob imports are a better default for the test template. Some exercises may require the student to implement a method. If the test file doesn't have a glob import, the students will be forced to implement an inherent method on a struct. On the other hand, if a glob import is used, the students may choose to implement it as a method on a trait.
Traits are a powerful feature of Rust, so we want to enable students to experiment with them whenever possible.
=> Use glob import in default test template

docs/CONTRIBUTING.md, exercises/practice/triangle/.meta/additional-tests.json, exercises/practice/triangle/.meta/example.rs, exercises/practice/triangle/.meta/test_template.tera, exercises/practice/triangle/.meta/tests.toml, exercises/practice/triangle/tests/triangle.rs
There was one challenge implementing the test template. The problem specification of this exercise states that it is up to the individual language tracks how to handle invalid triangles. However, this property is not easy to detect from the specification of the test cases. The test cases with invalid triangles were excluded in tests.toml and reimplemented in additional-tests.json with a custom property of "invalid".
It was also necessary to separate the different properties into individual modules. Some descriptions - and therefore the generated test case names - are duplicated across different properties, so they have to be in different namespaces.
=> Sync triangle with problem-specifications

exercises/shared/.docs/debug.md
=> Add documentation for debugging online

exercises/practice/circular-buffer/tests/circular-buffer.rs
A common solution to this exercise is to use `MaybeUninit<T>` in the buffer. However, `MaybeUninit<T>` explicitly never calls `T`s drop code.
A sound solution should drop elements in the buffer when it is dropped. This test checks for that.
=> Add a test to the CircularBuffer exercise to check if elements in the buffer are dropped when the buffer is dropped

exercises/practice/anagram/src/lib.rs
This is basically a revert of #1755.
The original "fix" was a reaction to this forum post: https://forum.exercism.org/t/the-function-signature-for-anagrams-in-rust-is-missing-a-lifetime/7677
It seems the exercise instructions, which explicitly mention that this missing lifetime annotation is intentional, went unnoticed.
=> Fix already-solved lifetime challenge in anagram

exercises/practice/anagram/.docs/hints.md, exercises/practice/anagram/.docs/instructions.append.md
- Remove some performance considerations. These are basically giving away the implementation. Also, not every student might want to focus on performance. Such considerations may be better suited for approaches articles.
- Remove non-Rust-related hints. These are pretty much covered by the instructions. I guess these were lacking at some point, but updated in the meantime.
- Move the most important hint about lifetimes to the top.
=> Update instructions append for anagram

exercises/practice/accumulate/.docs/hints.md, exercises/practice/binary-search/.docs/hints.md, exercises/practice/binary-search/.docs/instructions.append.md, exercises/practice/clock/.docs/instructions.append.md, exercises/practice/decimal/.docs/hints.md, exercises/practice/decimal/.docs/instructions.md, exercises/practice/dot-dsl/.docs/instructions.append.md, exercises/practice/doubly-linked-list/.docs/hints.md, exercises/practice/forth/.docs/instructions.append.md, exercises/practice/hello-world/.docs/instructions.append.md, exercises/practice/high-scores/.docs/hints.md, exercises/practice/largest-series-product/.docs/hints.md, exercises/practice/macros/.docs/instructions.append.md, exercises/practice/paasio/.docs/instructions.append.md, exercises/practice/parallel-letter-frequency/.docs/instructions.append.md, exercises/practice/poker/.docs/hints.md, exercises/practice/reverse-string/.docs/instructions.append.md, exercises/practice/rna-transcription/.docs/instructions.append.md, exercises/practice/say/.docs/instructions.append.md, exercises/practice/simple-linked-list/.docs/hints.md, exercises/practice/space-age/.docs/instructions.append.md, exercises/practice/triangle/.docs/instructions.append.md, exercises/practice/xorcism/.docs/instructions.append.md, rust-tooling/ci-tests/tests/docs_are_valid.rs
- Move some content from instructions.append.md which contain hints
to hints.md.
- Make sure all instructions.append.md files start with the line
`# Instructions append`.
https://exercism.org/docs/building/tracks/practice-exercises#h-file-docs-introduction-append-md
- Make sure all hints.md files start with the line `## General`.
https://exercism.org/docs/building/tracks/practice-exercises#h-file-docs-hints-md
- Add tests for the correct headings.
=> Make instructions append and hints consistent

exercises/practice/leap/.docs/instructions.md, exercises/practice/leap/.docs/introduction.md, exercises/practice/leap/.meta/config.json, exercises/practice/leap/.meta/test_template.tera, exercises/practice/leap/.meta/tests.toml, exercises/practice/leap/tests/leap.rs
A bunch of test cases not part of problem-specifications were deleted. Looking through the git history, it seems the manual cases were added first and the ones from problem-specfications later. Some cases are even duplicated because of this. I checked if there are some interesting edge cases worth upstreaming. The most likely ones would be:
```
process_leapyear_case(1, false);
process_leapyear_case(4, true);
```
problem-specifications doesn't yet have any test cases close to the year zero. That being said, I can't think of a concrete solution that would fail these test cases. So it might not be worth upstreaming after all.
=> Sync leap with problem-specifications

exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/tests/anagram.rs
I accidentally removed some unicode related tests in PR #1844. These are now upstreamed to problem-specifications.
=> anagram: Bring back unicode tests

exercises/practice/acronym/.meta/additional-tests.json, exercises/practice/acronym/.meta/test_template.tera, exercises/practice/acronym/tests/acronym.rs, justfile
The mechanism of the `additional-tests.json` file did not exist at the time I wrote this test template. This makes everything consistent.
=> Apply additional tests consistently

exercises/practice/knapsack/tests/knapsack.rs, exercises/practice/queen-attack/.meta/test_template.tera, exercises/practice/variable-length-quantity/.meta/test_template.tera, exercises/practice/wordy/.meta/additional-tests.json, exercises/practice/wordy/.meta/test_template.tera, rust-tooling/generate/src/lib.rs, rust-tooling/generate/src/main.rs, rust-tooling/generate/tests/tera_templates_are_in_sync.rs
=> Add test to ensure tera templates are in sync

config.json, exercises/practice/matrix/.docs/instructions.append.md, exercises/practice/matrix/.docs/instructions.md, exercises/practice/matrix/.gitignore, exercises/practice/matrix/.meta/additional-tests.json, exercises/practice/matrix/.meta/config.json, exercises/practice/matrix/.meta/example.rs, exercises/practice/matrix/.meta/test_template.tera, exercises/practice/matrix/.meta/tests.toml, exercises/practice/matrix/Cargo.toml, exercises/practice/matrix/src/lib.rs, exercises/practice/matrix/tests/matrix.rs
Per forum post - [Adding Matrix to the Rust Track](http://forum.exercism.org/t/adding-matrix-to-the-rust-track/10480)
Here's what I did:
- Added Matrix exercise from problem-specifications using `rust-tooling/generate`
- Created example.rs
- Added all required tests
- Created boilerplate in lib.rs
This is my first contribution so there's a chance I probably forgot something but it looks like all cargo and CI tests are running on my end, so hopefully we should be good.
Also, I increased the difficulty to 4 as depending on the implementation you could be working with nested iterators/map/collect, but I was going back and forth on this. If you think 1 is still more appropriate, just let me know and I'll switch it back. 
Thanks!
=> Add Exercise Matrix

config.json, exercises/practice/eliuds-eggs/.docs/instructions.md, exercises/practice/eliuds-eggs/.docs/introduction.md, exercises/practice/eliuds-eggs/.gitignore, exercises/practice/eliuds-eggs/.meta/config.json, exercises/practice/eliuds-eggs/.meta/example.rs, exercises/practice/eliuds-eggs/.meta/test_template.tera, exercises/practice/eliuds-eggs/.meta/tests.toml, exercises/practice/eliuds-eggs/Cargo.toml, exercises/practice/eliuds-eggs/src/lib.rs, exercises/practice/eliuds-eggs/tests/eliuds-eggs.rs
Even though I wrote the exercise generator, I believe this is the first _new_ exercise I'm adding with it. Checklist for manual things I did, please let me know if I missed something:
- tweak test template
- implement example solution
- add difficulty of `1`
- fill config.json (author, files)
Oh and I bumped the problem-specifications submodule, which is only used by my exercise generator.
=> Add exercise eliuds-eggs

exercises/practice/forth/.meta/test_template.tera, exercises/practice/forth/.meta/tests.toml, exercises/practice/forth/tests/forth.rs
=> forth: sync

exercises/practice/circular-buffer/.meta/additional-tests.json, exercises/practice/circular-buffer/.meta/test_template.tera, exercises/practice/circular-buffer/.meta/tests.toml, exercises/practice/circular-buffer/tests/circular-buffer.rs
=> circular-buffer: sync

exercises/practice/collatz-conjecture/.meta/test_template.tera, exercises/practice/collatz-conjecture/.meta/tests.toml, exercises/practice/collatz-conjecture/tests/collatz-conjecture.rs, rust-tooling/generate/src/lib.rs, rust-tooling/generate/templates/default_test_template.tera
The additional test cases for overflow are incorrect even with u64 in the API. u128 can be used as needed to calculate the intermediate values without overflow.
=> collatz-conjecture: sync

exercises/practice/protein-translation/.meta/additional-tests.json, exercises/practice/protein-translation/.meta/test_template.tera, exercises/practice/protein-translation/.meta/tests.toml, exercises/practice/protein-translation/tests/protein-translation.rs
=> protein-translation: sync

exercises/practice/series/.docs/instructions.append.md
The controversial test case was previously removed without updating the exercise instructions. This change brings the instructions in line with the tests.
- [PR removing the test][1]
- [forum discussion about removing the test][2]
- [report of outdated documentation][3]
[1]: https://github.com/exercism/rust/pull/1822
[2]: https://forum.exercism.org/t/feedback-wanted-removing-controversial-test-from-series-exercise/8659
[3]: https://forum.exercism.org/t/add-test-for-zero-length-case-on-exercise-series/11070
=> series: fix outdated instructions

exercises/practice/triangle/.docs/instructions.append.md
The current version of ` instructions.append.md` gives an inaccurate definition of a right triangle:
`an isosceles triangle whose equal sides are separated by 90 degrees`
(a right triangle need not be isosceles)
This PR attempts to fix this while trying not to add too much additional text that's incidental to the exercise - hopefully the result is readable!
The PR also tries to clarify a little the phrasing about  the representation of irrationals, at the end of the same paragraph.
=> Update instructions.append.md for Triangle

exercises/practice/grep/src/lib.rs
clap and structopt are not available in the test runner. This is because their derive-API (which is the most popular) takes too long to compile.
=> grep: remove suggestion of unavailable crates

exercises/practice/protein-translation/.meta/example.rs, exercises/practice/protein-translation/.meta/test_template.tera, exercises/practice/protein-translation/tests/protein-translation.rs
This is to stay consistent with canonical-data and the instructions. Users can more easily copy-paste the names from the instructions.
=> protein-translation: keep names uppercase

exercises/practice/paasio/tests/paasio.rs
Adds two tests to the PaaS I/O exercise to check that I/O errors are propagated rather than unwrapped/expected. [Fixes #992]
=> Add error handling tests to PaaS I/O

.gitignore, .gitmodules, bin/checkout_pinned_problem_specifications_commit.sh, bin/configlet_wrapper.sh, bin/get_problem_specifications_dir.sh, bin/symlink_problem_specifications.sh, bin/update_problem_specifications.sh, justfile, rust-tooling/ci-tests/tests/bash_script_conventions.rs
The previous approach used a submodule to keep things somewhat stable.
That worked well for the rust-tooling (exercise generator) which made
use of the submodule. However, configlet continued to use its own cache.
(see https://github.com/exercism/configlet/issues/816)
This could lead to problems where the configlet cache and the submodule
are out of sync and don't agree.
The new approach ditches the submodule and makes everything use the
configlet cache. Some helper scripts are responsible to make sure the
cache is checked out at the pinned commit and a configlet wrapper sets
the `--offile` flag to prevent configlet from updating the cache.
=> Pin problem-specifications to a specific commit

docs/CONTRIBUTING.md, exercises/practice/armstrong-numbers/.meta/test_template.tera, exercises/practice/armstrong-numbers/.meta/tests.toml, exercises/practice/armstrong-numbers/tests/armstrong-numbers.rs, rust-tooling/generate/Cargo.toml, rust-tooling/generate/src/custom_filters.rs
This also adds a new custom tera filter to format number literals in a more human-readable way (by inserting `_` every third digit).
Most of the additional tests don't seem to add any particular value except for the last one, which is [under consideration for upstreaming](https://forum.exercism.org/t/armstrong-numbers-test-case-against-overflow/12457).
=> armstrong-numbers: sync

rust-tooling/ci-tests/tests/stubs_are_warning_free.rs, rust-tooling/generate/src/cli.rs, rust-tooling/generate/src/main.rs
With the configlet wrapper added in https://github.com/exercism/rust/pull/1950, the `--offline` flag is now always set.
=> generator: remove redundant flag

docs/CONTRIBUTING.md, exercises/practice/all-your-base/.meta/test_template.tera, exercises/practice/all-your-base/.meta/tests.toml, exercises/practice/all-your-base/tests/all-your-base.rs, rust-tooling/generate/src/custom_filters.rs
=> all-your-base: sync

bin/test_exercise.sh, exercises/practice/binary-search/.meta/test_template.tera, exercises/practice/binary-search/.meta/tests.toml, exercises/practice/binary-search/Cargo.toml, exercises/practice/binary-search/tests/binary-search.rs
=> binary-search: sync

.ignore, exercises/practice/collatz-conjecture/.meta/test_template.tera, exercises/practice/collatz-conjecture/tests/collatz-conjecture.rs, exercises/practice/eliuds-eggs/.meta/test_template.tera, exercises/practice/eliuds-eggs/tests/eliuds-eggs.rs, exercises/practice/nth-prime/.meta/test_template.tera, exercises/practice/nth-prime/tests/nth-prime.rs, exercises/practice/perfect-numbers/.meta/test_template.tera, exercises/practice/perfect-numbers/tests/perfect-numbers.rs, exercises/practice/prime-factors/.meta/test_template.tera, exercises/practice/prime-factors/tests/prime-factors.rs, exercises/practice/pythagorean-triplet/.meta/test_template.tera, exercises/practice/pythagorean-triplet/tests/pythagorean-triplet.rs, exercises/practice/say/.meta/test_template.tera, exercises/practice/say/tests/say.rs, exercises/practice/space-age/.meta/test_template.tera, exercises/practice/space-age/tests/space-age.rs, exercises/practice/sum-of-multiples/.meta/test_template.tera, exercises/practice/sum-of-multiples/tests/sum-of-multiples.rs, exercises/practice/variable-length-quantity/.meta/test_template.tera, exercises/practice/variable-length-quantity/tests/variable-length-quantity.rs
=> Make number literals more human readable

exercises/practice/grep/.meta/test_template.tera, exercises/practice/grep/.meta/tests.toml, exercises/practice/grep/tests/grep.rs
=> grep: sync

exercises/practice/paasio/tests/paasio.rs
This is simply a manual expansion of the macros. There is no canonical data from problem specifications, so the tests won't change often and the maintenance burden of the duplication should be acceptable.
=> paasio: remove macros from tests

exercises/practice/xorcism/.meta/additional-tests.json, exercises/practice/xorcism/.meta/test_template.tera, exercises/practice/xorcism/tests/xorcism.rs, rust-tooling/models/src/exercise_config.rs
=> xorcism: remove macro from tests

docs/CONTRIBUTING.md, exercises/practice/paasio/.meta/config.json, exercises/practice/xorcism/.meta/config.json, rust-tooling/ci-tests/tests/count_ignores.rs, rust-tooling/models/src/exercise_config.rs
After having removed all macro-based testing, this is no longer needed.
=> Remove unused ignore-count-ignores

exercises/practice/dominoes/.meta/test_template.tera, exercises/practice/dominoes/.meta/tests.toml, exercises/practice/dominoes/tests/dominoes.rs
=> dominoes: sync

exercises/practice/grade-school/.meta/additional-tests.json, exercises/practice/grade-school/.meta/example.rs, exercises/practice/grade-school/.meta/test_template.tera, exercises/practice/grade-school/.meta/tests.toml, exercises/practice/grade-school/tests/grade-school.rs
=> grade-school: sync

exercises/practice/gigasecond/.meta/test_template.tera, exercises/practice/gigasecond/.meta/tests.toml, exercises/practice/gigasecond/tests/gigasecond.rs
The small util function for constructing a `DateTime` value was left as is because it's only noise and not necessary to understand what's going on in the test case.
=> gigasecond: sync

exercises/practice/grains/.meta/test_template.tera, exercises/practice/grains/.meta/tests.toml, exercises/practice/grains/tests/grains.rs
=> grains: sync

exercises/practice/minesweeper/.meta/test_template.tera, exercises/practice/minesweeper/.meta/tests.toml, exercises/practice/minesweeper/tests/minesweeper.rs
=> minesweeper: sync

exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.meta/test_template.tera, exercises/practice/luhn/.meta/tests.toml, exercises/practice/luhn/tests/luhn.rs
=> luhn: sync

exercises/practice/paasio/tests/paasio.rs
This is by no means perfect, but I attempted to make the test functions a little more concise and readable. This is desirable when the test code is shown to users online, while it wasn't a requirement when these tests were generated by macros.
=> paasio: simplify tests

exercises/practice/robot-name/tests/robot-name.rs
This is another case where I think it makes sense to actually keep the util function around. It produces a good error message and in combination with the body of the test function, users should have enough information.
As the comment in the diff already states, the removed tests are redundant because the type system prevents such errors anyway.
=> robot-name: remove redundant tests

exercises/practice/pig-latin/.meta/Cargo-example.toml, exercises/practice/pig-latin/.meta/example.rs, exercises/practice/robot-name/.meta/Cargo-example.toml, exercises/practice/robot-name/.meta/example.rs
This crate is not needed anymore since all its functionality has been merged into the standard library over time.
=> Remove lazy_static

exercises/practice/simple-linked-list/src/lib.rs
=> simple-linked-list: clarify vector order

exercises/practice/sublist/src/lib.rs
This necessitated adding `std::fmt::Debug` as a constraint to `T`. All of the types in the tests are `i32` so this does not cause the tests to break.
Corresponding forum post: https://forum.exercism.org/t/warn-explain-or-remove-variables/15285
=> Sublist: use args in todo! instead of naming with _

exercises/practice/palindrome-products/.meta/example.rs, exercises/practice/palindrome-products/.meta/test_template.tera, exercises/practice/palindrome-products/src/lib.rs, exercises/practice/palindrome-products/tests/palindrome-products.rs
Apologies if I did something wrong, struggled a little bit with the rust-tooling.
Please let me know of any mistake, miss, or decisions you disagree with, no matter how small. **No hard feelings.** 
Used a `HashSet<(u64, u64)>` for factors to avoid dealing with ordering of the factors and simultaneously communicate that the order doesn't matter. I thought leaving the inner tuple sorted made sense since that's how it appears in the instructions:
> [...] The largest palindrome product is 9. Its factors are (1, 9) and (3, 3).
A sorted `Vec` would probably be fine, and the change can be made easily enough if you think it would be more appropriate.
There were two extra tests on the now-defunct `Palindrome::new` function. I felt those only made sense if this exercise still contained the newtype …
=> palindrome-products: require factors in solution

exercises/practice/binary-search/.approaches/introduction.md
In the recursion section, `offset` is not defined. I updated it to match https://exercism.org/tracks/rust/exercises/binary-search/approaches/recursion.
=> Remove undefined offset variable from `tracks/rust/exercises/binary-search/dig_deeper`

exercises/practice/atbash-cipher/.meta/test_template.tera, exercises/practice/atbash-cipher/.meta/tests.toml, exercises/practice/atbash-cipher/tests/atbash-cipher.rs
This should stop configlet's warnings about missing tests. Please let me know if things like this are worth doing or if I should just let old code be as long as it's working.
=> atbash-cipher: Use Tera template for tests

exercises/practice/luhn-trait/.docs/instructions.md
Current rust book url is no longer valid. Updated with the active url of the trait page.
=> Luhn trait: update rust book url

exercises/practice/simple-cipher/.meta/tests.toml
Confirmed that all tests are defined, creating a Tera template is not really possible since canonical_data has some fields that are expressions rather than values. Besides many of the test cases have hilariously long descriptions which would not look good as function names.
Link to canonical_data.json for convenience: https://github.com/exercism/problem-specifications/blob/47b3bb2a1c88bf93d540916477a3b71ff94e9964/exercises/simple-cipher/canonical-data.json
=> simple-cipher: Sync tests.toml

exercises/practice/diamond/.meta/test_template.tera, exercises/practice/diamond/.meta/tests.toml, exercises/practice/diamond/tests/diamond.rs
=> diamond: Sync tests and generate them with Tera

exercises/practice/etl/.meta/test_template.tera, exercises/practice/etl/.meta/tests.toml, exercises/practice/etl/tests/etl.rs
Also changed the tests to use `BTreeMap::from` instead of the custom functions for better clarity.
=> etl: Sync tests and generate them with Tera

rust-tooling/generate/src/lib.rs, rust-tooling/generate/src/main.rs, rust-tooling/generate/tests/tera_templates_are_in_sync.rs
This ensures that all other files are still written to disk as expected. There is no risk of an invalid template being merged, because the generated fallback tests will always fail in CI.
=> generate: don't crash on invalid templates

justfile
`bin/` is the only directory where we have shell scripts. This will fail if shellcheck is not installed, but even the Ubuntu repos have it, so nobody should have trouble installing it.
=> run shellcheck in local test script

exercises/practice/doubly-linked-list/tests/step_4_leak_test_2.rs
Previously the check may fail due to an underflow in the subtraction, rather than the assert.
Forum discussion:
https://forum.exercism.org/t/fix-operand-order-in-leaked-bytes-check-in-leak-test-doubly-linked-list-rust-exercise/15884
=> doubly-linked-list: improve leak check

exercises/practice/macros/tests/invalid/Cargo.toml, exercises/practice/macros/tests/macros.rs
This regression was introduced in:
88c13fb21eacd6d4101b98f900e525fe1be3d1ca
Co-authored-by: yjhtry <860622588@qq.com>
=> macros: fix invalid file paths

exercises/practice/doubly-linked-list/.meta/config.json, exercises/practice/doubly-linked-list/Cargo.toml
The reason given for why this exercise was allowed to not compile
doesn't seem to apply anymore.
=> doubly-linked-list: check compilation in ci

exercises/practice/matching-brackets/.meta/test_template.tera, exercises/practice/matching-brackets/.meta/tests.toml, exercises/practice/matching-brackets/tests/matching_brackets.rs
Some shenanigans was going on where tests were missing in `tests.toml` but were actually implemented in the test file. With this everything is consistent.
Specifically
fn early_incomplete_brackets() {}
fn early_mismatched_brackets() {}
=> matching-brackets: Sync tests and add test template

exercises/practice/difference-of-squares/.meta/test_template.tera, exercises/practice/difference-of-squares/.meta/tests.toml
I considered adding the [tera_text_filters](https://docs.rs/tera-text-filters/latest/tera_text_filters/) crate but decided on if statements to avoid adding more dependencies.
With a snake_case filter, the template could be written without the `function` variable.
P. S.: I didn't forget to run `update-exercise` there is just no diff on the test file.
=> difference_of_squares: Sync tests & add template

exercises/practice/simple-cipher/.meta/example.rs, exercises/practice/simple-cipher/Cargo.toml
On [simple-cipher](https://exercism.org/tracks/rust/exercises/simple-cipher), we can update the `rand` version to the latest version because the new version has [several function name changes](https://github.com/rust-random/rand/blob/master/CHANGELOG.md#features) that, if you don't realize that you are looking at the wrong version of the doc, give meaningless errors like `expected function, found module 'rand::rng'` or `module 'rng' is private` (and it's even worse if you are looking at the [rust-rand-book](https://rust-random.github.io/book/quick-start.html), because it doesn't say the version anywhere). 
I saw that the rust-test-runner already [updated](https://github.com/exercism/rust-test-runner/commit/dff9e549a47efb99d14f98162a310d84e3102500#diff-4c3a26ef0093cb7ed4c5ed89ef6f170551d56a …
=> Update dependencie rand to 0.9 on simple-cipher

exercises/practice/parallel-letter-frequency/.meta/tests.toml, exercises/practice/parallel-letter-frequency/tests/parallel_letter_frequency.rs
The tests are unique and not really in sync with problem-specifications, however they test the same behavior so it should be fine? I thought I'd make a PR before making a template since it might make sense to keep the bespoke tests that we have now. **Would like any input on this.**
The tests I added were missing, but they are just convenience tests for students to be able to iterate their solution, so I think this is appropriate:
=> parallel-letter-frequency: Sync tests & add missing

concepts/string-vs-str/links.json
Hey! 
Just fixed the link, the current one shows 404.
=> Fix Working with strings in Rust link

exercises/practice/say/.docs/instructions.append.md
The "Say" exercise contains the statement that is not true, at least no longer:
> There is a -1 version of a test case, but it is commented out. If your function is implemented properly, the -1 test case should not compile.
Remove this paragraph to avoid confusion.
=> Fix appended instructions for Say exercise

justfile
This is especially relevant for the add-exercise workflow, which will suggest slugs of unimplemented exercises from problem-specifications only if the symlink exists. Otherwise no suggestions are made without any hint that something went wrong.
=> Ensure problem-specifications is symlinked

exercises/practice/accumulate/.meta/config.json, exercises/practice/accumulate/src/lib.rs, exercises/practice/xorcism/src/lib.rs, rust-tooling/ci-tests/tests/no_underscore_prefixed_idents.rs
* accumulate doesn't need to be in the exceptions list because it doesn't compile independent of the argument name and it is allowed to do so.
* xorcism doesn't need to be in the exceptions list because the compiler doesn't actually complain about the unused field if the name doesn't have a prefix. This only applies to fields of type `PhantomData`. I believe this must be a recent addition. It's nice, because the compiler can know that `PhantomData` is obviously never read.
* Fix some typos in the documentation of the test.
=> Improve test no_underscore_prefixed_idents

exercises/shared/.docs/help.md
When on an exercise (for example
[this one](https://exercism.org/tracks/rust/exercises/paasio/edit)) in the `Get help` tab, in the `Feedback, Issues, Pull Requests` paragraph, there's a link to GitHub `track repository` for `feedback about an exercise, or want to help implement new exercises`
However, when such an issue is opened it is automatically closed, redirecting to this forum ([example](https://github.com/exercism/rust/issues/2087)).
=> Point to the forum instead of GitHub for feedback and help.

.github/workflows/tests.yml, rust-tooling/ci-tests/tests/stubs_are_warning_free.rs
Putting the clippy output in a log file is somewhat convenient for local use. But if there's a failure in CI that's difficult to reproduce locally, it only makes things harder to debug.
The actual problem must've been that clippy used to be installed in the GitHub Actions environment by default (but not anymore), so we didn't notice that it's not explicitly requested in our workflow.
=> Do not hide test output in log file
